import React,{useEffect,useState}from'react';
const roles=['planner','developer','tester','reviewer'];
const labels:Record<string,string>={planner:'Planner',developer:'Developer',tester:'Tester',reviewer:'Reviewer'};
const equal=(left:any,right:any)=>JSON.stringify(left)===JSON.stringify(right);
type Props={workspace:{id:string};notify:(message:string,tone?:'success'|'error'|'info')=>void};
export default function WorkspaceAgentConfig({workspace,notify}:Props){const[data,setData]=useState<any>(null),[providers,setProviders]=useState<any[]>([]),[savedConfig,setSavedConfig]=useState<any>(null),[draftConfig,setDraftConfig]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{try{const[c,p]=await Promise.all([fetch(`/api/workspaces/${workspace.id}/provider-config`).then(r=>{if(!r.ok)throw new Error('Falha ao carregar a configuração do workspace.');return r.json()}),fetch('/api/provider-registry').then(r=>{if(!r.ok)throw new Error('Falha ao carregar os providers.');return r.json()})]);setData(c);setProviders(p);setSavedConfig(c.effective||{});setDraftConfig(c.effective||{});setError('')}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar a configuração do workspace.')}};
 useEffect(()=>{void load()},[workspace.id]);
 const update=(role:string,key:string,value:string)=>setDraftConfig((old:any)=>({...old,[role]:{...old[role],[key]:value}}));
 const updateProvider=(role:string,providerId:string)=>{const next=providers.find(x=>x.id===providerId);setDraftConfig((old:any)=>({...old,[role]:{provider:providerId,model:next?.models?.[0]?.modelId||''}}))};
 const invalid=roles.find(role=>{const c=draftConfig?.[role],p=providers.find(x=>x.id===c?.provider);return !c?.provider||!c?.model||!p?.models?.some((m:any)=>m.modelId===c.model)});
 const dirty=Boolean(draftConfig)&&!equal(savedConfig,draftConfig);
 const save=async()=>{if(!dirty||invalid||busy)return;setBusy(true);setError('');try{const response=await fetch(`/api/workspaces/${workspace.id}/provider-config`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(draftConfig)});if(!response.ok)throw new Error('Falha ao salvar a configuração do workspace.');const persisted=await response.json();setData(persisted);setSavedConfig(persisted.effective||draftConfig);setDraftConfig(persisted.effective||draftConfig);notify('Configuração do workspace salva.','success')}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar a configuração do workspace.');notify('Não foi possível salvar a configuração do workspace.','error')}finally{setBusy(false)}};
 const useGlobal=async()=>{if(busy||!data?.workspace||Object.keys(data.workspace).length===0)return;setBusy(true);setError('');try{const response=await fetch(`/api/workspaces/${workspace.id}/provider-config`,{method:'DELETE'});if(!response.ok)throw new Error('Falha ao remover a configuração personalizada.');const persisted=await response.json();setData(persisted);setSavedConfig(persisted.effective||{});setDraftConfig(persisted.effective||{});notify('Configuração global aplicada.','success')}catch(e){setError(e instanceof Error?e.message:'Falha ao remover a configuração personalizada.');notify('Não foi possível usar a configuração global.','error')}finally{setBusy(false)}};
 const hasOverride=Boolean(data?.workspace&&Object.keys(data.workspace).length>0);return <section className="panel workspace-agent-config"><div className="panel-title"><span>AGENTS DO WORKSPACE</span><span className="muted">{hasOverride?'Configuração personalizada':'Usando configuração global'}</span></div>{error&&<div className="notice warning">{error}</div>}{draftConfig&&roles.map(role=>{const c=draftConfig[role]||{provider:'',model:''},p=providers.find(x=>x.id===c.provider);return <div className="workspace-provider-role" key={role}><strong>{labels[role]}</strong><label>Provider<select value={c.provider} onChange={e=>updateProvider(role,e.target.value)}>{providers.filter(x=>x.roles?.includes(role)).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Modelo<select value={c.model} onChange={e=>update(role,'model',e.target.value)}>{(p?.models||[]).map((m:any)=><option key={m.modelId} value={m.modelId}>{m.modelId}</option>)}</select></label></div>})}{invalid&&<div className="notice warning">Selecione um provider e modelo válido para {labels[invalid]} antes de salvar.</div>}<div className="modal-foot"><button type="button" className="primary" disabled={!dirty||Boolean(invalid)||busy} onClick={save}>{busy?'Salvando…':dirty?'Salvar alterações':'Sem alterações'}</button><button type="button" className="secondary" disabled={!hasOverride||busy} onClick={useGlobal}>Usar configuração global</button></div></section>}
