import type {AgentRole,ExecutionContext,FailureKind,ProviderAdapter,ProviderExecutionResult,TaskStatus} from '@orchestrator/shared';
export const roleToStatus: Record<AgentRole,TaskStatus>={analyst:'analyzing',planner:'planning',developer:'implementing',tester:'testing',reviewer:'reviewing'};
export interface RetryPolicy {maxRetries:number; retryOn:FailureKind[]; backoffMs:number;}
export const DEFAULT_RETRY_POLICY: RetryPolicy={maxRetries:2,retryOn:['provider_error','timeout'],backoffMs:200};
export class WorkspaceLockManager {private locks=new Map<string,string>(); acquire(key:string,owner:string){const current=this.locks.get(key);if(current&&current!==owner)throw new Error(`Lock busy: ${key}`);this.locks.set(key,owner);} release(key:string,owner:string){if(this.locks.get(key)===owner)this.locks.delete(key);} isLocked(key:string){return this.locks.has(key);}}
export class BudgetExceededError extends Error {kind:FailureKind='budget_exceeded'; constructor(message='Execution budget exceeded'){super(message);}}
export class BudgetGuard {constructor(private readonly taskBudgetUsd:number,private readonly tokenBudget:number){} assertCanStart(spend:number,tokens:number){if(this.taskBudgetUsd>0&&spend>=this.taskBudgetUsd)throw new BudgetExceededError();if(this.tokenBudget>0&&tokens>=this.tokenBudget)throw new BudgetExceededError('Token budget exceeded');}}
export class ExecutionWatchdog {private timer?:ReturnType<typeof setInterval>;private last=Date.now();private stalled=false;constructor(private readonly timeoutMs:number,private readonly onStalled:()=>void){} beat(){if(!this.stalled)this.last=Date.now();} start(){this.stalled=false;this.last=Date.now();this.timer=setInterval(()=>{if(!this.stalled&&Date.now()-this.last>this.timeoutMs){this.stalled=true;this.onStalled();}},Math.max(25,Math.floor(this.timeoutMs/2)));} stop(){if(this.timer)clearInterval(this.timer);this.timer=undefined;}}
export class PipelineRunner {constructor(private readonly adapter:ProviderAdapter,private readonly hooks:{onStageStart:(role:AgentRole,parentExecutionId?:string)=>void;onStageComplete:(role:AgentRole,result:ProviderExecutionResult)=>void;onProgress:(role:AgentRole,message:string,percent?:number)=>void;onHeartbeat:(role:AgentRole)=>void;onFailure:(role:AgentRole,error:unknown)=>void}){} async run(context:Omit<ExecutionContext,'stage'>,pipeline:AgentRole[],startIndex=0,signal?:AbortSignal,retryPolicy:RetryPolicy=DEFAULT_RETRY_POLICY){const outputs:string[]=[];for(let i=startIndex;i<pipeline.length;i++){const role=pipeline[i];if(signal?.aborted)throw Object.assign(new Error('Execution cancelled'),{kind:'cancelled'});this.hooks.onStageStart(role);let attempt=0;while(true){try{const result=await this.adapter.execute({...context,stage:role,signal,onProgress:(m,p)=>this.hooks.onProgress(role,m,p),onHeartbeat:()=>this.hooks.onHeartbeat(role)});outputs.push(result.output);this.hooks.onStageComplete(role,result);break;}catch(error){this.hooks.onFailure(role,error);const kind=(error as {kind?:FailureKind}).kind||'provider_error';if(attempt>=retryPolicy.maxRetries||!retryPolicy.retryOn.includes(kind))throw error;attempt++;await new Promise(r=>setTimeout(r,retryPolicy.backoffMs*attempt));}}}return outputs;}}
export function resumeIndex(pipeline:AgentRole[],lastSuccessful?:AgentRole){if(!lastSuccessful)return 0;const index=pipeline.indexOf(lastSuccessful);return index<0?0:index+1;}
