import type {AgentRole,ExecutionContext,FailureKind,ProviderAdapter,ProviderExecutionResult,TaskStatus} from '@orchestrator/shared';
import {buildStageContext} from './context-builder.js';
export * from './project-context.js';

export const roleToStatus:Record<AgentRole,TaskStatus>={analyst:'analyzing',planner:'planning',developer:'implementing',tester:'testing',reviewer:'reviewing'};
export interface RetryPolicy{maxRetries:number;retryOn:FailureKind[];backoffMs:number;}
export const DEFAULT_RETRY_POLICY:RetryPolicy={maxRetries:2,retryOn:['provider_error','timeout'],backoffMs:200};
export class WorkspaceLockManager{private locks=new Map<string,string>();acquire(key:string,owner:string){const current=this.locks.get(key);if(current&&current!==owner)throw new Error(`Lock busy: ${key}`);this.locks.set(key,owner);}release(key:string,owner:string){if(this.locks.get(key)===owner)this.locks.delete(key);}isLocked(key:string){return this.locks.has(key);}}
export class BudgetExceededError extends Error{kind:FailureKind='budget_exceeded';constructor(message='Execution budget exceeded'){super(message);}}
export class BudgetGuard{constructor(private readonly taskBudgetUsd:number,private readonly tokenBudget:number){}assertCanStart(spend:number,tokens:number){if(this.taskBudgetUsd>0&&spend>=this.taskBudgetUsd)throw new BudgetExceededError();if(this.tokenBudget>0&&tokens>=this.tokenBudget)throw new BudgetExceededError('Token budget exceeded');}}
export class ExecutionWatchdog{private timer?:ReturnType<typeof setInterval>;private last=Date.now();private stalled=false;constructor(private readonly timeoutMs:number,private readonly onStalled:()=>void){}beat(){if(!this.stalled)this.last=Date.now();}start(){this.stalled=false;this.last=Date.now();this.timer=setInterval(()=>{if(!this.stalled&&Date.now()-this.last>this.timeoutMs){this.stalled=true;this.onStalled();}},Math.max(25,Math.floor(this.timeoutMs/2)));}stop(){if(this.timer)clearInterval(this.timer);this.timer=undefined;}}
export interface FixCycleOptions{enabled?:boolean;maxCycles?:number;onCycleStart?:(cycle:number,issues:string[])=>void|Promise<void>;onCycleComplete?:(cycle:number,status:string)=>void|Promise<void>;}
const snapshotOptions=(context:Omit<ExecutionContext,'stage'>)=>{const snapshot:any=context.task.configSnapshot;return{enabled:snapshot?.autoFixEnabled===undefined?true:snapshot.autoFixEnabled===true,maxCycles:Number.isInteger(snapshot?.maxFixCycles)&&snapshot.maxFixCycles>=0?snapshot.maxFixCycles:2};};
const reviewIssues=(result:ProviderExecutionResult)=>{const issues=(result.structuredResult as any)?.issues||[];return Array.isArray(issues)?issues.map((issue:any,index:number)=>`${index+1}. Severity: ${issue.severity||'unknown'}; File: ${issue.file||'general'}; Issue: ${issue.description||''}`):[];};
const testerIssues=(result:ProviderExecutionResult)=>{const value=result.structuredResult as any;const commands=Array.isArray(value?.commands)?value.commands:[];const issues=commands.filter((item:any)=>item.status!=='passed').map((item:any,index:number)=>`${index+1}. TEST FAILURE; Command: ${item.label||item.commandId||'unknown'}; Status: ${item.status}; Exit code: ${item.exitCode??'n/a'}; stderr: ${String(item.stderr||'').slice(0,500)}`);const browser=value?.browserQa;if(browser&&browser.status==='FAILED'){for(const route of browser.routes||[]){for(const error of route.errors||[]){const detail=typeof error==='string'?{type:'browser',message:error}:error;issues.push(`${issues.length+1}. TEST FAILURE; Browser QA; Route: ${route.route}; Type: ${detail.type||'browser'}; Message: ${String(detail.message||detail).slice(0,500)}; Screenshot: ${route.screenshot?.path||'none'}`);}}for(const scenario of browser.scenarios||[]){if(scenario.status==='FAILED'){for(const step of scenario.steps||[]){if(step.status==='FAILED')issues.push(`${issues.length+1}. TEST FAILURE; Interactive Browser QA; Scenario: ${scenario.name}; Step: ${step.index}; Action: ${step.action}; Target: ${JSON.stringify(step.target||{})}; Message: ${String(step.message||scenario.error||'scenario failed').slice(0,500)}; Screenshot: ${step.screenshot||scenario.screenshots?.at?.(-1)||'none'}`);}}}}return issues;};
const pipelineIncompleteError=(pipeline:AgentRole[],completedStages:AgentRole[],reason?:string)=>Object.assign(new Error(`Pipeline incomplete: required stage(s) were not completed: ${pipeline.filter(stage=>!completedStages.includes(stage)).join(', ')}`),{kind:'pipeline_incomplete',code:'pipeline_incomplete',details:{pipeline,completedStages,missingStages:pipeline.filter(stage=>!completedStages.includes(stage)),reason}});

export class PipelineRunner{
 constructor(private readonly adapter:ProviderAdapter,private readonly hooks:{onStageStart:(role:AgentRole,parentExecutionId?:string,context?:ExecutionContext)=>void|Promise<void>;onStageComplete:(role:AgentRole,result:ProviderExecutionResult)=>void|Promise<void>;onProgress:(role:AgentRole,message:string,percent?:number)=>void;onHeartbeat:(role:AgentRole)=>void;onFailure:(role:AgentRole,error:unknown)=>void|Promise<void>;beforeStage?:(role:AgentRole,context?:ExecutionContext)=>void|Promise<void>}){}
 async run(context:Omit<ExecutionContext,'stage'>,pipeline:AgentRole[],startIndex=0,signal?:AbortSignal,retryPolicy:RetryPolicy=DEFAULT_RETRY_POLICY,contextForStage?:(role:AgentRole,base:Omit<ExecutionContext,'stage'>)=>ExecutionContext,fixOptions?:FixCycleOptions){
  const outputs:string[]=[];const configured=snapshotOptions(context);const autoFix=fixOptions?.enabled??configured.enabled;const maxCycles=fixOptions?.maxCycles??configured.maxCycles;let cycle=0;let previousIssues:string[]=[];let completedStages:AgentRole[]=[];
  while(true){
   const cyclePipeline=cycle===0?pipeline:pipeline.slice(Math.max(0,pipeline.indexOf('developer')));
   const cycleContext={...context,task:{...context.task,fixCycle:cycle}};
   let cycleNeedsFix=false;
   for(let index=cycle===0?startIndex:0;index<cyclePipeline.length;index++){
    const role=cyclePipeline[index];const stageContext=contextForStage?.(role,cycleContext)||this.buildContext(role,cycleContext);
    if(role==='developer'&&previousIssues.length&&stageContext.stageContext){const basePrompt=stageContext.stageContext.prompt;const issueText=previousIssues.join('\n');stageContext.stageContext={...stageContext.stageContext,prompt:`${basePrompt}\n\nREVIEW ISSUES\n${issueText}`,contextChars:basePrompt.length+issueText.length};}
    if(signal?.aborted){stageContext.reviewBundle?.cleanup?.();throw Object.assign(new Error('Execution cancelled'),{kind:'cancelled'});}
    await this.hooks.beforeStage?.(role,stageContext);await this.hooks.onStageStart(role,undefined,stageContext);let attempt=0;let result:ProviderExecutionResult|undefined;
    while(true){try{result=await this.adapter.execute({...stageContext,signal,onProgress:(m,p)=>this.hooks.onProgress(role,m,p),onHeartbeat:()=>this.hooks.onHeartbeat(role)});outputs.push(result.output);await this.hooks.onStageComplete(role,result);completedStages=[...new Set([...completedStages,role])];stageContext.reviewBundle?.cleanup?.();if(stageContext.reviewBundle)console.info('review.bundle.cleaned',{taskId:stageContext.task.id,role,fixCycle:cycle});break;}catch(error){await this.hooks.onFailure(role,error);const kind=(error as {kind?:FailureKind}).kind||'provider_error';if(!shouldRetry(kind,attempt,retryPolicy)){stageContext.reviewBundle?.cleanup?.();throw error;}attempt++;if(stageContext.reviewBundle)console.info('review.bundle.reused',{taskId:stageContext.task.id,role,attempt,fixCycle:cycle});await new Promise(resolve=>setTimeout(resolve,retryPolicy.backoffMs*attempt));}}
    if(role==='tester'){const testerStatus=(result?.structuredResult as any)?.status;if(testerStatus==='FAILED'){previousIssues=testerIssues(result);cycleNeedsFix=true;await fixOptions?.onCycleComplete?.(cycle,'TEST_FAILED');if(!autoFix||cycle>=maxCycles){if(pipeline.includes('reviewer'))throw pipelineIncompleteError(pipeline,completedStages);return outputs;}await fixOptions?.onCycleStart?.(cycle+1,previousIssues);break;}if(testerStatus==='BLOCKED'&&(context.task.configSnapshot as any)?.testerRequired===true){if(pipeline.includes('reviewer'))throw pipelineIncompleteError(pipeline,completedStages,'tester_blocked');return outputs;}}
    if(role==='reviewer'){if(result?.structuredResult?.status==='NEEDS_FIX'){previousIssues=reviewIssues(result);cycleNeedsFix=true;await fixOptions?.onCycleComplete?.(cycle,'NEEDS_FIX');if(!autoFix||cycle>=maxCycles)return outputs;await fixOptions?.onCycleStart?.(cycle+1,previousIssues);break;}previousIssues=[];return outputs;}
   }
   if(!cycleNeedsFix){if(pipeline.includes('reviewer')&&!completedStages.includes('reviewer'))throw pipelineIncompleteError(pipeline,completedStages);return outputs;}cycle++;
  }
 }
 private buildContext(role:AgentRole,base:Omit<ExecutionContext,'stage'>):ExecutionContext{const diff=base.previousArtifacts.find(a=>a.type==='diff');let changedFiles:string[]=[];try{const value=diff?JSON.parse(diff.content):undefined;changedFiles=value?.changes?.filesChanged||value?.actualFilesChanged||[];}catch{}const stageContext=buildStageContext({task:base.task,role,workspaceContext:base.workspaceContext,projectRules:base.projectRules,artifacts:base.previousArtifacts,changedFiles,diff:diff?.content,acceptanceCriteria:[`The requested outcome is implemented and verified: ${base.task.description}`],tests:base.previousArtifacts.filter(a=>a.type==='test_report').map(a=>a.content),projectContext:(base as any).projectContext});return{...base,stage:role,stageContext};}
}
export function resumeIndex(pipeline:AgentRole[],lastSuccessful?:AgentRole){if(!lastSuccessful)return 0;const index=pipeline.indexOf(lastSuccessful);return index<0?0:index+1;}
export interface ResumeControl{canResume:boolean;resumeFromStage:AgentRole|null;blockedReason:string|null;}
export function getResumeControl(input:{pipeline:AgentRole[];lastSuccessfulStage?:AgentRole;status?:string;environmentStatus?:string;resumable?:boolean;budgetExceeded?:{tokenUsage?:number};workspaceTokenLimitExceeded?:{tokenUsage?:number};tokenUsage?:number;tokenBudget?:number;workspaceLimitActive?:boolean}):ResumeControl{const next=input.pipeline[resumeIndex(input.pipeline,input.lastSuccessfulStage)]||null;const terminal=['approved','applied','discarded'];if(terminal.includes(input.status||'')||['applied','discarded'].includes(input.environmentStatus||''))return{canResume:false,resumeFromStage:null,blockedReason:null};if(!next)return{canResume:false,resumeFromStage:null,blockedReason:null};const usage=Number(input.tokenUsage||input.budgetExceeded?.tokenUsage||0);if(input.budgetExceeded&&Number(input.tokenBudget||0)>0&&usage>=Number(input.tokenBudget)){return{canResume:false,resumeFromStage:next,blockedReason:'Limite de tokens da task ainda precisa ser aumentado para permitir a retomada.'};}const preservedEnvironment=['manual_review_preserved','failed_preserved'].includes(input.environmentStatus||'');if(input.workspaceTokenLimitExceeded&&!preservedEnvironment)return{canResume:false,resumeFromStage:null,blockedReason:null};if(input.workspaceTokenLimitExceeded&&input.workspaceLimitActive)return{canResume:false,resumeFromStage:next,blockedReason:'Retomada disponível após liberar o limite do workspace.'};if(input.workspaceTokenLimitExceeded||input.budgetExceeded||input.resumable||['failed','stalled','needs_manual_review'].includes(input.status||''))return{canResume:true,resumeFromStage:next,blockedReason:null};return{canResume:false,resumeFromStage:null,blockedReason:null};}
export const NON_RETRYABLE_FAILURES:FailureKind[]=['configuration_error','cli_invocation_error','validation_error','authentication_error','cancelled','budget_exceeded'];
export function shouldRetry(kind:FailureKind,attempt:number,policy:RetryPolicy=DEFAULT_RETRY_POLICY){return attempt<policy.maxRetries&&!NON_RETRYABLE_FAILURES.includes(kind)&&policy.retryOn.includes(kind);}
export interface PipelineApprovalIntegrity{pipeline:AgentRole[];completedStages:AgentRole[];missingStages:AgentRole[];reviewerExecution?:Record<string,unknown>;}
export function assertPipelineApprovalIntegrity(task:{pipeline?:AgentRole[];lastSuccessfulStage?:AgentRole},executions:Array<{role?:string;status?:string;structuredResult?:unknown}>,pipelineOverride?:AgentRole[]){const pipeline=pipelineOverride||task.pipeline||[];const completedStages=[...new Set(executions.filter(execution=>execution.status==='completed').map(execution=>execution.role).filter((role):role is AgentRole=>Boolean(role)))];const missingStages=pipeline.filter(stage=>!completedStages.includes(stage));const reviewerRequired=pipeline.includes('reviewer');const reviewerExecution=[...executions].reverse().find(execution=>execution.role==='reviewer'&&execution.status==='completed');const reviewerApproved=(reviewerExecution?.structuredResult as any)?.status==='APPROVED';if(reviewerRequired&&(!reviewerExecution||!reviewerApproved||task.lastSuccessfulStage!=='reviewer')){const details:PipelineApprovalIntegrity={pipeline,completedStages,missingStages:missingStages.length?missingStages:['reviewer'],reviewerExecution:reviewerExecution as Record<string,unknown>|undefined};throw Object.assign(new Error(`Pipeline approval integrity failed: reviewer approval is required; missing stages: ${details.missingStages.join(',')||'none'}`),{kind:'pipeline_incomplete',code:'pipeline_incomplete',details});}return{pipeline,completedStages,missingStages,reviewerExecution};}
export * from './prompt-refiner.js';
export * from './context-builder.js';
export * from './usage.js';
export * from './mission-planner.js';
