import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {existsSync,readFileSync} from 'node:fs';
import {join} from 'node:path';
import type {HumanApprovalGates,WorkspaceType} from '@orchestrator/shared';

export interface WorkspaceBaseline{gitAvailable:boolean;branch:string;statusBefore:string;diffBefore:string;stagedDiffBefore:string;untrackedBefore:string[];fileHashesBefore?:Record<string,string>;capturedAt:string;}
export interface WorkspaceStateAfter{gitAvailable:boolean;branch:string;statusAfter:string;diffAfter:string;stagedDiffAfter:string;untrackedAfter:string[];fileHashesAfter?:Record<string,string>;capturedAt:string;}
export interface WorkspaceChangeSet{added:string[];modified:string[];deleted:string[];untracked:string[];filesChanged:string[];preExistingFiles:string[];preExistingChanges:boolean;}
export interface WorkspaceTransport{type:WorkspaceType;healthCheck():Promise<boolean>;listFiles(path?:string):Promise<string[]>;readFile(path:string):Promise<string>;writeFile(path:string,content:string):Promise<void>;exec(command:string):Promise<{stdout:string;stderr:string;exitCode:number}>;gitStatus():Promise<string>;gitDiff():Promise<string>;checkout(branch:string):Promise<void>;getCurrentBranch():Promise<string>;captureBaseline?():Promise<WorkspaceBaseline>;captureState?():Promise<WorkspaceStateAfter>;getDiff?():Promise<string>;getStatus?():Promise<string>;getChangedFiles?():Promise<string[]>;}
export class LocalMockTransport implements WorkspaceTransport{type='local' as const;private files=new Map<string,string>();async healthCheck(){return true;}async listFiles(){return[...this.files.keys()];}async readFile(path:string){return this.files.get(path)||'';}async writeFile(path:string,content:string){this.files.set(path,content);}async exec(command:string){return{stdout:`mock exec: ${command}`,stderr:'',exitCode:0};}async gitStatus(){return'clean (mock)';}async gitDiff(){return'';}async checkout(){return;}async getCurrentBranch(){return'main';}}

function runGit(location:string,args:string[]){try{return{stdout:execFileSync('git',args,{cwd:location,encoding:'utf8',stdio:['ignore','pipe','pipe']}),stderr:'',exitCode:0};}catch(error:any){return{stdout:String(error.stdout||''),stderr:String(error.stderr||error.message||''),exitCode:typeof error.status==='number'?error.status:1};}}
function parseStatus(status:string){return status.split(/\r?\n/).filter(Boolean).map(line=>{const code=line.slice(0,2);const path=line.slice(3).split(' -> ').pop()||line.slice(3);return{code,path};});}
export class LocalWorkspaceTransport implements WorkspaceTransport{type='local' as const;constructor(readonly location:string){}private git(args:string[]){return runGit(this.location,args);}private untracked(){const result=this.git(['ls-files','--others','--exclude-standard']);return result.exitCode===0?result.stdout.split(/\r?\n/).filter(Boolean):[];}private fileHashes(){const result=this.git(['ls-files','-co','--exclude-standard']);const files=result.exitCode===0?result.stdout.split(/\r?\n/).filter(Boolean):[];const hashes:Record<string,string>={};for(const file of files){const full=join(this.location,file);if(!existsSync(full))continue;try{hashes[file]=createHash('sha256').update(readFileSync(full)).digest('hex');}catch{}}return hashes;}async healthCheck(){return existsSync(this.location);}async listFiles(){return this.untracked();}async readFile(path:string){return'';}async writeFile(){throw new Error('LocalWorkspaceTransport is read-only for this service');}async exec(command:string){return{stdout:'',stderr:`command not allowed: ${command}`,exitCode:1};}async gitStatus(){return this.git(['status','--porcelain']).stdout;}async gitDiff(){return this.git(['diff']).stdout;}async checkout(_branch:string){throw new Error('checkout is not available in read-only workspace inspection');}async getCurrentBranch(){const result=this.git(['rev-parse','--abbrev-ref','HEAD']);return result.exitCode===0?result.stdout.trim():'(no-git)';}async captureBaseline(){const gitAvailable=this.git(['rev-parse','--is-inside-work-tree']).exitCode===0;const capturedAt=new Date().toISOString();if(!gitAvailable)return{gitAvailable,branch:'(no-git)',statusBefore:'',diffBefore:'',stagedDiffBefore:'',untrackedBefore:[],fileHashesBefore:{},capturedAt};return{gitAvailable,branch:await this.getCurrentBranch(),statusBefore:await this.gitStatus(),diffBefore:await this.gitDiff(),stagedDiffBefore:this.git(['diff','--cached']).stdout,untrackedBefore:this.untracked(),fileHashesBefore:this.fileHashes(),capturedAt};}async captureState(){const gitAvailable=this.git(['rev-parse','--is-inside-work-tree']).exitCode===0;const capturedAt=new Date().toISOString();if(!gitAvailable)return{gitAvailable,branch:'(no-git)',statusAfter:'',diffAfter:'',stagedDiffAfter:'',untrackedAfter:[],fileHashesAfter:{},capturedAt};return{gitAvailable,branch:await this.getCurrentBranch(),statusAfter:await this.gitStatus(),diffAfter:await this.gitDiff(),stagedDiffAfter:this.git(['diff','--cached']).stdout,untrackedAfter:this.untracked(),fileHashesAfter:this.fileHashes(),capturedAt};}async getDiff(){return this.gitDiff();}async getStatus(){return this.gitStatus();}async getChangedFiles(){const state=await this.captureState();return parseStatus(state.statusAfter).map(item=>item.path);} }
export function calculateWorkspaceChangeSet(baseline:WorkspaceBaseline,after:WorkspaceStateAfter):WorkspaceChangeSet{if(!after.gitAvailable)return{added:[],modified:[],deleted:[],untracked:[],filesChanged:[],preExistingFiles:[],preExistingChanges:false};const beforeStatus=new Set([...parseStatus(baseline.statusBefore).map(item=>item.path),...baseline.untrackedBefore]);const afterEntries=parseStatus(after.statusAfter);const beforeHashes=baseline.fileHashesBefore;const afterHashes=after.fileHashesAfter;const filesChanged:string[]=[];if(beforeHashes&&afterHashes){for(const file of new Set([...Object.keys(beforeHashes),...Object.keys(afterHashes)])){if(beforeHashes[file]!==afterHashes[file])filesChanged.push(file);}}else{const afterFiles=new Set([...afterEntries.map(item=>item.path),...after.untrackedAfter]);filesChanged.push(...[...afterFiles].filter(file=>!beforeStatus.has(file)));}const added:string[]=[];const modified:string[]=[];const deleted:string[]=[];for(const file of filesChanged){const before=beforeHashes?.[file];const afterHash=afterHashes?.[file];if(!before&&afterHash)added.push(file);else if(before&&!afterHash)deleted.push(file);else modified.push(file);}for(const entry of afterEntries.filter(item=>filesChanged.includes(item.path))){if(entry.code.includes('D')&&!deleted.includes(entry.path)){deleted.push(entry.path);if(added.includes(entry.path))added.splice(added.indexOf(entry.path),1);}else if(entry.code.includes('??')&&!added.includes(entry.path)){added.push(entry.path);if(modified.includes(entry.path))modified.splice(modified.indexOf(entry.path),1);}}return{added,modified,deleted,untracked:after.untrackedAfter.filter(file=>filesChanged.includes(file)),filesChanged,preExistingFiles:[...beforeStatus],preExistingChanges:beforeStatus.size>0};}
export const defaultPolicy={denyGitPush:true,denyDeploy:true,denyDestructiveCommands:true,denySecrets:true,timeoutMs:120000,maxIterations:3,requireHumanApproval:false};
export const defaultGates:HumanApprovalGates={beforeImplementation:false,beforeCommit:false,beforeMerge:false,beforeDeploy:true,beforeDatabaseChange:true};
export function requiresApproval(gates:HumanApprovalGates,action:keyof HumanApprovalGates){return gates[action];}
export const isSupportedWorkspaceType=(type:string):type is WorkspaceType=>['local','git','ssh'].includes(type);
