import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {existsSync,readFileSync} from 'node:fs';
import {mkdirSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import type {HumanApprovalGates,WorkspaceType} from '@orchestrator/shared';

export interface WorkspaceBaseline{gitAvailable:boolean;branch:string;statusBefore:string;diffBefore:string;stagedDiffBefore:string;untrackedBefore:string[];fileHashesBefore?:Record<string,string>;capturedAt:string;}
export interface WorkspaceStateAfter{gitAvailable:boolean;branch:string;statusAfter:string;diffAfter:string;stagedDiffAfter:string;untrackedAfter:string[];fileHashesAfter?:Record<string,string>;capturedAt:string;}
export interface WorkspaceChangeSet{added:string[];modified:string[];deleted:string[];untracked:string[];filesChanged:string[];preExistingFiles:string[];preExistingChanges:boolean;}
export interface WorkspaceTransport{type:WorkspaceType;healthCheck():Promise<boolean>;listFiles(path?:string):Promise<string[]>;readFile(path:string):Promise<string>;writeFile(path:string,content:string):Promise<void>;exec(command:string):Promise<{stdout:string;stderr:string;exitCode:number}>;gitStatus():Promise<string>;gitDiff():Promise<string>;checkout(branch:string):Promise<void>;getCurrentBranch():Promise<string>;captureBaseline?():Promise<WorkspaceBaseline>;captureState?():Promise<WorkspaceStateAfter>;getDiff?():Promise<string>;getStatus?():Promise<string>;getChangedFiles?():Promise<string[]>;}
export class LocalMockTransport implements WorkspaceTransport{type='local' as const;private files=new Map<string,string>();async healthCheck(){return true;}async listFiles(){return[...this.files.keys()];}async readFile(path:string){return this.files.get(path)||'';}async writeFile(path:string,content:string){this.files.set(path,content);}async exec(command:string){return{stdout:`mock exec: ${command}`,stderr:'',exitCode:0};}async gitStatus(){return'clean (mock)';}async gitDiff(){return'';}async checkout(){return;}async getCurrentBranch(){return'main';}}

function runGit(location:string,args:string[]){try{return{stdout:execFileSync('git',args,{cwd:location,encoding:'utf8',stdio:['ignore','pipe','pipe']}),stderr:'',exitCode:0};}catch(error:any){return{stdout:String(error.stdout||''),stderr:String(error.stderr||error.message||''),exitCode:typeof error.status==='number'?error.status:1};}}
function parseStatus(status:string){return status.split(/\r?\n/).filter(Boolean).map(line=>{const code=line.slice(0,2);const path=line.slice(3).split(' -> ').pop()||line.slice(3);return{code,path};});}
export class LocalWorkspaceTransport implements WorkspaceTransport{type='local' as const;constructor(readonly location:string){}private git(args:string[]){return runGit(this.location,args);}private untracked(){const result=this.git(['ls-files','--others','--exclude-standard']);return result.exitCode===0?result.stdout.split(/\r?\n/).filter(Boolean):[];}private fileHashes(){const result=this.git(['ls-files','-co','--exclude-standard']);const files=result.exitCode===0?result.stdout.split(/\r?\n/).filter(Boolean):[];const hashes:Record<string,string>={};for(const file of files){const full=join(this.location,file);if(!existsSync(full))continue;try{hashes[file]=createHash('sha256').update(readFileSync(full)).digest('hex');}catch{}}return hashes;}async healthCheck(){return existsSync(this.location);}async listFiles(){return this.untracked();}async readFile(path:string){return'';}async writeFile(){throw new Error('LocalWorkspaceTransport is read-only for this service');}async exec(command:string){return{stdout:'',stderr:`command not allowed: ${command}`,exitCode:1};}async gitStatus(){return this.git(['status','--porcelain']).stdout;}async gitDiff(){return this.git(['diff']).stdout;}async checkout(_branch:string){throw new Error('checkout is not available in read-only workspace inspection');}async getCurrentBranch(){const result=this.git(['rev-parse','--abbrev-ref','HEAD']);return result.exitCode===0?result.stdout.trim():'(no-git)';}async captureBaseline(){const gitAvailable=this.git(['rev-parse','--is-inside-work-tree']).exitCode===0;const capturedAt=new Date().toISOString();if(!gitAvailable)return{gitAvailable,branch:'(no-git)',statusBefore:'',diffBefore:'',stagedDiffBefore:'',untrackedBefore:[],fileHashesBefore:{},capturedAt};return{gitAvailable,branch:await this.getCurrentBranch(),statusBefore:await this.gitStatus(),diffBefore:await this.gitDiff(),stagedDiffBefore:this.git(['diff','--cached']).stdout,untrackedBefore:this.untracked(),fileHashesBefore:this.fileHashes(),capturedAt};}async captureState(){const gitAvailable=this.git(['rev-parse','--is-inside-work-tree']).exitCode===0;const capturedAt=new Date().toISOString();if(!gitAvailable)return{gitAvailable,branch:'(no-git)',statusAfter:'',diffAfter:'',stagedDiffAfter:'',untrackedAfter:[],fileHashesAfter:{},capturedAt};return{gitAvailable,branch:await this.getCurrentBranch(),statusAfter:await this.gitStatus(),diffAfter:await this.gitDiff(),stagedDiffAfter:this.git(['diff','--cached']).stdout,untrackedAfter:this.untracked(),fileHashesAfter:this.fileHashes(),capturedAt};}async getDiff(){return this.gitDiff();}async getStatus(){return this.gitStatus();}async getChangedFiles(){const state=await this.captureState();return parseStatus(state.statusAfter).map(item=>item.path);} }
export function calculateWorkspaceChangeSet(baseline:WorkspaceBaseline,after:WorkspaceStateAfter):WorkspaceChangeSet{if(!after.gitAvailable)return{added:[],modified:[],deleted:[],untracked:[],filesChanged:[],preExistingFiles:[],preExistingChanges:false};const beforeStatus=new Set([...parseStatus(baseline.statusBefore).map(item=>item.path),...baseline.untrackedBefore]);const afterEntries=parseStatus(after.statusAfter);const beforeHashes=baseline.fileHashesBefore;const afterHashes=after.fileHashesAfter;const filesChanged:string[]=[];if(beforeHashes&&afterHashes){for(const file of new Set([...Object.keys(beforeHashes),...Object.keys(afterHashes)])){if(beforeHashes[file]!==afterHashes[file])filesChanged.push(file);}}else{const afterFiles=new Set([...afterEntries.map(item=>item.path),...after.untrackedAfter]);filesChanged.push(...[...afterFiles].filter(file=>!beforeStatus.has(file)));}const added:string[]=[];const modified:string[]=[];const deleted:string[]=[];for(const file of filesChanged){const before=beforeHashes?.[file];const afterHash=afterHashes?.[file];if(!before&&afterHash)added.push(file);else if(before&&!afterHash)deleted.push(file);else modified.push(file);}for(const entry of afterEntries.filter(item=>filesChanged.includes(item.path))){if(entry.code.includes('D')&&!deleted.includes(entry.path)){deleted.push(entry.path);if(added.includes(entry.path))added.splice(added.indexOf(entry.path),1);}else if(entry.code.includes('??')&&!added.includes(entry.path)){added.push(entry.path);if(modified.includes(entry.path))modified.splice(modified.indexOf(entry.path),1);}}return{added,modified,deleted,untracked:after.untrackedAfter.filter(file=>filesChanged.includes(file)),filesChanged,preExistingFiles:[...beforeStatus],preExistingChanges:beforeStatus.size>0};}
export const defaultPolicy={denyGitPush:true,denyDeploy:true,denyDestructiveCommands:true,denySecrets:true,timeoutMs:120000,maxIterations:3,requireHumanApproval:false};
export const defaultGates:HumanApprovalGates={beforeImplementation:false,beforeCommit:false,beforeMerge:false,beforeDeploy:true,beforeDatabaseChange:true};
export function requiresApproval(gates:HumanApprovalGates,action:keyof HumanApprovalGates){return gates[action];}
export const isSupportedWorkspaceType=(type:string):type is WorkspaceType=>['local','git','ssh'].includes(type);

export type TaskIsolationMode='worktree'|'current-workspace';
export type TaskEnvironmentStatus='preparing'|'active'|'approved_waiting_action'|'failed_preserved'|'manual_review_preserved'|'applying'|'applied'|'discarding'|'discarded'|'cleanup_failed'|'environment_missing'|'orphaned';
export interface TaskEnvironment{isolationMode:TaskIsolationMode;environmentStatus:TaskEnvironmentStatus;baseBranch:string;baseCommitSha:string;taskBranch?:string;worktreePath?:string;warning?:string;mainDirty:boolean;}
export interface TaskIsolationOptions{workspaceId:string;taskId:string;title:string;workspacePath:string;baseBranch?:string;mode?:TaskIsolationMode;root?:string;}
export interface GitCommandResult{stdout:string;stderr:string;exitCode:number;}
function runGitCommand(cwd:string,args:string[]){try{return{...runGit(cwd,args),args};}catch(error){return{stdout:'',stderr:String(error),exitCode:1,args};}}
function safeSlug(value:string){return value.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,48)||'task';}
export function buildTaskBranchName(taskId:string,title:string,existing:string[]=[]){const base=`task/${safeSlug(taskId).slice(0,16)}-${safeSlug(title)}`;let candidate=base.slice(0,96);let n=2;while(existing.includes(candidate))candidate=`${base.slice(0,88)}-${n++}`;return candidate;}
export class TaskIsolationManager{
 constructor(private readonly options:{root?:string}={}){}
 private root(workspaceId:string,taskId:string){return resolve(this.options.root||process.env.TASK_WORKTREE_ROOT||join(tmpdir(),'orquestradoria-worktrees'),workspaceId,taskId);}
 prepare(input:TaskIsolationOptions):TaskEnvironment{const mode=input.mode||((process.env.TASK_ISOLATION_MODE||'worktree') as TaskIsolationMode);const baseBranch=input.baseBranch||'main';const git=runGitCommand(input.workspacePath,['rev-parse','--is-inside-work-tree']);if(mode==='current-workspace'||git.exitCode!==0)return{isolationMode:'current-workspace',environmentStatus:'active',baseBranch,baseCommitSha:'',mainDirty:false,warning:git.exitCode===0?undefined:'Git isolation unavailable for this workspace.'};const dirty=runGitCommand(input.workspacePath,['status','--porcelain']).stdout.trim().length>0;const sha=runGitCommand(input.workspacePath,['rev-parse',baseBranch]);if(sha.exitCode!==0)throw new Error(`Base branch is unavailable: ${baseBranch}`);const baseCommitSha=sha.stdout.trim();const worktreePath=this.root(input.workspaceId,input.taskId);mkdirSync(resolve(this.options.root||process.env.TASK_WORKTREE_ROOT||join(tmpdir(),'orquestradoria-worktrees'),input.workspaceId),{recursive:true});const existing=runGitCommand(input.workspacePath,['for-each-ref','refs/heads/task/','--format=%(refname:short)']).stdout.split(/\r?\n/).filter(Boolean);const taskBranch=buildTaskBranchName(input.taskId,input.title,existing);const result=runGitCommand(input.workspacePath,['worktree','add','-b',taskBranch,worktreePath,baseCommitSha]);if(result.exitCode!==0)throw new Error(`Unable to create task worktree: ${result.stderr||result.stdout}`);return{isolationMode:'worktree',environmentStatus:'active',baseBranch,baseCommitSha,taskBranch,worktreePath,mainDirty:dirty,warning:dirty?'Main workspace has uncommitted changes. They are not included in this isolated task.':undefined};}
 diff(environment:TaskEnvironment,workspacePath:string){if(environment.isolationMode!=='worktree'||!environment.worktreePath||!environment.baseCommitSha)return{files:[],added:[],modified:[],deleted:[],diff:'',truncated:false};const raw=runGitCommand(environment.worktreePath,['diff','--name-status',environment.baseCommitSha,'--']);const untracked=runGitCommand(environment.worktreePath,['ls-files','--others','--exclude-standard']);const files=raw.stdout.split(/\r?\n/).filter(Boolean).map(line=>{const [status,...path]=line.split(/\s+/);return{status,path:path.join(' ')}});for(const path of untracked.stdout.split(/\r?\n/).filter(Boolean)){if(!files.some(file=>file.path===path))files.push({status:'A',path});}const patch=runGitCommand(environment.worktreePath,['diff',environment.baseCommitSha,'--']);const limit=Number(process.env.TASK_DIFF_MAX_CHARS||200000);const diff=patch.stdout.slice(0,limit);return{files,added:files.filter(f=>f.status.startsWith('A')).map(f=>f.path),modified:files.filter(f=>f.status.startsWith('M')).map(f=>f.path),deleted:files.filter(f=>f.status.startsWith('D')).map(f=>f.path),diff,truncated:patch.stdout.length>limit};}
 commitForApply(environment:TaskEnvironment,message:string){if(environment.isolationMode!=='worktree'||!environment.taskBranch||!environment.worktreePath)throw new Error('Task environment is not an isolated worktree');const status=runGitCommand(environment.worktreePath,['status','--porcelain']);if(status.exitCode!==0)throw new Error(status.stderr||'Unable to inspect task worktree');if(!status.stdout.trim())return false;const added=runGitCommand(environment.worktreePath,['add','-A']);if(added.exitCode!==0)throw new Error(added.stderr||'Unable to stage task worktree changes');const committed=runGitCommand(environment.worktreePath,['commit','-m',message]);if(committed.exitCode!==0)throw new Error(committed.stderr||'Unable to commit task worktree changes');return true;}
 apply(environment:TaskEnvironment,workspacePath:string){if(environment.isolationMode!=='worktree'||!environment.taskBranch||!environment.worktreePath)throw new Error('Task environment is not an isolated worktree');if(!environment.baseCommitSha)throw new Error('Task environment has no frozen base commit');if(runGitCommand(workspacePath,['status','--porcelain']).stdout.trim())throw Object.assign(new Error('Base workspace has uncommitted changes. Commit, stash, or resolve them before applying this task.'),{code:'apply_blocked_dirty_workspace'});const head=runGitCommand(workspacePath,['rev-parse',environment.baseBranch]).stdout.trim();if(head!==environment.baseCommitSha)throw Object.assign(new Error('Base branch advanced since task isolation was created.'),{code:'base_branch_advanced'});const result=runGitCommand(workspacePath,['merge','--no-ff',environment.taskBranch,'-m',`orchestrator: apply task ${environment.taskBranch}`]);if(result.exitCode!==0){runGitCommand(workspacePath,['merge','--abort']);throw Object.assign(new Error(result.stderr||result.stdout||'Task apply conflict'),{code:'apply_conflict'});}return true;}
 discard(environment:TaskEnvironment,workspacePath:string){if(environment.isolationMode!=='worktree'||!environment.taskBranch||!environment.worktreePath)throw new Error('Task environment is not an isolated worktree');const branch=runGitCommand(workspacePath,['show-ref','--verify',`refs/heads/${environment.taskBranch}`]);if(branch.exitCode!==0)throw new Error('Refusing to remove an unmanaged task branch');const removed=runGitCommand(workspacePath,['worktree','remove','--force',environment.worktreePath]);if(removed.exitCode!==0)throw new Error(removed.stderr||'Unable to remove task worktree');const deleted=runGitCommand(workspacePath,['branch','-D',environment.taskBranch]);if(deleted.exitCode!==0)throw new Error(deleted.stderr||'Unable to remove task branch');return true;}
 listOrphans(workspacePath:string,managedPaths:string[]){const result=runGitCommand(workspacePath,['worktree','list','--porcelain']);const paths=result.stdout.split(/\r?\n/).filter(line=>line.startsWith('worktree ')).map(line=>line.slice(9));const configuredRoot=resolve(this.options.root||process.env.TASK_WORKTREE_ROOT||join(tmpdir(),'orquestradoria-worktrees'));return paths.filter(path=>(path.startsWith(configuredRoot)||path.includes('orquestradoria-worktrees'))&&!managedPaths.includes(path)).map(path=>({path,status:'orphaned' as const}));}
}
