import {createServer,type IncomingMessage,type ServerResponse,request as httpRequest} from 'node:http';
import {createReadStream,existsSync,statSync,readFileSync} from 'node:fs';
import {join,normalize,relative,resolve,extname} from 'node:path';
import {spawn,type ChildProcess} from 'node:child_process';
import {createServer as createNetServer} from 'node:net';

export interface RuntimeProfile{type:'static'|'php'|'vite'|'unsupported';command?:{executable:string;args:string[];cwd:string};reason?:string;}
export interface RuntimeSession{id:string;profile:RuntimeProfile;pid?:number;port:number;baseUrl:string;status:'starting'|'ready'|'failed'|'stopped';startedAt:string;stoppedAt?:string;stdout:string;stderr:string;}
export interface RuntimeDetectorOptions{platform?:NodeJS.Platform;env?:NodeJS.ProcessEnv;which?:(command:string)=>string|undefined;}
const bounded=(value:string,max=12000)=>value.length<=max?value:`${value.slice(0,max)}\n...[truncated]`;
export function getFreeLocalPort():Promise<number>{return new Promise((resolvePort,reject)=>{const server=createNetServer();server.once('error',reject);server.listen(0,'127.0.0.1',()=>{const address=server.address();const port=typeof address==='object'&&address?address.port:0;server.close(error=>error?reject(error):resolvePort(port));});});}
const mime:Record<string,string>={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml','.ico':'image/x-icon'};
function staticServer(root:string){const base=resolve(root),separator=process.platform==='win32'?'\\':'/';return createServer((req:IncomingMessage,res:ServerResponse)=>{const pathname=new URL(req.url||'/', 'http://127.0.0.1').pathname;const requested=pathname==='/'?'/index.html':pathname;const file=resolve(join(base,decodeURIComponent(requested)));if(file!==base&&!file.startsWith(base+separator)&&!file.startsWith(base+'/')){res.statusCode=403;return res.end('Forbidden');}if(!existsSync(file)||!statSync(file).isFile()){res.statusCode=404;return res.end('Not found');}res.statusCode=200;res.setHeader('Content-Type',mime[extname(file).toLowerCase()]||'application/octet-stream');createReadStream(file).on('error',()=>{if(!res.headersSent)res.statusCode=500;res.end();}).pipe(res);});}
export class RuntimeDetector{constructor(private readonly options:RuntimeDetectorOptions={}){}detect(cwd:string):RuntimeProfile{const env=this.options.env||process.env;const which=this.options.which||((command:string)=>{const pathEnv=env.PATH||'';for(const entry of pathEnv.split(requirePathSeparator(this.options.platform||process.platform))){const candidate=join(entry,command);if(existsSync(candidate))return candidate;}return undefined;});if(existsSync(join(cwd,'index.php'))){const php=which('php');return php?{type:'php',command:{executable:php,args:['-S','127.0.0.1:{PORT}','-t',cwd],cwd}}:{type:'php',reason:'PHP executable not found'};}try{const packageJson=JSON.parse(readFileSync(join(cwd,'package.json'),'utf8'));const dev=String(packageJson.scripts?.dev||'');if(/vite/i.test(dev)){const manager=existsSync(join(cwd,'pnpm-lock.yaml'))?'pnpm':existsSync(join(cwd,'yarn.lock'))?'yarn':'npm';return{type:'vite',command:{executable:which(manager)||manager,args:['run','dev','--','--host','127.0.0.1','--port','{PORT}','--strictPort'],cwd}};}}catch{}if(existsSync(join(cwd,'index.html')))return{type:'static'};return{type:'unsupported',reason:'No supported web runtime was detected'};}}
function requirePathSeparator(platform:NodeJS.Platform){return platform==='win32'?';':':';}
export class RuntimeSessionManager{private readonly children=new Map<string,ChildProcess>();private readonly servers=new Map<string,ReturnType<typeof createServer>>();constructor(private readonly detector=new RuntimeDetector()){}detect(cwd:string){return this.detector.detect(cwd);}async start(cwd:string,options:{id?:string;port?:number;signal?:AbortSignal;onProgress?:(message:string)=>void}={}):Promise<RuntimeSession>{const id=options.id||`runtime-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;const profile=this.detect(cwd);const port=options.port||await getFreeLocalPort();const session:RuntimeSession={id,profile,port,baseUrl:`http://127.0.0.1:${port}`,status:'starting',startedAt:new Date().toISOString(),stdout:'',stderr:''};if(profile.type==='unsupported'||(profile.type==='php'&&!profile.command)){session.status='failed';session.stderr=profile.reason||'Runtime unavailable';return session;}if(profile.type==='static'){const server=staticServer(cwd);this.servers.set(id,server);server.on('error',error=>{session.status='failed';session.stderr=bounded(String(error));});await new Promise<void>((resolveStart,reject)=>{server.once('error',reject);server.listen(port,'127.0.0.1',()=>resolveStart());});options.onProgress?.(`Runtime disponível em ${session.baseUrl}`);}else{const command=profile.command!;const args=command.args.map(arg=>arg.replace('{PORT}',String(port)));const child=spawn(command.executable,args,{cwd:command.cwd,env:process.env,stdio:['ignore','pipe','pipe'],shell:false});session.pid=child.pid;this.children.set(id,child);child.stdout?.on('data',chunk=>{session.stdout=bounded(session.stdout+chunk.toString());});child.stderr?.on('data',chunk=>{session.stderr=bounded(session.stderr+chunk.toString());});child.on('exit',code=>{if(session.status!=='stopped'&&code!==0)session.status='failed';});}if(options.signal)options.signal.addEventListener('abort',()=>{void this.stop(session);},{once:true});try{await this.waitUntilReady(session);session.status='ready';return session;}catch(error){session.status='failed';session.stderr=bounded(`${session.stderr}\n${String(error)}`);await this.stop(session);return session;}}
async waitUntilReady(session:RuntimeSession,timeoutMs=20000){const started=Date.now();while(Date.now()-started<timeoutMs){if(session.status==='failed')throw new Error(session.stderr||'Runtime process exited');try{await new Promise<void>((resolveRequest,reject)=>{const req=httpRequest(`${session.baseUrl}/`,{method:'GET'},response=>{response.resume();response.statusCode&&response.statusCode<500?resolveRequest():reject(new Error(`Runtime responded with ${response.statusCode}`));});req.on('error',reject);req.setTimeout(1000,()=>{req.destroy();reject(new Error('readiness timeout'));});req.end();});return;}catch{await new Promise(resolveDelay=>setTimeout(resolveDelay,300));}}throw new Error(`Runtime readiness timed out after ${timeoutMs}ms`);}
async stop(session:RuntimeSession){if(session.status==='stopped')return session;const server=this.servers.get(session.id);if(server){await new Promise<void>(resolveStop=>server.close(()=>resolveStop()));this.servers.delete(session.id);}const child=this.children.get(session.id);if(child){if(process.platform==='win32'&&child.pid)spawn('taskkill.exe',['/PID',String(child.pid),'/T','/F'],{shell:false,stdio:'ignore'});else child.kill('SIGTERM');this.children.delete(session.id);}session.status='stopped';session.stoppedAt=new Date().toISOString();return session;}}
