export type WorkspaceType = 'local'|'git'|'ssh';export type WorkspaceStatus = 'active'|'paused'|'archived';
export type TaskStatus = 'pending'|'analyzing'|'planning'|'implementing'|'testing'|'reviewing'|'needs_fix'|'needs_manual_review'|'approved'|'human_review_required'|'cancelled'|'failed'|'stalled';
export type ExecutionStatus = 'queued'|'running'|'completed'|'failed'|'cancelled'|'timed_out'|'stalled';export type AgentRole='analyst'|'planner'|'developer'|'tester'|'reviewer';
export type FailureKind='provider_error'|'timeout'|'validation_error'|'configuration_error'|'cli_invocation_error'|'authentication_error'|'review_rejected'|'cancelled'|'budget_exceeded'|'pipeline_incomplete'|'acceptance_coverage_incomplete';export type ArtifactType='plan'|'implementation_summary'|'diff'|'review'|'test_report'|'browser_qa_report'|'browser_qa_plan'|'acceptance_criteria'|'acceptance_coverage_plan'|'acceptance_coverage'|'log'|'generated_file'|'context_snapshot'|'workspace_baseline'|'context_manifest';
export type BrowserScenarioAction='goto'|'fill'|'click'|'selectOption'|'check'|'uncheck'|'press'|'reload'|'waitForVisible'|'expectVisible'|'expectHidden'|'expectText'|'expectValue'|'expectCount'|'screenshot'|'clearStorage';
export const ARIA_ROLES=['alert','alertdialog','application','article','banner','button','cell','checkbox','columnheader','combobox','complementary','contentinfo','dialog','document','figure','form','grid','gridcell','group','heading','img','link','list','listbox','listitem','main','menu','menubar','menuitem','menuitemcheckbox','menuitemradio','navigation','option','progressbar','radio','radiogroup','region','row','rowgroup','rowheader','search','searchbox','separator','slider','spinbutton','status','switch','tab','table','tablist','tabpanel','textbox','toolbar','tooltip','tree','treegrid','treeitem'] as const;
export type AriaRole=typeof ARIA_ROLES[number];
export interface BrowserTarget{role?:AriaRole;name?:string;label?:string;placeholder?:string;text?:string;testId?:string;selector?:string;}
export interface BrowserDialogExpectation{action:'accept'|'dismiss';messageIncludes?:string;}
export interface BrowserScenarioStep{action:BrowserScenarioAction;target?:BrowserTarget;value?:string|number|boolean;text?:string;count?:number;dialog?:BrowserDialogExpectation;timeoutMs?:number;}
export interface BrowserScenario{name:string;description?:string;route:string;resetStorage?:boolean;steps:BrowserScenarioStep[];}
const browserRoleLabel=(role?:AriaRole)=>role==='button'?'botão':role==='textbox'?'campo':role==='heading'?'título':role==='link'?'link':role;
const quoted=(value:unknown)=>`"${String(value??'')}"`;
export function describeBrowserStep(step:BrowserScenarioStep):string{const action=step.action;if(action==='reload')return 'reload';if(action==='goto')return `goto · ${String(step.value??'')}`;const target=step.target;let targetText='';if(target?.role&&target.name)targetText=`${browserRoleLabel(target.role)} ${quoted(target.name)}`;else if(target?.label)targetText=`campo ${quoted(target.label)}`;else if(target?.placeholder)targetText=`placeholder ${quoted(target.placeholder)}`;else if(target?.testId)targetText=`testId ${quoted(target.testId)}`;else if(target?.text)targetText=`texto ${quoted(target.text)}`;else if(target?.role)targetText=String(browserRoleLabel(target.role));else if(target?.selector)targetText=`alvo ${quoted(target.selector)}`;if(action==='fill')return `fill${targetText?` · ${targetText}`:''}`;if(action==='expectCount')return `expectCount${targetText?` · ${targetText}`:''}${typeof step.count==='number'?` · contagem esperada ${step.count}`:''}`;if(action==='expectText')return `expectText${targetText?` · ${targetText}`:''}${step.text!==undefined?` · texto ${quoted(step.text)}`:''}`;if(action==='expectValue')return `expectValue${targetText?` · ${targetText}`:''}${step.value!==undefined?` · valor esperado ${quoted(step.value)}`:''}`;return `${action}${targetText?` · ${targetText}`:''}`;}
export interface Workspace{id:string;name:string;type:WorkspaceType;location:string;branch?:string;status:WorkspaceStatus;taskBudgetUsd:number;monthlyBudgetUsd:number;createdAt:string;updatedAt:string;}
export interface AgentConfig{role:AgentRole;provider:string;model:string;timeoutSeconds:number;maxRetries:number;maxIterations:number;budgetUsd:number;tokenBudget:number;fallbackProviders:string[];enabled:boolean;}
export interface SecurityPolicy{denyGitPush:boolean;denyDeploy:boolean;denyDestructiveCommands:boolean;denySecrets:boolean;timeoutMs:number;maxIterations:number;requireHumanApproval:boolean;}
export interface HumanApprovalGates{beforeImplementation:boolean;beforeCommit:boolean;beforeMerge:boolean;beforeDeploy:boolean;beforeDatabaseChange:boolean;}
export interface Task{id:string;workspaceId:string;title:string;description:string;pipeline:AgentRole[];status:TaskStatus;currentStage?:AgentRole;lastSuccessfulStage?:AgentRole;resumable:boolean;taskBudgetUsd:number;tokenBudget:number;configSnapshot:string;createdAt:string;updatedAt:string;fixCycle?:number;maxFixCycles?:number;autoFixEnabled?:boolean;}
export interface ProviderCapabilities{streaming:boolean;cancel:boolean;usageReporting:boolean;modelSelection:boolean;toolUse:boolean;filesystemAccess:boolean;sessionResume:boolean;structuredOutput:boolean;}
export interface ModelCatalog{providerId:string;modelId:string;displayName:string;capabilities:ProviderCapabilities;contextWindow:number;inputCostPerMillion:number;outputCostPerMillion:number;enabled:boolean;metadata:Record<string,unknown>;}
export type AuthenticationStatus='authenticated'|'unauthenticated'|'unknown';export type BillingMode='api_key'|'cli_managed'|'unknown';export interface ProviderHealth{providerId:string;available:boolean;authenticated:boolean;authenticationStatus:AuthenticationStatus;authMode?:'api_key'|'account_session_or_cli_managed'|'unknown';billingMode?:BillingMode;version?:string;resolvedExecutable?:string;supportedExecFlags?:string[];unsupportedConfiguredFlags?:string[];lastCheckAt?:string;latencyMs?:number;error?:string;}
export interface PromptTemplate{id:string;name:string;version:number;template:string;description?:string;createdAt:string;active:boolean;}
export interface RetentionConfig{eventsDays:number;logsDays:number;artifactsDays:number;rawProviderResponsesDays:number;}
export interface ContextManifest{role:AgentRole;includedSections:string[];excludedSections:string[];filesIncluded:string[];filesOmitted:string[];charCount:number;truncated:boolean;omittedChars?:number;}
export interface ReviewScope{taskId:string;filesAdded:string[];filesModified:string[];filesDeleted:string[];actualFilesChanged:string[];preExistingFiles:string[];relevantDiff:string;}
export interface ReviewBundle{location:string;scope:ReviewScope;filesIncluded:string[];filesOmitted:string[];bundleSizeChars:number;bundleSizeBytes:number;manifestPath:string;reviewRequestPath:string;cleanup?:()=>void;}
export interface StageContext{prompt:string;manifest:ContextManifest;contextChars:number;contextSections:string[];contextTruncated:boolean;contextFilesIncluded:string[];contextFilesOmitted:string[];reviewBundle?:ReviewBundle;projectContext?:{text:string;hash:string;chars:number;version:number;status:string;sourceCommitSha?:string|null;truncated:boolean};}
export interface ExecutionContext{task:Task;workspaceContext:{id:string;type:WorkspaceType;location:string;branch?:string};projectRules:string[];stage:AgentRole;previousArtifacts:Artifact[];constraints:{timeoutSeconds:number;tokenBudget:number;budgetUsd:number};expectedOutputSchema?:Record<string,unknown>;stageContext?:StageContext;reviewBundle?:ReviewBundle;projectContext?:unknown;}
export interface ProgressEvent{message:string;percent?:number;timestamp:string;}
export interface StructuredExecutionOutput{stdout:string;stderr:string;progressEvents:ProgressEvent[];structuredResult?:Record<string,unknown>;rawProviderResponse?:unknown;}
export interface ProviderExecutionResult extends StructuredExecutionOutput{output:string;tokenUsage:number;inputTokens?:number;cachedInputTokens?:number;outputTokens?:number;reasoningTokens?:number;estimatedCost?:number;providerSessionId?:string;conversationId?:string;resumeToken?:string;}
export interface Execution{id:string;taskId:string;role:AgentRole;provider:string;model:string;status:ExecutionStatus;startedAt?:string;finishedAt?:string;duration?:number;tokenUsage?:number;inputTokens?:number;cachedInputTokens?:number;outputTokens?:number;reasoningTokens?:number;estimatedCost?:number;logs:string;error?:string;lastHeartbeatAt?:string;progressMessage?:string;progressPercent?:number;providerSessionId?:string;conversationId?:string;resumeToken?:string;parentExecutionId?:string;stdout?:string;stderr?:string;progressEvents?:ProgressEvent[];structuredResult?:Record<string,unknown>;rawProviderResponse?:unknown;promptTemplateId?:string;promptTemplateVersion?:number;renderedPromptHash?:string;contextChars?:number;contextSections?:string[];contextTruncated?:boolean;contextFilesIncluded?:string[];contextFilesOmitted?:string[];reviewBundleCreated?:boolean;reviewBundlePath?:string;reviewBundleFiles?:string[];reviewBundleBytes?:number;}
export interface Artifact{id:string;taskId:string;executionId?:string;type:ArtifactType;name:string;content:string;createdAt:string;}
export interface AuditEntry{id:string;actor:string;action:string;taskId?:string;executionId?:string;provider?:string;model?:string;timestamp:string;metadata:string;}
export interface DomainEvent{id:string;type:string;taskId?:string;executionId?:string;payload:string;createdAt:string;}
export interface ProviderAdapter{id:string;name:string;capabilities:ProviderCapabilities;checkAvailability():Promise<boolean>;getModels():Promise<string[]>;execute(input:ExecutionContext&{signal?:AbortSignal;onProgress?:(message:string,percent?:number)=>void;onHeartbeat?:()=>void;resumeToken?:string}):Promise<ProviderExecutionResult>;cancel(executionId:string):Promise<void>;getUsage():Promise<{tokenUsage:number;estimatedCost:number}>;}
export const DEFAULT_PIPELINE:AgentRole[]=['planner','developer','tester','reviewer'];
export const DEFAULT_POLICY:SecurityPolicy={denyGitPush:true,denyDeploy:true,denyDestructiveCommands:true,denySecrets:true,timeoutMs:120000,maxIterations:3,requireHumanApproval:false};
export const DEFAULT_GATES:HumanApprovalGates={beforeImplementation:false,beforeCommit:false,beforeMerge:false,beforeDeploy:true,beforeDatabaseChange:true};
export const DEFAULT_RETENTION:RetentionConfig={eventsDays:30,logsDays:30,artifactsDays:90,rawProviderResponsesDays:14};
export const TASK_STATUSES:TaskStatus[]=['pending','analyzing','planning','implementing','testing','reviewing','needs_fix','needs_manual_review','approved','human_review_required','cancelled','failed','stalled'];

export * from './sse.js';
export * from './provider-registry.js';
export * from './acceptance.js';
