import type {AgentRole,ProviderCapabilities} from './index.js';

export interface ProviderRegistryEntry {id:string;name:string;type:'cli'|'local'|'internal';roles:AgentRole[];authMode:'account_session_or_cli_managed'|'not_applicable';billingMode:'cli_managed'|'local'|'no_external_cost';capabilities:ProviderCapabilities;models:{providerId:string;modelId:string;displayName:string;enabled:boolean;capabilities:ProviderCapabilities;contextWindow:number|null;inputCostPerMillion:number|null;outputCostPerMillion:number|null;metadata:Record<string,unknown>}[];}
const cliCapabilities:ProviderCapabilities={streaming:true,cancel:true,usageReporting:true,modelSelection:true,toolUse:true,filesystemAccess:true,sessionResume:true,structuredOutput:true};
const localCapabilities:ProviderCapabilities={streaming:true,cancel:true,usageReporting:false,modelSelection:true,toolUse:false,filesystemAccess:true,sessionResume:false,structuredOutput:true};
const internalCapabilities:ProviderCapabilities={streaming:true,cancel:true,usageReporting:true,modelSelection:true,toolUse:false,filesystemAccess:false,sessionResume:true,structuredOutput:true};
export const PROVIDER_REGISTRY:ProviderRegistryEntry[]=[
  {id:'claude-code',name:'Claude Code',type:'cli',roles:['planner','developer','reviewer'],authMode:'account_session_or_cli_managed',billingMode:'cli_managed',capabilities:cliCapabilities,models:['sonnet','haiku'].map(modelId=>({providerId:'claude-code',modelId,displayName:modelId,enabled:true,capabilities:cliCapabilities,contextWindow:null,inputCostPerMillion:null,outputCostPerMillion:null,metadata:{source:'configured-supported-alias'}}))},
  {id:'codex-cli',name:'Codex CLI',type:'cli',roles:['planner','developer','reviewer'],authMode:'account_session_or_cli_managed',billingMode:'cli_managed',capabilities:cliCapabilities,models:[{providerId:'codex-cli',modelId:'gpt-5.6-luna',displayName:'gpt-5.6-luna',enabled:true,capabilities:cliCapabilities,contextWindow:null,inputCostPerMillion:null,outputCostPerMillion:null,metadata:{source:'configured-model'}}]},
  {id:'command-tester',name:'Command Tester',type:'local',roles:['tester'],authMode:'not_applicable',billingMode:'local',capabilities:localCapabilities,models:[{providerId:'command-tester',modelId:'local-command-runner',displayName:'local-command-runner',enabled:true,capabilities:localCapabilities,contextWindow:null,inputCostPerMillion:null,outputCostPerMillion:null,metadata:{source:'local-runtime'}}]},
  {id:'mock',name:'Mock',type:'internal',roles:['planner','developer','tester','reviewer'],authMode:'not_applicable',billingMode:'no_external_cost',capabilities:internalCapabilities,models:['mock-fast','mock-reasoning'].map(modelId=>({providerId:'mock',modelId,displayName:modelId,enabled:true,capabilities:internalCapabilities,contextWindow:null,inputCostPerMillion:0,outputCostPerMillion:0,metadata:{source:'internal'}}))}
];
export const DEFAULT_PROVIDER_CONFIG:Partial<Record<AgentRole,{provider:string;model:string}>>={planner:{provider:'mock',model:'mock-fast'},developer:{provider:'claude-code',model:'sonnet'},tester:{provider:'command-tester',model:'local-command-runner'},reviewer:{provider:'codex-cli',model:'gpt-5.6-luna'}};
export function providerForRole(providerId:string,role:AgentRole){return PROVIDER_REGISTRY.find(provider=>provider.id===providerId&&provider.roles.includes(role));}
export function modelForProvider(providerId:string,modelId:string){return PROVIDER_REGISTRY.find(provider=>provider.id===providerId)?.models.find(model=>model.modelId===modelId&&model.enabled);}
