import {strict as assert} from 'node:assert';
import {EventEmitter} from 'node:events';
import {test} from 'node:test';
import {ClaudeCodeAdapter,parseClaudeCapabilities,resolveWindowsCmdTarget,validateClaudeHelpOutput,validateClaudeVersionOutput} from '@orchestrator/adapters';

const realHelp='Claude Code - starts an interactive session by default, use -p/--print for non-interactive output\n  -p, --print                           Print response and exit (useful for pipes).\n--model <model>\n--allowedTools, --allowed-tools <tools...>\n--disallowedTools, --disallowed-tools <tools...>\n--output-format <format>\n--permission-mode <mode>\n--permission-prompts <target>';
function fakeSpawn(version='2.1.287 (Claude Code)',help=realHelp,helpIn='stdout') {return (_command:string,args:string[],_options:any)=>{const child:any=new EventEmitter();child.stdout=new EventEmitter();child.stderr=new EventEmitter();child.stdin={end(){const output=args.includes('--version')?version:help;if(args.includes('--help')&&helpIn==='stderr')child.stderr.emit('data',Buffer.from(output));else child.stdout.emit('data',Buffer.from(output));child.emit('close',0);}};child.kill=()=>child.emit('close',null);return child;};}
test('Claude capability health uses a Windows .cmd fake and validates version/help',async()=>{const adapter=new ClaudeCodeAdapter({executable:'C:\\Users\\aghiggi\\AppData\\Roaming\\npm\\claude.cmd',platform:'win32',model:'sonnet',spawn:fakeSpawn()});assert.equal(await adapter.checkAvailability(),true);const health:any=await adapter.getHealth();assert.equal(health.available,true);assert.ok(health.supportedCliFlags.includes('-p'));assert.ok(health.supportedCliFlags.includes('--print'));assert.ok(health.supportedCliFlags.includes('--model'));assert.ok(health.supportedCliFlags.includes('--allowedTools'));assert.ok(health.supportedCliFlags.includes('--disallowedTools'));assert.ok(health.supportedCliFlags.includes('--output-format'));assert.ok(health.supportedCliFlags.includes('--permission-mode'));});
test('Claude capability parser accepts stdout, stderr and divided help',()=>{const stdout=parseClaudeCapabilities(realHelp);const stderr=parseClaudeCapabilities(realHelp);const divided=parseClaudeCapabilities(realHelp.slice(0,90)+'\n'+realHelp.slice(90));for(const parsed of [stdout,stderr,divided]){assert.ok(parsed.supportedFlags.includes('-p'));assert.ok(parsed.supportedFlags.includes('--print'));assert.ok(parsed.supportedFlags.includes('--model'));}assert.equal(validateClaudeVersionOutput('2.1.287 (Claude Code)'),true);assert.equal(validateClaudeVersionOutput('The command claude --version needs your approval...'),false);assert.equal(validateClaudeHelpOutput(realHelp),true);});
test('Claude health rejects a model response pretending to be --version',async()=>{const adapter=new ClaudeCodeAdapter({executable:'claude.cmd',platform:'win32',spawn:fakeSpawn('The command `claude --version` needs your approval before it runs...')});assert.equal(await adapter.checkAvailability(),false);const health:any=await adapter.getHealth();assert.equal(health.error,'Unexpected Claude --version output');});
test('Windows npm wrapper resolves its real Claude executable without cmd.exe',()=>{const wrapper='C:\\Users\\test\\AppData\\Roaming\\npm\\claude.cmd';const target=resolveWindowsCmdTarget(wrapper,()=>true,()=>`"%dp0%\\node_modules\\@anthropic-ai\\claude-code\\bin\\claude.exe"   %*`);assert.equal(target,'C:\\Users\\test\\AppData\\Roaming\\npm\\node_modules\\@anthropic-ai\\claude-code\\bin\\claude.exe');});
