import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,existsSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {EventEmitter} from 'node:events';
import {CodexCliAdapter} from '@orchestrator/adapters';
import {buildStageContext} from '@orchestrator/core';
import type {ReviewScope,Task} from '@orchestrator/shared';
import {createReviewBundle,cleanupReviewBundle} from './review-bundle.js';

const task:Task={id:'review-scope-task',workspaceId:'workspace',title:'Create scoped file',description:'Create context-optimization-test.txt',pipeline:['planner','developer','tester','reviewer'],status:'reviewing',resumable:true,taskBudgetUsd:0,tokenBudget:0,configSnapshot:'{}',createdAt:'',updatedAt:''};
const scope:ReviewScope={taskId:task.id,filesAdded:['context-optimization-test.txt'],filesModified:[],filesDeleted:[],actualFilesChanged:['context-optimization-test.txt'],preExistingFiles:Array.from({length:17},(_,i)=>`old-${i}.txt`),relevantDiff:'diff --git a/context-optimization-test.txt b/context-optimization-test.txt\n+ok'};

test('review scope excludes pre-existing files from reviewer rules',()=>{const context=buildStageContext({task,role:'reviewer',workspaceContext:{id:'workspace',type:'local',location:'C:\\workspace'},reviewScope:scope,changedFiles:scope.actualFilesChanged,diff:scope.relevantDiff,acceptanceCriteria:['File exists'],maxChars:10000});assert.match(context.prompt,/17 files existed before this task/);assert.match(context.prompt,/Use actualFilesChanged as the authoritative task scope/);assert.match(context.prompt,/context-optimization-test\.txt/);assert.doesNotMatch(context.prompt,/old-0\.txt/);});

test('review bundle contains only selected files and cleans up',()=>{const workspace=mkdtempSync(join(tmpdir(),'orchestrator-review-fixture-'));const selected=join(workspace,'context-optimization-test.txt');writeFileSync(selected,'task file','utf8');writeFileSync(join(workspace,'unrelated.txt'),'must not be copied','utf8');const bundle=createReviewBundle({task,workspaceLocation:workspace,executionId:'execution-1',scope,acceptanceCriteria:['File exists'],filePaths:['context-optimization-test.txt']});assert.equal(bundle.filesIncluded.length,1);assert.deepEqual(bundle.filesOmitted,[]);assert.equal(existsSync(join(bundle.location,'files','context-optimization-test.txt')),true);assert.equal(existsSync(join(bundle.location,'files','unrelated.txt')),false);assert.ok(bundle.bundleSizeBytes>0);assert.equal(existsSync(bundle.location),true);cleanupReviewBundle(bundle);assert.equal(existsSync(bundle.location),false);});

test('Codex reviewer uses review bundle cwd and still parses APPROVED',async()=>{const workspace=mkdtempSync(join(tmpdir(),'orchestrator-review-cwd-'));writeFileSync(join(workspace,'context-optimization-test.txt'),'task file','utf8');const bundle=createReviewBundle({task,workspaceLocation:workspace,executionId:'execution-2',scope,acceptanceCriteria:['File exists'],filePaths:scope.actualFilesChanged});let observedCwd='';const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',spawn:(_command,args,options)=>{observedCwd=String(options.cwd);const child:any=new EventEmitter();child.stdout=new EventEmitter();child.stderr=new EventEmitter();child.stdin={end(){const output=args.includes('--help')?'Usage: codex exec\n--json\n--sandbox\n--model':args.includes('--version')?'codex-cli 0.160.0':JSON.stringify({status:'APPROVED',summary:'ok',issues:[]});child.stdout.emit('data',Buffer.from(output));child.emit('close',0);}};child.kill=()=>{};return child;}});const result=await adapter.execute({task,workspaceContext:{id:'workspace',type:'local',location:workspace},projectRules:[],stage:'reviewer',previousArtifacts:[],constraints:{timeoutSeconds:1,tokenBudget:100,budgetUsd:1},stageContext:{prompt:'Review bundle',manifest:{role:'reviewer',includedSections:[],excludedSections:[],filesIncluded:scope.actualFilesChanged,filesOmitted:[],charCount:14,truncated:false},contextChars:14,contextSections:[],contextTruncated:false,contextFilesIncluded:scope.actualFilesChanged,contextFilesOmitted:[],reviewBundle:bundle}});assert.equal(result.structuredResult?.status,'APPROVED');assert.equal(observedCwd,bundle.location);assert.equal(existsSync(bundle.location),false);});
