import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,existsSync,readFileSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {EventEmitter} from 'node:events';
import {CodexCliAdapter} from '@orchestrator/adapters';
import {buildStageContext,PipelineRunner} from '@orchestrator/core';
import type {ReviewScope,Task} from '@orchestrator/shared';
import {createReviewBundle,cleanupReviewBundle} from './review-bundle.js';

const task:Task={id:'review-scope-task',workspaceId:'workspace',title:'Create scoped file',description:'Create context-optimization-test.txt',pipeline:['planner','developer','tester','reviewer'],status:'reviewing',resumable:true,taskBudgetUsd:0,tokenBudget:0,configSnapshot:'{}',createdAt:'',updatedAt:''};
test('ReviewBundle keeps acceptance criteria as individual entries',()=>{const workspace=mkdtempSync(join(tmpdir(),'orchestrator-review-criteria-'));const bundle=createReviewBundle({task,workspaceLocation:workspace,executionId:'criteria',scope:{taskId:task.id,filesAdded:[],filesModified:[],filesDeleted:[],actualFilesChanged:[],preExistingFiles:[],relevantDiff:''},acceptanceCriteria:['[AC1] Criação aprovada.','[AC2] Exclusão aprovada.'],filePaths:[]});const request=readFileSync(bundle.reviewRequestPath,'utf8');assert.match(request,/- \[AC1\] Criação aprovada\./);assert.match(request,/- \[AC2\] Exclusão aprovada\./);cleanupReviewBundle(bundle);});
const scope:ReviewScope={taskId:task.id,filesAdded:['context-optimization-test.txt'],filesModified:[],filesDeleted:[],actualFilesChanged:['context-optimization-test.txt'],preExistingFiles:Array.from({length:17},(_,i)=>`old-${i}.txt`),relevantDiff:'diff --git a/context-optimization-test.txt b/context-optimization-test.txt\n+ok'};
const context=(bundle?:any):any=>({task,workspaceContext:{id:'workspace',type:'local',location:bundle?.location||mkdtempSync(join(tmpdir(),'orchestrator-review-workspace-'))},projectRules:[],stage:'reviewer',previousArtifacts:[],constraints:{timeoutSeconds:1,tokenBudget:100,budgetUsd:1},reviewBundle:bundle,stageContext:{prompt:'Review bundle',manifest:{role:'reviewer',includedSections:[],excludedSections:[],filesIncluded:scope.actualFilesChanged,filesOmitted:[],charCount:14,truncated:false},contextChars:14,contextSections:[],contextTruncated:false,contextFilesIncluded:scope.actualFilesChanged,contextFilesOmitted:[],reviewBundle:bundle}});
function fakeProcess(output:string,code=0){const child:any=new EventEmitter();child.stdout=new EventEmitter();child.stderr=new EventEmitter();child.stdin={end(){if(output)child.stdout.emit('data',Buffer.from(output));child.emit('close',code);}};child.kill=()=>{};return child;}
function codexSpawn(options:{help?:string;review?:string;code?:number;onArgs?:(args:string[])=>void}={}){return (_command:string,args:string[])=>{options.onArgs?.(args);const output=args.includes('--version')?'codex-cli 0.160.0':args.includes('--help')?options.help||'Usage: codex exec\n--json\n--sandbox\n--model\n--skip-git-repo-check':options.review||JSON.stringify({status:'APPROVED',summary:'ok',issues:[]});return fakeProcess(output,options.code||0);};}

test('review scope excludes pre-existing files from reviewer rules',()=>{const built=buildStageContext({task,role:'reviewer',workspaceContext:{id:'workspace',type:'local',location:'C:\\workspace'},reviewScope:scope,changedFiles:scope.actualFilesChanged,diff:scope.relevantDiff,acceptanceCriteria:['File exists'],maxChars:10000});assert.match(built.prompt,/17 files existed before this task/);assert.match(built.prompt,/Use actualFilesChanged as the authoritative task scope/);assert.match(built.prompt,/context-optimization-test\.txt/);assert.doesNotMatch(built.prompt,/old-0\.txt/);});
test('review bundle contains only selected files and cleanup is explicit',()=>{const workspace=mkdtempSync(join(tmpdir(),'orchestrator-review-fixture-'));writeFileSync(join(workspace,'context-optimization-test.txt'),'task file','utf8');writeFileSync(join(workspace,'unrelated.txt'),'must not be copied','utf8');const bundle=createReviewBundle({task,workspaceLocation:workspace,executionId:'execution-1',scope,acceptanceCriteria:['File exists'],filePaths:['context-optimization-test.txt']});assert.deepEqual(bundle.filesIncluded,['context-optimization-test.txt']);assert.equal(existsSync(join(bundle.location,'files','unrelated.txt')),false);assert.ok(bundle.bundleSizeBytes>0);const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',spawn:codexSpawn()});assert.equal(existsSync(bundle.location),true);cleanupReviewBundle(bundle);assert.equal(existsSync(bundle.location),false);void adapter;});
test('ReviewBundle uses skip-git-repo-check and survives one retry',async()=>{const workspace=mkdtempSync(join(tmpdir(),'orchestrator-review-cwd with spaces-'));writeFileSync(join(workspace,'context-optimization-test.txt'),'task file','utf8');const bundle=createReviewBundle({task,workspaceLocation:workspace,executionId:'execution-2',scope,acceptanceCriteria:['File exists'],filePaths:scope.actualFilesChanged});let attempts=0;let observedArgs:string[][]=[];const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',spawn:codexSpawn({review:JSON.stringify({status:'APPROVED',summary:'ok',issues:[]}),onArgs:args=>{if(args.includes('--model')){observedArgs.push(args);attempts++;}}})});const runner=new PipelineRunner({execute:async input=>{if(attempts===0){await adapter.execute(input);throw Object.assign(new Error('transient'),{kind:'provider_error'});}return adapter.execute(input);},checkAvailability:()=>Promise.resolve(true),getModels:()=>Promise.resolve([]),getUsage:()=>Promise.resolve({tokenUsage:0,estimatedCost:0}),cancel:()=>Promise.resolve(),id:'test',name:'test',capabilities:adapter.capabilities},{onStageStart(){},onStageComplete(){},onProgress(){},onHeartbeat(){},onFailure(){}});const base=context(bundle);await runner.run(base,['reviewer'],0,undefined,undefined,()=>base);assert.equal(observedArgs.length,2);assert.ok(observedArgs[0].includes('--skip-git-repo-check'));assert.equal(observedArgs[0].join('|'),observedArgs[1].join('|'));assert.equal(existsSync(bundle.location),false);});
test('normal workspace does not receive skip-git-repo-check',async()=>{const workspace=mkdtempSync(join(tmpdir(),'orchestrator-normal-git-'));let observed:string[]=[];const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',spawn:codexSpawn({onArgs:args=>{if(args.includes('--model'))observed=args;}})});await adapter.execute({...context(),workspaceContext:{id:'workspace',type:'git',location:workspace}});assert.equal(observed.includes('--skip-git-repo-check'),false);});
test('unsupported bundle flag fails before provider spawn',async()=>{const workspace=mkdtempSync(join(tmpdir(),'orchestrator-no-skip-'));const bundle=createReviewBundle({task,workspaceLocation:workspace,executionId:'execution-3',scope,filePaths:[]});let spawned=false;const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',spawn:(_command,args)=>{spawned=true;return fakeProcess(args.includes('--help')?'--json\n--sandbox\n--model':JSON.stringify({status:'APPROVED',summary:'ok',issues:[]}));}});await assert.rejects(adapter.execute(context(bundle)),error=>{assert.equal((error as any).kind,'configuration_error');assert.match(String(error),/skip-git-repo-check/);return true;});assert.equal(spawned,true);cleanupReviewBundle(bundle);});
test('missing review bundle cwd is a clear configuration error',async()=>{const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',spawn:codexSpawn()});const missing={...context(),stageContext:{...context().stageContext,reviewBundle:{location:join(tmpdir(),'does-not-exist-review-bundle')}}};await assert.rejects(adapter.execute(missing),error=>{assert.equal((error as any).kind,'configuration_error');assert.match(String(error),/Review bundle directory does not exist/);return true;});});
test('terminal reviewer failure cleans bundle only after retries are exhausted',async()=>{const workspace=mkdtempSync(join(tmpdir(),'orchestrator-terminal-failure-'));const bundle=createReviewBundle({task,workspaceLocation:workspace,executionId:'execution-4',scope,filePaths:[]});let calls=0;const runner=new PipelineRunner({id:'failure',name:'failure',capabilities:{streaming:false,cancel:true,usageReporting:false,modelSelection:false,toolUse:false,filesystemAccess:false,sessionResume:false,structuredOutput:true},checkAvailability:()=>Promise.resolve(true),getModels:()=>Promise.resolve([]),getUsage:()=>Promise.resolve({tokenUsage:0,estimatedCost:0}),cancel:()=>Promise.resolve(),execute:async()=>{calls++;throw Object.assign(new Error('transient'),{kind:'provider_error'});}}, {onStageStart(){},onStageComplete(){},onProgress(){},onHeartbeat(){},onFailure(){}});await assert.rejects(runner.run(context(bundle),['reviewer'],0,undefined,{maxRetries:1,retryOn:['provider_error'],backoffMs:1},()=>context(bundle)));assert.equal(calls,2);assert.equal(existsSync(bundle.location),false);});
test('cancelled reviewer cleans bundle without another attempt',async()=>{const workspace=mkdtempSync(join(tmpdir(),'orchestrator-cancel-'));const bundle=createReviewBundle({task,workspaceLocation:workspace,executionId:'execution-5',scope,filePaths:[]});const controller=new AbortController();const runner=new PipelineRunner({id:'cancel',name:'cancel',capabilities:{streaming:false,cancel:true,usageReporting:false,modelSelection:false,toolUse:false,filesystemAccess:false,sessionResume:false,structuredOutput:true},checkAvailability:()=>Promise.resolve(true),getModels:()=>Promise.resolve([]),getUsage:()=>Promise.resolve({tokenUsage:0,estimatedCost:0}),cancel:()=>Promise.resolve(),execute:async()=>{controller.abort();throw Object.assign(new Error('cancelled'),{kind:'cancelled'});}}, {onStageStart(){},onStageComplete(){},onProgress(){},onHeartbeat(){},onFailure(){}});await assert.rejects(runner.run(context(bundle),['reviewer'],0,controller.signal,undefined,()=>context(bundle)),/cancelled/);assert.equal(existsSync(bundle.location),false);});
