import test from 'node:test';import assert from 'node:assert/strict';
import {MockAdapter} from '@orchestrator/adapters';
import {BudgetExceededError,BudgetGuard,ExecutionWatchdog,WorkspaceLockManager,resumeIndex,PipelineRunner} from '@orchestrator/core';

test('provider capabilities are explicit and mock reports usage',async()=>{const a=new MockAdapter();assert.equal(await a.checkAvailability(),true);assert.equal(a.capabilities.cancel,true);assert.equal(a.capabilities.filesystemAccess,false);const result=await a.execute({stage:'reviewer'});assert.match(result.output,/APPROVED/);assert.equal(result.stdout,result.output);assert.equal(result.stderr,'');assert.equal(result.progressEvents.length,3);assert.equal(result.structuredResult?.status,'ok');assert.equal(result.providerSessionId,'mock-session');assert.equal(result.conversationId,'mock-conversation');assert.equal(result.resumeToken,'mock-resume-token');assert.ok(result.tokenUsage>0);});
test('budget guard blocks exceeded spend',()=>{const guard=new BudgetGuard(1,100);assert.throws(()=>guard.assertCanStart(1.1,0),BudgetExceededError);assert.throws(()=>guard.assertCanStart(0,101),BudgetExceededError);});
test('workspace lock prevents concurrent ownership',()=>{const locks=new WorkspaceLockManager();locks.acquire('workspace:w','a');assert.throws(()=>locks.acquire('workspace:w','b'),/Lock busy/);locks.release('workspace:w','a');locks.acquire('workspace:w','b');});
test('resume starts after last successful stage',()=>{assert.equal(resumeIndex(['planner','developer','tester','reviewer'],'developer'),2);assert.equal(resumeIndex(['planner','developer'],undefined),0);});
test('watchdog marks stalled execution after missing heartbeat',async()=>{await new Promise<void>((resolve,reject)=>{const watchdog=new ExecutionWatchdog(250,()=>{watchdog.stop();resolve();});watchdog.start();setTimeout(()=>{watchdog.stop();reject(new Error('watchdog did not fire'));},700);});});
test('pipeline cancellation propagates',async()=>{const controller=new AbortController();controller.abort();const runner=new PipelineRunner(new MockAdapter(),{onStageStart(){},onStageComplete(){},onProgress(){},onHeartbeat(){},onFailure(){}});await assert.rejects(runner.run({task:{} as any,workspaceContext:{} as any,projectRules:[],previousArtifacts:[],constraints:{timeoutSeconds:1,tokenBudget:0,budgetUsd:0}},['planner'],0,controller.signal),/cancelled/i);});

test('pipeline retries provider errors according to policy',async()=>{let calls=0;const adapter:any={execute:async()=>{calls++;if(calls===1)throw Object.assign(new Error('temporary'),{kind:'provider_error'});return{output:'ok',tokenUsage:1,estimatedCost:0};}};const runner=new PipelineRunner(adapter,{onStageStart(){},onStageComplete(){},onProgress(){},onHeartbeat(){},onFailure(){}});const output=await runner.run({task:{} as any,workspaceContext:{} as any,projectRules:[],previousArtifacts:[],constraints:{timeoutSeconds:1,tokenBudget:0,budgetUsd:0}},['planner']);assert.equal(output[0],'ok');assert.equal(calls,2);});

import {EventEmitter} from 'node:events';
import {CodexCliAdapter,resolveExecutable} from '@orchestrator/adapters';

const codexContext:any={task:{id:'codex-test',title:'Review',description:'Review safely',pipeline:['reviewer'],status:'reviewing',resumable:true,workspaceId:'w',taskBudgetUsd:1,tokenBudget:1000,configSnapshot:'{}',createdAt:'',updatedAt:''},workspaceContext:{id:'w',type:'local',location:'/tmp',branch:'main'},projectRules:[],stage:'reviewer',previousArtifacts:[],constraints:{timeoutSeconds:1,tokenBudget:1000,budgetUsd:1}};
function fakeSpawn(config:{stdout?:string;stderr?:string;code?:number|null;delay?:number;never?:boolean}={}){return (_command:string,args:string[])=>{const child:any=new EventEmitter();child.stdout=new EventEmitter();child.stderr=new EventEmitter();child.stdin={end(){if(config.never)return;setTimeout(()=>{if(config.stdout)child.stdout.emit('data',Buffer.from(config.stdout));if(config.stderr)child.stderr.emit('data',Buffer.from(config.stderr));child.emit('close',config.code??0);},config.delay||0);}};child.kill=()=>{if(!child.closed){child.closed=true;child.emit('close',null);}};child.args=args;return child;};}
function review(status:'APPROVED'|'NEEDS_FIX'='APPROVED'){return JSON.stringify({status,summary:'review summary',issues:status==='APPROVED'?[]:[{severity:'high',file:'src/app.ts',description:'Fix this issue'}]});}

test('codex reports CLI missing separately from authentication',async()=>{const adapter=new CodexCliAdapter({executable:'codex-not-installed-for-test'});assert.equal(await adapter.checkAvailability(),false);const health=await adapter.getHealth();assert.equal(health.available,false);assert.equal(health.authenticated,false);});
test('codex health captures version and authentication error',async()=>{const adapter=new CodexCliAdapter({executable:'codex',spawn:fakeSpawn({stdout:'codex 1.2.3',stderr:'authentication required',code:0})});assert.equal(await adapter.checkAvailability(),true);const health=await adapter.getHealth();assert.equal(health.version,'1.2.3');assert.equal(health.authenticated,false);assert.equal(health.authenticationStatus,'unknown');});
test('codex rejects non-zero exit and captures stderr',async()=>{const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',spawn:fakeSpawn({stderr:'cli failure',code:2})});await assert.rejects(adapter.execute(codexContext),error=>{assert.equal((error as any).kind,'provider_error');assert.match(String(error),/cli failure/);return true;});});
test('codex validates APPROVED JSON and structured output',async()=>{let args:string[]=[];const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',spawn:(command,a)=>{args=a;return fakeSpawn({stdout:review('APPROVED')})(command,a);}});const result=await adapter.execute({...codexContext,onProgress(){},onHeartbeat(){}});assert.equal(result.structuredResult?.status,'APPROVED');assert.equal(result.stderr,'');assert.equal(result.tokenUsage,0);assert.ok(args.includes('--sandbox'));});
test('codex validates NEEDS_FIX JSON without textual approval fallback',async()=>{const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',spawn:fakeSpawn({stdout:review('NEEDS_FIX')})});const result=await adapter.execute(codexContext);assert.equal(result.structuredResult?.status,'NEEDS_FIX');assert.match(result.output,/NEEDS_FIX/);});
test('codex rejects invalid JSON even when stdout contains APPROVED text',async()=>{const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',spawn:fakeSpawn({stdout:'APPROVED but not JSON'})});await assert.rejects(adapter.execute(codexContext),error=>{assert.equal((error as any).kind,'validation_error');return true;});});
test('codex times out and terminates only its child',async()=>{const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',timeoutMs:20,spawn:fakeSpawn({never:true})});await assert.rejects(adapter.execute(codexContext),error=>{assert.equal((error as any).kind,'timeout');return true;});});
test('codex responds to AbortSignal and cancel',async()=>{const controller=new AbortController();const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',timeoutMs:1000,spawn:fakeSpawn({never:true})});const promise=adapter.execute({...codexContext,signal:controller.signal});controller.abort();await assert.rejects(promise,error=>{assert.equal((error as any).kind,'cancelled');return true;});});
test('codex blocks invalid budget before spawning',async()=>{let spawned=false;const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',spawn:(command,args)=>{spawned=true;return fakeSpawn({stdout:review()})(command,args);}});await assert.rejects(adapter.execute({...codexContext,constraints:{timeoutSeconds:1,tokenBudget:1000,budgetUsd:-1}}),error=>{assert.equal((error as any).kind,'budget_exceeded');return true;});assert.equal(spawned,false);});
test('codex exposes configured model only and never invents catalog models',async()=>{assert.deepEqual(await new CodexCliAdapter({}).getModels(),[]);assert.deepEqual(await new CodexCliAdapter({model:'configured-model'}).getModels(),['configured-model']);});


test('resolver finds codex.cmd in a Windows PATH before exe and ps1',()=>{const resolved=resolveExecutable({platform:'win32',env:{PATH:'C:\\Tools;C:\\Users\\tester\\AppData\\Roaming\\npm'},pathExists:path=>path.endsWith('\\codex.cmd')});assert.equal(resolved?.path,'C:\\Tools\\codex.cmd');assert.equal(resolved?.isWindowsWrapper,true);});
test('resolver honors explicit Windows path containing spaces',()=>{const resolved=resolveExecutable({platform:'win32',explicit:'C:\\Program Files\\Codex\\codex.cmd',pathExists:()=>true});assert.equal(resolved?.source,'configured');assert.equal(resolved?.path,'C:\\Program Files\\Codex\\codex.cmd');});
test('resolver uses codex on Linux and does not require Windows wrappers',()=>{const resolved=resolveExecutable({platform:'linux',env:{PATH:'/usr/local/bin'},pathExists:path=>path==='/usr/local/bin/codex'});assert.equal(resolved?.path,'/usr/local/bin/codex');assert.equal(resolved?.isWindowsWrapper,false);});
test('health check keeps authentication unknown after safe version check',async()=>{const adapter=new CodexCliAdapter({executable:'codex.cmd',platform:'win32',spawn:fakeSpawn({stdout:'codex-cli 0.160.0'})});assert.equal(await adapter.checkAvailability(),true);const health=await adapter.getHealth();assert.equal(health.available,true);assert.equal(health.version,'0.160.0');assert.equal(health.authenticationStatus,'unknown');assert.equal(health.resolvedExecutable,'codex.cmd');});

import {buildAgentConfigs,configForRole,createTaskConfigSnapshot,toWorkspaceContext,validateWorkspaceLocation} from './task-config.js';

test('task snapshot freezes Codex reviewer while other stages remain Mock',()=>{const snapshot=createTaskConfigSnapshot(['planner','developer','tester','reviewer'],{reviewerProvider:'codex-cli',codexModel:'gpt-5.6-luna'},{},{});assert.deepEqual(snapshot.agentConfigs.map(c=>[c.role,c.provider,c.model]),[['planner','mock','mock-fast'],['developer','mock','mock-fast'],['tester','mock','mock-fast'],['reviewer','codex-cli','gpt-5.6-luna']]);assert.match(snapshot.providerSelection,/reviewer:codex-cli\/gpt-5.6-luna/);});
test('task keeps frozen config when environment changes later',()=>{const snapshot=createTaskConfigSnapshot(['reviewer'],{reviewerProvider:'codex-cli',codexModel:'gpt-5.6-luna'},{},{});const later=buildAgentConfigs(['reviewer'],{reviewerProvider:'mock',codexModel:'other-model'});assert.equal(configForRole(snapshot,'reviewer').provider,'codex-cli');assert.equal(configForRole(snapshot,'reviewer').model,'gpt-5.6-luna');assert.equal(later[0].provider,'mock');});
test('execution context uses registered workspace location and branch',()=>{const context=toWorkspaceContext({id:'w1',name:'Mapa AI',type:'local',location:'C:\\xampp\\htdocs\\mapa-ai',branch:'main',status:'active',taskBudgetUsd:0,monthlyBudgetUsd:0,createdAt:'',updatedAt:''});assert.deepEqual(context,{id:'w1',type:'local',location:'C:\\xampp\\htdocs\\mapa-ai',branch:'main'});});
test('missing local workspace blocks execution before provider',()=>{assert.equal(validateWorkspaceLocation({type:'local',location:'/missing'},()=>false),false);assert.equal(validateWorkspaceLocation({type:'local',location:'/present'},()=>true),true);assert.equal(validateWorkspaceLocation({type:'git',location:'/remote'},()=>false),true);});
