import express, {type Express} from 'express'; import cors from 'cors'; import Database from 'better-sqlite3'; import {nanoid} from 'nanoid'; import {MockAdapter} from '@orchestrator/adapters'; import {PipelineRunner} from '@orchestrator/core'; import {DEFAULT_PIPELINE,type AgentRole,type TaskStatus} from '@orchestrator/shared';
const db=new Database(process.env.DB_PATH||'orchestrator.db'); db.pragma('journal_mode = WAL'); db.exec(`CREATE TABLE IF NOT EXISTS workspaces (id TEXT PRIMARY KEY,name TEXT NOT NULL,type TEXT NOT NULL,location TEXT NOT NULL,branch TEXT,status TEXT NOT NULL,createdAt TEXT NOT NULL,updatedAt TEXT NOT NULL); CREATE TABLE IF NOT EXISTS tasks (id TEXT PRIMARY KEY,workspaceId TEXT NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL,pipeline TEXT NOT NULL,status TEXT NOT NULL,createdAt TEXT NOT NULL,updatedAt TEXT NOT NULL); CREATE TABLE IF NOT EXISTS executions (id TEXT PRIMARY KEY,taskId TEXT NOT NULL,role TEXT NOT NULL,provider TEXT NOT NULL,model TEXT NOT NULL,status TEXT NOT NULL,startedAt TEXT,finishedAt TEXT,duration INTEGER,tokenUsage INTEGER,estimatedCost REAL,logs TEXT,error TEXT); CREATE TABLE IF NOT EXISTS events (id TEXT PRIMARY KEY,type TEXT NOT NULL,taskId TEXT,executionId TEXT,payload TEXT NOT NULL,createdAt TEXT NOT NULL); CREATE TABLE IF NOT EXISTS providers (id TEXT PRIMARY KEY,name TEXT NOT NULL,status TEXT NOT NULL); CREATE TABLE IF NOT EXISTS agent_configs (id TEXT PRIMARY KEY,role TEXT NOT NULL,provider TEXT NOT NULL,model TEXT NOT NULL);`);
const app: Express=express(); app.use(cors()); app.use(express.json()); const clients=new Set<express.Response>(); const now=()=>new Date().toISOString();
function emit(type:string,data:Record<string,unknown>,taskId?:string,executionId?:string){const event={id:nanoid(),type,taskId,executionId,payload:JSON.stringify(data),createdAt:now()}; db.prepare('INSERT INTO events VALUES (@id,@type,@taskId,@executionId,@payload,@createdAt)').run(event); for(const res of clients){res.write(`event: ${type}\ndata: ${JSON.stringify({...data,taskId,executionId})}\n\n`);} }
app.get('/health',(_,res)=>res.json({ok:true,service:'ai-orchestrator-api'})); app.get('/events',(_,res)=>{res.setHeader('Content-Type','text/event-stream');res.setHeader('Cache-Control','no-cache');res.setHeader('Connection','keep-alive');res.flushHeaders();clients.add(res);res.write(`event: connected\ndata: {}\n\n`);res.on('close',()=>clients.delete(res));});
app.get('/api/workspaces',(_,res)=>res.json(db.prepare('SELECT * FROM workspaces ORDER BY updatedAt DESC').all())); app.post('/api/workspaces',(req,res)=>{const id=nanoid();const t=now();const {name,type='local',location,branch='main'}=req.body;if(!name||!location)return res.status(400).json({error:'name e location são obrigatórios'});db.prepare('INSERT INTO workspaces VALUES (?,?,?,?,?,?,?)').run(id,name,type,location,branch,'active',t,t);res.status(201).json(db.prepare('SELECT * FROM workspaces WHERE id=?').get(id));});
app.get('/api/workspaces/:id', (req,res)=>{const workspace=db.prepare('SELECT * FROM workspaces WHERE id=?').get(req.params.id);if(!workspace)return res.sendStatus(404);const tasks=db.prepare('SELECT * FROM tasks WHERE workspaceId=? ORDER BY updatedAt DESC').all(req.params.id);res.json({...workspace,tasks});});
app.get('/api/tasks/:id',(req,res)=>{const task:any=db.prepare('SELECT * FROM tasks WHERE id=?').get(req.params.id);if(!task)return res.sendStatus(404);task.pipeline=JSON.parse(task.pipeline);task.executions=db.prepare('SELECT * FROM executions WHERE taskId=? ORDER BY startedAt').all(task.id);task.events=db.prepare('SELECT * FROM events WHERE taskId=? ORDER BY createdAt').all(task.id).map((e:any)=>({...e,payload:JSON.parse(e.payload)}));res.json(task);});
app.post('/api/workspaces/:workspaceId/tasks',(req,res)=>{const id=nanoid(),t=now();const pipeline=req.body.pipeline?.length?req.body.pipeline:DEFAULT_PIPELINE;const {title,description}=req.body;if(!title||!description)return res.status(400).json({error:'title e description são obrigatórios'});db.prepare('INSERT INTO tasks VALUES (?,?,?,?,?,?,?,?)').run(id,req.params.workspaceId,title,description,JSON.stringify(pipeline),'pending',t,t);emit('task.created',{title},id);res.status(201).json(db.prepare('SELECT * FROM tasks WHERE id=?').get(id));});
app.post('/api/tasks/:id/run',(req,res)=>{const task:any=db.prepare('SELECT * FROM tasks WHERE id=?').get(req.params.id);if(!task)return res.sendStatus(404);res.status(202).json({accepted:true,taskId:task.id});void runTask(task);});
app.post('/api/tasks/:id/cancel',(req,res)=>{const task:any=db.prepare('SELECT * FROM tasks WHERE id=?').get(req.params.id);if(!task)return res.sendStatus(404);db.prepare('UPDATE tasks SET status=?,updatedAt=? WHERE id=?').run('cancelled',now(),task.id);emit('task.cancelled',{},task.id);res.json({ok:true});});
app.get('/api/providers',(_,res)=>res.json([{id:'mock',name:'Mock Provider',status:'available',models:['mock-fast','mock-reasoning']} ]));
async function runTask(task:any){const adapter=new MockAdapter();const controller=new AbortController();const pipeline:AgentRole[]=JSON.parse(task.pipeline);db.prepare('UPDATE tasks SET status=?,updatedAt=? WHERE id=?').run('analyzing',now(),task.id);emit('task.started',{},task.id);const runner=new PipelineRunner(adapter,{onStageStart(role){const id=nanoid(),started=now();db.prepare('INSERT INTO executions (id,taskId,role,provider,model,status,startedAt,logs) VALUES (?,?,?,?,?,?,?,?)').run(id,task.id,role,'mock','mock-fast','running',started,`Iniciando ${role}`);emit('stage.started',{role},task.id,id);},onProgress(role,message){const exec:any=db.prepare('SELECT * FROM executions WHERE taskId=? AND role=? AND status=? ORDER BY startedAt DESC LIMIT 1').get(task.id,role,'running');if(exec){db.prepare('UPDATE executions SET logs=? WHERE id=?').run(`${exec.logs}\n${message}`,exec.id);emit('execution.progress',{role,message},task.id,exec.id);}},onStageComplete(role,output){const exec:any=db.prepare('SELECT * FROM executions WHERE taskId=? AND role=? AND status=? ORDER BY startedAt DESC LIMIT 1').get(task.id,role,'running');if(exec){const finished=now();const duration=Date.parse(finished)-Date.parse(exec.startedAt);db.prepare('UPDATE executions SET status=?,finishedAt=?,duration=?,tokenUsage=?,estimatedCost=?,logs=? WHERE id=?').run('completed',finished,duration,120+role.length*7,0,`${exec.logs}\n${output}`,exec.id);emit('execution.completed',{role,output},task.id,exec.id);}}});try{await runner.run(task.description,pipeline,controller.signal);db.prepare('UPDATE tasks SET status=?,updatedAt=? WHERE id=?').run('approved',now(),task.id);emit('task.completed',{status:'approved'},task.id);}catch(error){db.prepare('UPDATE tasks SET status=?,updatedAt=? WHERE id=?').run('failed',now(),task.id);emit('execution.failed',{error:String(error)},task.id);}}
const port=Number(process.env.PORT||4000);app.listen(port,'0.0.0.0',()=>console.log(`API listening on http://0.0.0.0:${port}`));
