import test from 'node:test';import assert from 'node:assert/strict';
import {MockAdapter} from '@orchestrator/adapters';
import {BudgetExceededError,BudgetGuard,ExecutionWatchdog,WorkspaceLockManager,resumeIndex,PipelineRunner} from '@orchestrator/core';

test('provider capabilities are explicit and mock reports usage',async()=>{const a=new MockAdapter();assert.equal(await a.checkAvailability(),true);assert.equal(a.capabilities.cancel,true);assert.equal(a.capabilities.filesystemAccess,false);const result=await a.execute({stage:'reviewer'});assert.match(result.output,/APPROVED/);assert.ok(result.tokenUsage>0);});
test('budget guard blocks exceeded spend',()=>{const guard=new BudgetGuard(1,100);assert.throws(()=>guard.assertCanStart(1.1,0),BudgetExceededError);assert.throws(()=>guard.assertCanStart(0,101),BudgetExceededError);});
test('workspace lock prevents concurrent ownership',()=>{const locks=new WorkspaceLockManager();locks.acquire('workspace:w','a');assert.throws(()=>locks.acquire('workspace:w','b'),/Lock busy/);locks.release('workspace:w','a');locks.acquire('workspace:w','b');});
test('resume starts after last successful stage',()=>{assert.equal(resumeIndex(['planner','developer','tester','reviewer'],'developer'),2);assert.equal(resumeIndex(['planner','developer'],undefined),0);});
test('watchdog marks stalled execution after missing heartbeat',async()=>{await new Promise<void>((resolve,reject)=>{const watchdog=new ExecutionWatchdog(250,()=>{watchdog.stop();resolve();});watchdog.start();setTimeout(()=>{watchdog.stop();reject(new Error('watchdog did not fire'));},700);});});
test('pipeline cancellation propagates',async()=>{const controller=new AbortController();controller.abort();const runner=new PipelineRunner(new MockAdapter(),{onStageStart(){},onStageComplete(){},onProgress(){},onHeartbeat(){},onFailure(){}});await assert.rejects(runner.run({task:{} as any,workspaceContext:{} as any,projectRules:[],previousArtifacts:[],constraints:{timeoutSeconds:1,tokenBudget:0,budgetUsd:0}},['planner'],0,controller.signal),/cancelled/i);});

test('pipeline retries provider errors according to policy',async()=>{let calls=0;const adapter:any={execute:async()=>{calls++;if(calls===1)throw Object.assign(new Error('temporary'),{kind:'provider_error'});return{output:'ok',tokenUsage:1,estimatedCost:0};}};const runner=new PipelineRunner(adapter,{onStageStart(){},onStageComplete(){},onProgress(){},onHeartbeat(){},onFailure(){}});const output=await runner.run({task:{} as any,workspaceContext:{} as any,projectRules:[],previousArtifacts:[],constraints:{timeoutSeconds:1,tokenBudget:0,budgetUsd:0}},['planner']);assert.equal(output[0],'ok');assert.equal(calls,2);});
