import test from 'node:test';import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {MockAdapter,RoleProviderRouter} from '@orchestrator/adapters';
import {DEFAULT_PROVIDER_CONFIG,PROVIDER_REGISTRY,SSE_EVENT_TYPES,makeSseEnvelope,providerAuthSemantics} from '@orchestrator/shared';
import {BudgetExceededError,BudgetGuard,ExecutionWatchdog,WorkspaceLockManager,assertPipelineApprovalIntegrity,resumeIndex,PipelineRunner} from '@orchestrator/core';
import {ClaudeCodePromptRefiner} from './claude-code-prompt-refiner.js';

test('provider capabilities are explicit and mock reports usage',async()=>{const a=new MockAdapter();assert.equal(await a.checkAvailability(),true);assert.equal(a.capabilities.cancel,true);assert.equal(a.capabilities.filesystemAccess,false);const result=await a.execute({stage:'reviewer'});assert.match(result.output,/APPROVED/);assert.equal(result.stdout,result.output);assert.equal(result.stderr,'');assert.equal(result.progressEvents.length,3);assert.equal(result.structuredResult?.status,'APPROVED');assert.equal(result.providerSessionId,'mock-session');assert.equal(result.conversationId,'mock-conversation');assert.equal(result.resumeToken,'mock-resume-token');assert.ok(result.tokenUsage>0);});
test('budget guard blocks exceeded spend',()=>{const guard=new BudgetGuard(1,100);assert.throws(()=>guard.assertCanStart(1.1,0),BudgetExceededError);assert.throws(()=>guard.assertCanStart(0,101),BudgetExceededError);});
test('workspace lock prevents concurrent ownership',()=>{const locks=new WorkspaceLockManager();locks.acquire('workspace:w','a');assert.throws(()=>locks.acquire('workspace:w','b'),/Lock busy/);locks.release('workspace:w','a');locks.acquire('workspace:w','b');});
test('resume starts after last successful stage',()=>{assert.equal(resumeIndex(['planner','developer','tester','reviewer'],'developer'),2);assert.equal(resumeIndex(['planner','developer'],undefined),0);});
test('watchdog marks stalled execution after missing heartbeat',async()=>{await new Promise<void>((resolve,reject)=>{const watchdog=new ExecutionWatchdog(250,()=>{watchdog.stop();resolve();});watchdog.start();setTimeout(()=>{watchdog.stop();reject(new Error('watchdog did not fire'));},700);});});
test('pipeline cancellation propagates',async()=>{const controller=new AbortController();controller.abort();const runner=new PipelineRunner(new MockAdapter(),{onStageStart(){},onStageComplete(){},onProgress(){},onHeartbeat(){},onFailure(){}});await assert.rejects(runner.run({task:{} as any,workspaceContext:{} as any,projectRules:[],previousArtifacts:[],constraints:{timeoutSeconds:1,tokenBudget:0,budgetUsd:0}},['planner'],0,controller.signal),/cancelled/i);});
test('reviewer approval integrity requires reviewer completion and last safe stage',async()=>{const roles:string[]=[];const adapter:any={execute:async(input:any)=>{roles.push(input.stage);return{output:input.stage,tokenUsage:0,structuredResult:input.stage==='reviewer'?{status:'APPROVED'}:{status:'COMPLETED'}};}};const runner=new PipelineRunner(adapter,{onStageStart(){},onStageComplete(){},onProgress(){},onHeartbeat(){},onFailure(){}});await runner.run({task:{configSnapshot:{autoFixEnabled:false}} as any,workspaceContext:{} as any,projectRules:[],previousArtifacts:[],constraints:{timeoutSeconds:1,tokenBudget:0,budgetUsd:0}},['planner','developer','tester','reviewer']);assert.deepEqual(roles,['planner','developer','tester','reviewer']);assert.doesNotThrow(()=>assertPipelineApprovalIntegrity({pipeline:['planner','developer','tester','reviewer'],lastSuccessfulStage:'reviewer'},roles.map(role=>({role,status:'completed',structuredResult:role==='reviewer'?{status:'APPROVED'}:{status:'COMPLETED'}}))));assert.throws(()=>assertPipelineApprovalIntegrity({pipeline:['planner','developer','tester','reviewer'],lastSuccessfulStage:'tester'},roles.slice(0,3).map(role=>({role,status:'completed',structuredResult:{status:'COMPLETED'}}))),error=>{assert.equal((error as any).kind,'pipeline_incomplete');assert.deepEqual((error as any).details.missingStages,['reviewer']);return true;});});
test('tester cannot silently finish a pipeline that requires reviewer',async()=>{const runner=new PipelineRunner({execute:async(input:any)=>({output:input.stage,tokenUsage:0,structuredResult:input.stage==='tester'?{status:'FAILED'}:{status:'COMPLETED'}})} as any,{onStageStart(){},onStageComplete(){},onProgress(){},onHeartbeat(){},onFailure(){}});await assert.rejects(runner.run({task:{configSnapshot:{autoFixEnabled:false}} as any,workspaceContext:{} as any,projectRules:[],previousArtifacts:[],constraints:{timeoutSeconds:1,tokenBudget:0,budgetUsd:0}},['planner','developer','tester','reviewer']),error=>{assert.equal((error as any).kind,'pipeline_incomplete');return true;});});

test('pipeline retries provider errors according to policy',async()=>{let calls=0;const adapter:any={execute:async()=>{calls++;if(calls===1)throw Object.assign(new Error('temporary'),{kind:'provider_error'});return{output:'ok',tokenUsage:1,estimatedCost:0};}};const runner=new PipelineRunner(adapter,{onStageStart(){},onStageComplete(){},onProgress(){},onHeartbeat(){},onFailure(){}});const output=await runner.run({task:{} as any,workspaceContext:{} as any,projectRules:[],previousArtifacts:[],constraints:{timeoutSeconds:1,tokenBudget:0,budgetUsd:0}},['planner']);assert.equal(output[0],'ok');assert.equal(calls,2);});

import {EventEmitter} from 'node:events';
import {CodexCliAdapter,ReviewerProviderRouter,resolveExecutable} from '@orchestrator/adapters';

const codexContext:any={task:{id:'codex-test',title:'Review',description:'Review safely',pipeline:['reviewer'],status:'reviewing',resumable:true,workspaceId:'w',taskBudgetUsd:1,tokenBudget:1000,configSnapshot:'{}',createdAt:'',updatedAt:''},workspaceContext:{id:'w',type:'local',location:process.cwd(),branch:'main'},projectRules:[],stage:'reviewer',previousArtifacts:[],constraints:{timeoutSeconds:1,tokenBudget:1000,budgetUsd:1}};
function fakeSpawn(config:{stdout?:string;stderr?:string;code?:number|null;delay?:number;never?:boolean;onChildCreated?:(child:any)=>void;synchronousMetadata?:boolean}={}){return (_command:string,args:string[])=>{const child:any=new EventEmitter();child.stdout=new EventEmitter();child.stderr=new EventEmitter();const metadata=args.includes('--help')||args.includes('--version');child.stdin={end(){if(config.never&&!metadata)return;const finish=()=>{const output=args.includes('--help')?'Usage: codex exec [OPTIONS] [PROMPT]\n      --json\n      --sandbox <MODE>\n      --model <MODEL>':args.includes('--version')?(config.stdout||'codex-cli 0.160.0'):config.stdout;if(output)child.stdout.emit('data',Buffer.from(output));if(config.stderr)child.stderr.emit('data',Buffer.from(config.stderr));child.emit('close',metadata?0:(config.code??0));};if(metadata)finish();else setTimeout(finish,config.delay||0);}};child.kill=()=>{if(!child.closed){child.closed=true;child.emit('close',null);}};child.args=args;config.onChildCreated?.(child);return child;};}
function review(status:'APPROVED'|'NEEDS_FIX'='APPROVED'){return JSON.stringify({status,summary:'review summary',issues:status==='APPROVED'?[]:[{severity:'high',file:'src/app.ts',description:'Fix this issue'}]});}

test('codex reports CLI missing separately from authentication',async()=>{const adapter=new CodexCliAdapter({executable:'codex-not-installed-for-test'});assert.equal(await adapter.checkAvailability(),false);const health=await adapter.getHealth();assert.equal(health.available,false);assert.equal(health.authenticated,false);});
test('codex health captures version and authentication error',async()=>{const adapter=new CodexCliAdapter({executable:'codex',spawn:fakeSpawn({stdout:'codex 1.2.3',stderr:'authentication required',code:0})});assert.equal(await adapter.checkAvailability(),true);const health=await adapter.getHealth();assert.equal(health.version,'1.2.3');assert.equal(health.authenticated,false);assert.equal(health.authenticationStatus,'unknown');});
test('codex rejects non-zero exit and captures stderr',async()=>{const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',spawn:fakeSpawn({stderr:'cli failure',code:2})});await assert.rejects(adapter.execute(codexContext),error=>{assert.equal((error as any).kind,'provider_error');assert.match(String(error),/cli failure/);return true;});});
test('codex validates APPROVED JSON and structured output',async()=>{let args:string[]=[];const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',spawn:(command,a)=>{args=a;return fakeSpawn({stdout:review('APPROVED')})(command,a);}});const result=await adapter.execute({...codexContext,onProgress(){},onHeartbeat(){}});assert.equal(result.structuredResult?.status,'APPROVED');assert.equal(result.stderr,'');assert.equal(result.tokenUsage,0);assert.ok(args.includes('--sandbox'));});
test('codex validates NEEDS_FIX JSON without textual approval fallback',async()=>{const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',spawn:fakeSpawn({stdout:review('NEEDS_FIX')})});const result=await adapter.execute(codexContext);assert.equal(result.structuredResult?.status,'NEEDS_FIX');assert.match(result.output,/NEEDS_FIX/);});
test('codex parses JSONL and uses the last valid agent_message',async()=>{const stream=[JSON.stringify({type:'thread.started',thread_id:'abc'}),'{not-json}',JSON.stringify({type:'item.completed',item:{type:'agent_message',text:'Analisando projeto...'}}),JSON.stringify({type:'item.completed',item:{type:'agent_message',text:review('APPROVED')}}),JSON.stringify({type:'turn.completed',usage:{input_tokens:100,output_tokens:20}})].join('\n');const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',spawn:fakeSpawn({stdout:stream})});const result=await adapter.execute(codexContext);assert.equal(result.structuredResult?.status,'APPROVED');assert.equal((result.rawProviderResponse as any).events.length,4);assert.equal((result.rawProviderResponse as any).turnCompleted,true);assert.equal(result.tokenUsage,120);});
test('codex parses NEEDS_FIX JSON inside a markdown code fence',async()=>{const text='```json\n'+review('NEEDS_FIX')+'\n```';const stream=JSON.stringify({type:'item.completed',item:{type:'agent_message',text}})+'\n'+JSON.stringify({type:'turn.completed'});const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',spawn:fakeSpawn({stdout:stream})});const result=await adapter.execute(codexContext);assert.equal(result.structuredResult?.status,'NEEDS_FIX');});
test('codex reports provider error when stream fails without completed turn',async()=>{const stream=JSON.stringify({type:'error',message:'provider failed'});const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',spawn:fakeSpawn({stdout:stream})});await assert.rejects(adapter.execute(codexContext),error=>{assert.equal((error as any).kind,'provider_error');return true;});});
test('codex rejects invalid JSON even when stdout contains APPROVED text',async()=>{const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',spawn:fakeSpawn({stdout:'APPROVED but not JSON'})});await assert.rejects(adapter.execute(codexContext),error=>{assert.equal((error as any).kind,'validation_error');return true;});});
test('codex times out and terminates only its child',async()=>{const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',timeoutMs:20,spawn:fakeSpawn({never:true})});await assert.rejects(adapter.execute(codexContext),error=>{assert.equal((error as any).kind,'timeout');return true;});});
test('codex responds to AbortSignal and cancel',async()=>{const controller=new AbortController();const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',timeoutMs:1000,spawn:fakeSpawn({never:true})});const promise=adapter.execute({...codexContext,signal:controller.signal});controller.abort();await assert.rejects(promise,error=>{assert.equal((error as any).kind,'cancelled');return true;});});
test('codex blocks invalid budget before spawning',async()=>{let spawned=false;const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',spawn:(command,args)=>{spawned=true;return fakeSpawn({stdout:review()})(command,args);}});await assert.rejects(adapter.execute({...codexContext,constraints:{timeoutSeconds:1,tokenBudget:1000,budgetUsd:-1}}),error=>{assert.equal((error as any).kind,'budget_exceeded');return true;});assert.equal(spawned,false);});
test('codex exposes the explicitly configured environment model',async()=>{assert.deepEqual(await new CodexCliAdapter({env:{...process.env,CODEX_MODEL:'gpt-5.6-luna'}}).getModels(),['gpt-5.6-luna']);});
test('codex exposes no model when CODEX_MODEL is not configured',async()=>{const env={...process.env};delete env.CODEX_MODEL;assert.deepEqual(await new CodexCliAdapter({env}).getModels(),[]);});
test('codex never invents a hardcoded model catalog',async()=>{const env={...process.env};delete env.CODEX_MODEL;const adapter=new CodexCliAdapter({env});assert.deepEqual(await adapter.getModels(),[]);assert.deepEqual(await new CodexCliAdapter({model:'configured-model',env}).getModels(),['configured-model']);});


test('resolver finds codex.cmd in a Windows PATH before exe and ps1',()=>{const resolved=resolveExecutable({platform:'win32',env:{PATH:'C:\\Tools;C:\\Users\\tester\\AppData\\Roaming\\npm'},pathExists:path=>path.endsWith('\\codex.cmd')});assert.equal(resolved?.path,'C:\\Tools\\codex.cmd');assert.equal(resolved?.isWindowsWrapper,true);});
test('resolver honors explicit Windows path containing spaces',()=>{const resolved=resolveExecutable({platform:'win32',explicit:'C:\\Program Files\\Codex\\codex.cmd',pathExists:()=>true});assert.equal(resolved?.source,'configured');assert.equal(resolved?.path,'C:\\Program Files\\Codex\\codex.cmd');});
test('resolver uses codex on Linux and does not require Windows wrappers',()=>{const resolved=resolveExecutable({platform:'linux',env:{PATH:'/usr/local/bin'},pathExists:path=>path==='/usr/local/bin/codex'});assert.equal(resolved?.path,'/usr/local/bin/codex');assert.equal(resolved?.isWindowsWrapper,false);});
test('health check keeps authentication unknown after safe version check',async()=>{const adapter=new CodexCliAdapter({executable:'codex.cmd',platform:'win32',spawn:fakeSpawn({stdout:'codex-cli 0.160.0'})});assert.equal(await adapter.checkAvailability(),true);const health=await adapter.getHealth();assert.equal(health.available,true);assert.equal(health.version,'0.160.0');assert.equal(health.authenticationStatus,'unknown');assert.equal(health.resolvedExecutable,'codex.cmd');});

import {buildAgentConfigs,configForRole,createTaskConfigSnapshot,toWorkspaceContext,validateAgentConfig,validateWorkspaceLocation} from './task-config.js';

test('task snapshot freezes Codex reviewer while other stages remain Mock',()=>{const snapshot=createTaskConfigSnapshot(['planner','developer','tester','reviewer'],{reviewerProvider:'codex-cli',codexModel:'gpt-5.6-luna',testerProvider:'mock',testerRequired:false,testerAllowedScripts:''},{},{});assert.deepEqual(snapshot.agentConfigs.map(c=>[c.role,c.provider,c.model]),[['planner','mock','mock-fast'],['developer','mock','mock-fast'],['tester','mock','mock-fast'],['reviewer','codex-cli','gpt-5.6-luna']]);assert.match(snapshot.providerSelection,/reviewer:codex-cli\/gpt-5.6-luna/);});
test('task keeps frozen config when environment changes later',()=>{const snapshot=createTaskConfigSnapshot(['reviewer'],{reviewerProvider:'codex-cli',codexModel:'gpt-5.6-luna',testerProvider:'mock',testerRequired:false,testerAllowedScripts:''},{},{});const later=buildAgentConfigs(['reviewer'],{reviewerProvider:'mock',codexModel:'other-model',testerProvider:'mock'});assert.equal(configForRole(snapshot,'reviewer').provider,'codex-cli');assert.equal(configForRole(snapshot,'reviewer').model,'gpt-5.6-luna');assert.equal(later[0].provider,'mock');});
test('execution context uses registered workspace location and branch',()=>{const context=toWorkspaceContext({id:'w1',name:'Mapa AI',type:'local',location:'C:\\xampp\\htdocs\\mapa-ai',branch:'main',status:'active',taskBudgetUsd:0,monthlyBudgetUsd:0,createdAt:'',updatedAt:''});assert.deepEqual(context,{id:'w1',type:'local',location:'C:\\xampp\\htdocs\\mapa-ai',branch:'main'});});
test('missing local workspace blocks execution before provider',()=>{assert.equal(validateWorkspaceLocation({type:'local',location:'/missing'},()=>false),false);assert.equal(validateWorkspaceLocation({type:'local',location:'/present'},()=>true),true);assert.equal(validateWorkspaceLocation({type:'git',location:'/remote'},()=>false),true);});


test('full mock pipeline completes all stages with no running executions',async()=>{const completed:string[]=[];const started:string[]=[];const runner=new PipelineRunner(new MockAdapter(),{onStageStart:role=>{started.push(role)},onStageComplete:role=>{completed.push(role)},onProgress(){},onHeartbeat(){},onFailure(){}});const result=await runner.run({task:{} as any,workspaceContext:{id:'w',type:'local',location:'/tmp',branch:'main'},projectRules:[],previousArtifacts:[],constraints:{timeoutSeconds:5,tokenBudget:0,budgetUsd:0}},['planner','developer','tester','reviewer']);assert.equal(result.length,4);assert.deepEqual(started,['planner','developer','tester','reviewer']);assert.deepEqual(completed,['planner','developer','tester','reviewer']);});
test('fake Codex reviewer is reached after mock stages',async()=>{const roles:string[]=[];const fake:any={...new MockAdapter(),execute:async(input:any)=>{if(input.stage==='reviewer')return{output:'{\"status\":\"APPROVED\",\"issues\":[]}',stdout:'fake codex',stderr:'',progressEvents:[],structuredResult:{status:'APPROVED',issues:[]},rawProviderResponse:{fake:true},tokenUsage:0};return new MockAdapter().execute(input);}};const runner=new PipelineRunner(new ReviewerProviderRouter(new MockAdapter(),fake),{onStageStart:role=>{roles.push(role)},onStageComplete(){},onProgress(){},onHeartbeat(){},onFailure(){}});await runner.run({task:{} as any,workspaceContext:{id:'w',type:'local',location:'/tmp'},projectRules:[],previousArtifacts:[],constraints:{timeoutSeconds:5,tokenBudget:0,budgetUsd:0}},['planner','developer','tester','reviewer']);assert.deepEqual(roles,['planner','developer','tester','reviewer']);});
test('cancellation during mock planner stops runner',async()=>{const controller=new AbortController();const promise=new PipelineRunner(new MockAdapter(),{onStageStart(){},onStageComplete(){},onProgress(){},onHeartbeat(){},onFailure(){}}).run({task:{} as any,workspaceContext:{} as any,projectRules:[],previousArtifacts:[],constraints:{timeoutSeconds:5,tokenBudget:0,budgetUsd:0}},['planner'],0,controller.signal);setTimeout(()=>controller.abort(),20);await assert.rejects(promise,/cancelled/i);});
test('cancellation during fake reviewer stops runner',async()=>{const controller=new AbortController();const fake:any={id:'fake-codex',name:'Fake Codex',capabilities:new MockAdapter().capabilities,checkAvailability:async()=>true,getModels:async()=>['fake'],cancel:async()=>{},getUsage:async()=>({tokenUsage:0,estimatedCost:0}),execute:async({signal}:any)=>await new Promise((_,reject)=>{signal?.addEventListener('abort',()=>reject(Object.assign(new Error('cancelled'),{kind:'cancelled'})));})};const runner=new PipelineRunner(new ReviewerProviderRouter(new MockAdapter(),fake),{onStageStart(){},onStageComplete(){},onProgress(){},onHeartbeat(){},onFailure(){}});const promise=runner.run({task:{} as any,workspaceContext:{} as any,projectRules:[],previousArtifacts:[],constraints:{timeoutSeconds:5,tokenBudget:0,budgetUsd:0}},['reviewer'],0,controller.signal);setTimeout(()=>controller.abort(),20);await assert.rejects(promise,/cancelled/i);});

test('watchdog heartbeat prevents stalled while activity continues',async()=>{let stalled=0;const watchdog=new ExecutionWatchdog(80,()=>{stalled++;});watchdog.start();for(let i=0;i<4;i++){await new Promise(r=>setTimeout(r,35));watchdog.beat();}watchdog.stop();assert.equal(stalled,0);});


test('SSE envelope carries named type, task, execution, timestamp and data',()=>{const envelope=makeSseEnvelope('execution.completed',{role:'planner'},'task-1','execution-1','2026-01-01T00:00:00.000Z');assert.deepEqual(envelope,{type:'execution.completed',taskId:'task-1',executionId:'execution-1',timestamp:'2026-01-01T00:00:00.000Z',data:{role:'planner'}});assert.ok(SSE_EVENT_TYPES.includes('execution.completed'));assert.ok(SSE_EVENT_TYPES.includes('task.completed'));});

test('codex 0.160 capability check detects json sandbox and model without prompt',async()=>{let promptCalls=0;const adapter=new CodexCliAdapter({executable:'codex',model:'gpt-5.6-luna',spawn:(command,args,options)=>{if(!args.includes('--help')&&!args.includes('--version'))promptCalls++;return fakeSpawn()(command,args);}});assert.equal(await adapter.checkAvailability(),true);const health=await adapter.getHealth();assert.deepEqual(health.supportedExecFlags,['--json','--sandbox','--model']);assert.deepEqual(health.unsupportedConfiguredFlags,[]);assert.equal(promptCalls,0);});
test('unsupported ask-for-approval is configuration_error before prompt',async()=>{let promptCalls=0;const adapter=new CodexCliAdapter({executable:'codex',model:'gpt-5.6-luna',safeArgs:['exec','--json','--sandbox','read-only','--ask-for-approval','never'],spawn:(command,args,options)=>{if(!args.includes('--help')&&!args.includes('--version'))promptCalls++;return fakeSpawn()(command,args);}});await assert.rejects(adapter.execute(codexContext),error=>{assert.equal((error as any).kind,'configuration_error');assert.match(String(error),/Unsupported Codex CLI argument: --ask-for-approval/);return true;});assert.equal(promptCalls,0);const health=await adapter.getHealth();assert.deepEqual(health.unsupportedConfiguredFlags,['--ask-for-approval']);});
test('configuration_error is not retried by PipelineRunner',async()=>{let calls=0;const adapter:any={execute:async()=>{calls++;throw Object.assign(new Error('Unsupported Codex CLI argument: --ask-for-approval'),{kind:'configuration_error'});}};const runner=new PipelineRunner(adapter,{onStageStart(){},onStageComplete(){},onProgress(){},onHeartbeat(){},onFailure(){}});await assert.rejects(runner.run({task:{} as any,workspaceContext:{} as any,projectRules:[],previousArtifacts:[],constraints:{timeoutSeconds:1,tokenBudget:0,budgetUsd:0}},['reviewer']),/ask-for-approval/);assert.equal(calls,1);});

test('silent Codex process emits heartbeat without fake progress and stops after cancel',async()=>{const controller=new AbortController();let heartbeats=0;let progress=0;let tick:(()=>void)|undefined;let cleared=false;const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',heartbeatIntervalMs:20,timeoutMs:500,spawn:fakeSpawn({never:true}),setIntervalFn:handler=>{tick=handler;return {} as ReturnType<typeof setInterval>},clearIntervalFn:()=>{cleared=true}});const promise=adapter.execute({...codexContext,signal:controller.signal,onHeartbeat:()=>heartbeats++,onProgress:()=>progress++});await new Promise<void>(resolve=>setImmediate(resolve));assert.ok(tick);tick!();assert.equal(heartbeats,1);tick!();assert.equal(heartbeats,2);assert.equal(progress,0);controller.abort();await assert.rejects(promise,error=>{assert.equal((error as any).kind,'cancelled');return true;});assert.equal(cleared,true);tick!();assert.equal(heartbeats,2);});
test('silent Codex process heartbeat stops after process close',async()=>{let heartbeats=0;let tick:(()=>void)|undefined;let child:any;const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',timeoutMs:500,spawn:fakeSpawn({never:true,onChildCreated:(created:any)=>{child=created}} as any),setIntervalFn:handler=>{tick=handler;return {} as ReturnType<typeof setInterval>},clearIntervalFn:()=>{}});const promise=adapter.execute({...codexContext,onHeartbeat:()=>heartbeats++});await new Promise<void>(resolve=>setImmediate(resolve));assert.ok(tick);tick!();assert.equal(heartbeats,1);child.emit('close',2);await assert.rejects(promise);tick!();assert.equal(heartbeats,1);});
test('Codex total timeout is distinct from provider stall heartbeat',async()=>{let heartbeats=0;let tick:(()=>void)|undefined;let cleared=false;const adapter=new CodexCliAdapter({executable:'codex',model:'configured-model',heartbeatIntervalMs:15,timeoutMs:70,spawn:fakeSpawn({never:true}),setIntervalFn:handler=>{tick=handler;return {} as ReturnType<typeof setInterval>},clearIntervalFn:()=>{cleared=true}});const promise=adapter.execute({...codexContext,onHeartbeat:()=>heartbeats++});await new Promise<void>(resolve=>setImmediate(resolve));assert.ok(tick);tick!();assert.equal(heartbeats,1);await assert.rejects(promise,error=>{assert.equal((error as any).kind,'timeout');return true;});assert.equal(cleared,true);tick!();assert.equal(heartbeats,1);});


test('stalled reviewer resume starts a new reviewer execution without rerunning safe stages',async()=>{const started:string[]=[];const runner=new PipelineRunner(new MockAdapter(),{onStageStart:role=>{started.push(role)},onStageComplete(){},onProgress(){},onHeartbeat(){},onFailure(){}});await runner.run({task:{} as any,workspaceContext:{} as any,projectRules:[],previousArtifacts:[],constraints:{timeoutSeconds:5,tokenBudget:0,budgetUsd:0}},['planner','developer','tester','reviewer'],resumeIndex(['planner','developer','tester','reviewer'],'tester'));assert.deepEqual(started,['reviewer']);assert.equal(resumeIndex(['planner','developer','tester','reviewer'],'tester'),3);});


test('NEEDS_FIX reviewer result completes once and does not retry',async()=>{let calls=0;let completed:any;const adapter:any={execute:async()=>{calls++;return{output:'review',tokenUsage:4,estimatedCost:0,structuredResult:{status:'NEEDS_FIX',summary:'issues',issues:[{severity:'high',file:'index.html',description:'encoding'}]}};}};const runner=new PipelineRunner(adapter,{onStageStart(){},onStageComplete:(_role,result)=>{completed=result;},onProgress(){},onHeartbeat(){},onFailure(){}});await runner.run({task:{} as any,workspaceContext:{} as any,projectRules:[],previousArtifacts:[],constraints:{timeoutSeconds:1,tokenBudget:0,budgetUsd:0}},['reviewer']);assert.equal(calls,1);assert.equal(completed.structuredResult.status,'NEEDS_FIX');});
test('bounded auto-fix loop runs developer/tester/reviewer without rerunning planner',async()=>{const roles:string[]=[];let reviewCount=0;let fixerPrompt='';const adapter:any={execute:async(input:any)=>{roles.push(input.stage);if(input.stage==='developer')fixerPrompt=input.stageContext.prompt;if(input.stage==='reviewer'){reviewCount++;return{output:'review',tokenUsage:1,estimatedCost:0,structuredResult:reviewCount===1?{status:'NEEDS_FIX',summary:'fix',issues:[{severity:'high',file:'a.ts',description:'issue X'}]}:{status:'APPROVED',summary:'ok',issues:[]}};}return{output:input.stage,tokenUsage:1,estimatedCost:0,structuredResult:{status:'COMPLETED'}};}};const runner=new PipelineRunner(adapter,{onStageStart(){},onStageComplete(){},onProgress(){},onHeartbeat(){},onFailure(){}});const base:any={task:{id:'fix-task',title:'Fix',description:'task',configSnapshot:{autoFixEnabled:true,maxFixCycles:2}},workspaceContext:{id:'w',type:'local',location:process.cwd()},projectRules:[],previousArtifacts:[],constraints:{timeoutSeconds:1,tokenBudget:0,budgetUsd:0}};await runner.run(base,['planner','developer','tester','reviewer']);assert.deepEqual(roles,['planner','developer','tester','reviewer','developer','tester','reviewer']);assert.match(fixerPrompt,/issue X/);});
test('auto-fix disabled stops at NEEDS_FIX',async()=>{let developers=0;let reviews=0;const adapter:any={execute:async(input:any)=>{if(input.stage==='developer')developers++;if(input.stage==='reviewer')reviews++;return{output:'x',tokenUsage:0,structuredResult:input.stage==='reviewer'?{status:'NEEDS_FIX',issues:[]}:{status:'COMPLETED'}};}};const runner=new PipelineRunner(adapter,{onStageStart(){},onStageComplete(){},onProgress(){},onHeartbeat(){},onFailure(){}});const base:any={task:{id:'off-task',title:'Fix',description:'task',configSnapshot:{autoFixEnabled:false,maxFixCycles:2}},workspaceContext:{id:'w',type:'local',location:process.cwd()},projectRules:[],previousArtifacts:[],constraints:{timeoutSeconds:1,tokenBudget:0,budgetUsd:0}};await runner.run(base,['developer','reviewer']);assert.equal(developers,1);assert.equal(reviews,1);});

import {ClaudeCodeAdapter,buildClaudeArgs,parseClaudeCapabilities,resolveClaudeExecutable,buildWindowsCmdInvocation} from '@orchestrator/adapters';
function fakeClaudeSpawn(config:{stdout?:string;stderr?:string;code?:number|null;delay?:number;never?:boolean;onStdin?:(value:string)=>void}={}){return (_command:string,args:string[],_options?:any)=>{const child:any=new EventEmitter();child.stdout=new EventEmitter();child.stderr=new EventEmitter();const metadata=args.includes('--version')||args.includes('--help');child.stdin={end(value?:string){config.onStdin?.(value||'');if(config.never&&!metadata)return;setTimeout(()=>{const output=args.includes('--version')?'Claude Code 1.2.3':args.includes('--help')?'Claude Code - starts an interactive session by default, use -p/--print for non-interactive output\\nUsage: claude [OPTIONS]\n  -p, --print\n  --model <model>\n  --allowedTools <tools...>\n  --disallowedTools <tools...>\n  --permission-mode <mode> (default acceptEdits dontAsk)\n  --max-turns <n>\n  --output-format <format>':config.stdout;if(output)child.stdout.emit('data',Buffer.from(output));if(config.stderr)child.stderr.emit('data',Buffer.from(config.stderr));child.emit('close',metadata?0:(config.code??0));},config.delay||0);}};child.kill=()=>{if(!child.closed){child.closed=true;child.emit('close',null);}};return child;};}
const claudeContext:any={task:{id:'claude-test',title:'Implement feature',description:'Implement safely',pipeline:['planner','developer','tester','reviewer'],status:'implementing',resumable:true,workspaceId:'w',taskBudgetUsd:1,tokenBudget:1000,configSnapshot:'{}',createdAt:'',updatedAt:''},workspaceContext:{id:'w',type:'local',location:'/tmp/workspace',branch:'main'},projectRules:[],stage:'developer',previousArtifacts:[],constraints:{timeoutSeconds:10,tokenBudget:1000,budgetUsd:1}};
const developerResult=JSON.stringify({status:'COMPLETED',summary:'Implemented safely',filesChanged:['src/app.ts'],testsRun:[{command:'pnpm test',status:'passed'}],notes:[]});
test('Claude args preserve tool patterns as individual arguments and cmd invocation is shell-free',()=>{const args=buildClaudeArgs({model:'sonnet',supportedFlags:['-p','--model','--allowedTools','--disallowedTools','--max-turns'],allowedTools:['Bash(git status:*)','Bash(php -l:*)'],disallowedTools:['Bash(git commit:*)'],maxTurns:15,safeArgs:[]});assert.ok(args.some(arg=>arg.includes('Bash(php -l:*)')));assert.ok(!args.includes('-l:*)'));const wrapped=buildWindowsCmdInvocation({executable:'C:\\Program Files\\Claude\\claude.cmd',args});assert.equal(wrapped.command,'cmd.exe');assert.equal(wrapped.shell,false);});
test('claude resolver honors configured path and Windows npm wrappers',()=>{assert.equal(resolveClaudeExecutable({explicit:'C:/Tools/Claude Code/claude.cmd',platform:'win32'})?.isWindowsWrapper,true);assert.equal(resolveClaudeExecutable({platform:'win32',env:{PATH:'C:/bin',APPDATA:'C:/Users/test/AppData/Roaming'},pathExists:path=>path.includes('AppData\\Roaming\\npm')&&path.endsWith('claude.cmd')})?.path,'C:\\Users\\test\\AppData\\Roaming\\npm\\claude.cmd');});
test('claude health uses version/help without model execution',async()=>{const adapter=new ClaudeCodeAdapter({executable:'claude',spawn:fakeClaudeSpawn()});assert.equal(await adapter.checkAvailability(),true);const health=await adapter.getHealth();assert.equal(health.version,'Claude Code 1.2.3');assert.deepEqual(health.supportedCliFlags,['-p','--print','--model','--output-format','--allowedTools','--disallowedTools','--permission-mode','--max-turns']);assert.equal(health.authenticationStatus,'unknown');});
test('claude validates developer structured result and workspace cwd',async()=>{let cwd='';let args:string[]=[];const adapter=new ClaudeCodeAdapter({executable:'claude',model:'sonnet-test',spawn:(command,a,options)=>{cwd=options.cwd||'';args=a;return fakeClaudeSpawn({stdout:developerResult})(command,a,options);}});const result=await adapter.execute(claudeContext);assert.equal(result.structuredResult?.status,'COMPLETED');assert.equal(cwd,'/tmp/workspace');assert.ok(args.includes('-p'));assert.ok(args.includes('--model'));});test('claude sends shell-sensitive prompt through stdin and never puts it in args',async()=>{let stdin='';let args:string[]=[];const task={...claudeContext,task:{...claudeContext.task,title:'Return ONLY: {\"status\":\"COMPLETED\"|\"BLOCKED\"}',description:'Teste A | Teste B; a & b; x > y; \"quoted\"; {json} [] ()'}};const adapter=new ClaudeCodeAdapter({executable:'C:/Users/test/AppData/Roaming/npm/claude.cmd',platform:'win32',model:'sonnet-test',spawn:(command,a)=>{args=a;return fakeClaudeSpawn({stdout:developerResult,onStdin:value=>{stdin=value}})(command,a);}});const result=await adapter.execute(task);assert.equal(result.structuredResult?.status,'COMPLETED');assert.ok(stdin.includes('Teste A | Teste B'));assert.ok(stdin.includes('a & b'));assert.ok(stdin.includes('x > y'));assert.ok(stdin.includes('\"quoted\"'));assert.ok(!args.some(arg=>arg.includes('|')||arg.includes('&')||arg.includes('Teste A')));assert.ok(args.includes('-p'));assert.ok(args.includes('--model'));assert.ok(args.includes('--allowedTools'));assert.ok(args.includes('--disallowedTools'));assert.ok(args.some(arg=>arg.includes('Read')&&arg.includes('Write')));assert.ok(args.some(arg=>arg.includes('Bash(git commit:*)')));assert.ok(args.includes('--permission-mode'));assert.ok(args.includes('dontAsk'));assert.ok(args.includes('--max-turns'));assert.ok(args.includes('15'));assert.ok(!args.includes('--dangerously-skip-permissions'));});
test('claude rejects other roles and missing model',async()=>{const adapter=new ClaudeCodeAdapter({executable:'claude',spawn:fakeClaudeSpawn()});await assert.rejects(adapter.execute({...claudeContext,stage:'reviewer'}),error=>{assert.equal((error as any).kind,'validation_error');return true;});await assert.rejects(adapter.execute(claudeContext),error=>{assert.equal((error as any).kind,'validation_error');return true;});});
test('claude rejects unsupported configured safe args before execution',async()=>{const adapter=new ClaudeCodeAdapter({executable:'claude',model:'sonnet-test',safeArgs:['--unsafe-flag'],spawn:fakeClaudeSpawn()});await assert.rejects(adapter.execute(claudeContext),error=>{assert.equal((error as any).kind,'configuration_error');return true;});});
test('claude emits heartbeat, supports abort and timeout',async()=>{let heartbeats=0;const adapter=new ClaudeCodeAdapter({executable:'claude',model:'sonnet-test',heartbeatIntervalMs:10,timeoutMs:35,spawn:fakeClaudeSpawn({never:true})});await assert.rejects(adapter.execute({...claudeContext,onHeartbeat:()=>heartbeats++}),error=>{assert.equal((error as any).kind,'timeout');return true;});assert.ok(heartbeats>=1);const controller=new AbortController();const cancellable=new ClaudeCodeAdapter({executable:'claude',model:'sonnet-test',spawn:fakeClaudeSpawn({never:true})});const promise=cancellable.execute({...claudeContext,signal:controller.signal});setTimeout(()=>controller.abort(),5);await assert.rejects(promise,error=>{assert.equal((error as any).kind,'cancelled');return true;});});
test('provider snapshot selects Claude only for developer',()=>{const configs=buildAgentConfigs(['planner','developer','tester','reviewer'],{developerProvider:'claude-code',claudeModel:'sonnet-test',testerProvider:'mock'});assert.deepEqual(configs.map(config=>config.provider),['mock','claude-code','mock','mock']);assert.equal(configs[1].model,'sonnet-test');});

import {mkdtempSync,writeFileSync,unlinkSync,mkdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
import {LocalWorkspaceTransport,calculateWorkspaceChangeSet} from '@orchestrator/workspace';
function fixtureGit(){const dir=mkdtempSync(join(tmpdir(),'orchestrator-workspace-'));execFileSync('git',['init','-q'],{cwd:dir});execFileSync('git',['config','user.email','test@example.com'],{cwd:dir});execFileSync('git',['config','user.name','Test'],{cwd:dir});writeFileSync(join(dir,'tracked.txt'),'before\n');execFileSync('git',['add','tracked.txt'],{cwd:dir});execFileSync('git',['commit','-qm','fixture'],{cwd:dir});return dir;}
test('workspace baseline is empty for a clean Git fixture',async()=>{const transport=new LocalWorkspaceTransport(fixtureGit());const baseline=await transport.captureBaseline();assert.equal(baseline.gitAvailable,true);assert.equal(baseline.statusBefore,'');assert.deepEqual(baseline.untrackedBefore,[]);});
test('workspace changeset includes a dirty file modified again during the task',async()=>{const dir=fixtureGit();writeFileSync(join(dir,'tracked.txt'),'preexisting\n');const transport=new LocalWorkspaceTransport(dir);const baseline=await transport.captureBaseline();writeFileSync(join(dir,'tracked.txt'),'developer\n');const after=await transport.captureState();const changes=calculateWorkspaceChangeSet(baseline,after);assert.equal(changes.preExistingChanges,true);assert.deepEqual(changes.filesChanged,['tracked.txt']);assert.deepEqual(changes.modified,['tracked.txt']);});
test('workspace changeset excludes an untouched pre-existing dirty file',async()=>{const dir=fixtureGit();writeFileSync(join(dir,'tracked.txt'),'preexisting\n');const transport=new LocalWorkspaceTransport(dir);const baseline=await transport.captureBaseline();const after=await transport.captureState();const changes=calculateWorkspaceChangeSet(baseline,after);assert.equal(changes.preExistingChanges,true);assert.deepEqual(changes.filesChanged,[]);assert.deepEqual(changes.preExistingFiles,['tracked.txt']);});
test('workspace changeset excludes pre-existing files and detects developer additions',async()=>{const dir=fixtureGit();writeFileSync(join(dir,'tracked.txt'),'preexisting\n');const transport=new LocalWorkspaceTransport(dir);const baseline=await transport.captureBaseline();writeFileSync(join(dir,'tracked.txt'),'developer\n');writeFileSync(join(dir,'new.txt'),'created\n');const after=await transport.captureState();const changes=calculateWorkspaceChangeSet(baseline,after);assert.equal(changes.preExistingChanges,true);assert.deepEqual(changes.filesChanged,['tracked.txt','new.txt']);assert.deepEqual(changes.added,['new.txt']);assert.deepEqual(changes.modified,['tracked.txt']);});
test('workspace changeset detects a developer deletion from a clean baseline',async()=>{const dir=fixtureGit();const transport=new LocalWorkspaceTransport(dir);const baseline=await transport.captureBaseline();unlinkSync(join(dir,'tracked.txt'));const after=await transport.captureState();const changes=calculateWorkspaceChangeSet(baseline,after);assert.deepEqual(changes.deleted,['tracked.txt']);assert.deepEqual(changes.filesChanged,['tracked.txt']);});
test('workspace without Git continues with gitAvailable false',async()=>{const dir=mkdtempSync(join(tmpdir(),'orchestrator-nogit-'));mkdirSync(join(dir,'nested'));const transport=new LocalWorkspaceTransport(dir);const baseline=await transport.captureBaseline();const after=await transport.captureState();assert.equal(baseline.gitAvailable,false);assert.equal(after.gitAvailable,false);assert.deepEqual(calculateWorkspaceChangeSet(baseline,after).filesChanged,[]);});
test('workspace transport exposes only read-only Git inspection commands',async()=>{const transport=new LocalWorkspaceTransport(fixtureGit());assert.equal(await transport.gitStatus(),'');assert.equal(await transport.gitDiff(),'');await assert.rejects(transport.checkout('main'),/read-only/);});

test('cli invocation errors are not retried by the pipeline',async()=>{let calls=0;const adapter:any={execute:async()=>{calls++;throw Object.assign(new Error('wrapper invocation failed'),{kind:'cli_invocation_error'});}};const runner=new PipelineRunner(adapter,{onStageStart(){},onStageComplete(){},onProgress(){},onHeartbeat(){},onFailure(){}});await assert.rejects(runner.run({task:{} as any,workspaceContext:{} as any,projectRules:[],previousArtifacts:[],constraints:{timeoutSeconds:1,tokenBudget:0,budgetUsd:0}},['developer']),/wrapper invocation failed/);assert.equal(calls,1);});
test('Windows cmd invocation treats executable separately from complex args',()=>{for(const executable of ['C:\\tools\\claude.cmd','C:\\Program Files\\Claude\\claude.cmd','C:\\Users\\aghiggi\\AppData\\Roaming\\npm\\claude.cmd']){const invocation=buildWindowsCmdInvocation({executable,args:['-p','--model','sonnet','Bash(git status:*)','Bash(php -l:*)','Bash(npm run test:*)','& | > < ^ ( ) * :','C:\\Program Files\\workspace']});const commandLine=invocation.args[2],unescaped=commandLine.replace(/\^/g,'');assert.equal(invocation.command,'cmd.exe');assert.equal(invocation.shell,false);assert.ok(!commandLine.includes('\\"'));assert.ok(unescaped.includes(executable));assert.ok(unescaped.includes('Bash(php -l:*)'));assert.ok(unescaped.includes('Bash(npm run test:*)'));}});
test('Claude Code Prompt Refiner uses haiku independently and sends request through stdin without tools',async()=>{let stdin='';let observedArgs:string[]=[];const refiner=new ClaudeCodePromptRefiner('haiku',{timeoutMs:1000,env:{CLAUDE_CLI_PATH:'claude'},spawn:(command,args,options)=>{observedArgs=args;return fakeClaudeSpawn({stdout:JSON.stringify({result:JSON.stringify({title:'Refined',objective:'Implement request',acceptanceCriteria:['done']})}),onStdin:value=>{stdin=value}})(command,args,options);}});const result=await refiner.refine({request:'special & request',workspaceName:'demo',workspaceBranch:'main'});assert.equal(result.title,'Refined');assert.ok(observedArgs.includes('-p'));assert.ok(observedArgs.includes('--model'));assert.ok(observedArgs.includes('haiku'));assert.ok(!observedArgs.includes('--allowedTools'));assert.ok(!observedArgs.includes('--disallowedTools'));assert.ok(stdin.includes('task specification refiner'));assert.ok(stdin.includes('special & request'));assert.equal(stdin.includes('sonnet'),false);});
test('Claude 2.1.287 capabilities parse help from stdout, stderr and aliases',()=>{const fixture='Claude Code - starts an interactive session by default, use -p/--print for non-interactive output\n--allowedTools, --allowed-tools <tools...>\n--disallowedTools, --disallowed-tools <tools...>\n--model <model>\n--output-format <format>\n--permission-mode <mode>\n--permission-prompts <target>\n--tools <tools...>\nacceptEdits auto bypassPermissions manual dontAsk plan';const stdout=parseClaudeCapabilities(fixture);const stderr=parseClaudeCapabilities(fixture);assert.deepEqual(stdout,stderr);assert.ok(stdout.supportedFlags.includes('-p'));assert.ok(stdout.supportedFlags.includes('--print'));assert.ok(stdout.supportedFlags.includes('--allowed-tools'));assert.ok(stdout.supportedFlags.includes('--disallowed-tools'));assert.ok(stdout.supportedFlags.includes('--permission-prompts'));assert.ok(!stdout.supportedFlags.includes('--max-turns'));const args=buildClaudeArgs({model:'sonnet',supportedFlags:stdout.supportedFlags,allowedTools:['Read','Bash(php -l:*)'],disallowedTools:['Bash(git commit:*)'],permissionMode:'dontAsk',maxTurns:15,safeArgs:[],outputFormat:'json'});assert.deepEqual(args.slice(-7),['--allowedTools','Read,Bash(php -l:*)','--disallowedTools','Bash(git commit:*)','--permission-mode','dontAsk','--permission-prompts','none'].slice(-7));});
test('required BLOCKED tester stops without provider failure or fix cycle',async()=>{const roles:string[]=[];const adapter:any={execute:async(input:any)=>{roles.push(input.stage);return{output:'blocked',tokenUsage:0,structuredResult:input.stage==='tester'?{status:'BLOCKED',blockReason:'No safe test command was detected'}:{status:'COMPLETED'}};}};const runner=new PipelineRunner(adapter,{onStageStart(){},onStageComplete(){},onProgress(){},onHeartbeat(){},onFailure(){throw new Error('provider failure should not occur');}});const base:any={task:{id:'blocked-required',title:'Blocked',description:'task',configSnapshot:{autoFixEnabled:true,maxFixCycles:2,testerRequired:true}},workspaceContext:{id:'w',type:'local',location:process.cwd()},projectRules:[],previousArtifacts:[],constraints:{timeoutSeconds:1,tokenBudget:0,budgetUsd:0}};await assert.rejects(runner.run(base,['developer','tester','reviewer']),error=>{assert.equal((error as any).kind,'pipeline_incomplete');assert.equal((error as any).details.reason,'tester_blocked');return true;});assert.deepEqual(roles,['developer','tester']);});
test('optional BLOCKED tester continues to reviewer without auto-fix',async()=>{const roles:string[]=[];const adapter:any={execute:async(input:any)=>{roles.push(input.stage);return{output:'blocked',tokenUsage:0,structuredResult:input.stage==='tester'?{status:'BLOCKED',blockReason:'No safe test command was detected'}:{status:'APPROVED',issues:[]}};}};const runner=new PipelineRunner(adapter,{onStageStart(){},onStageComplete(){},onProgress(){},onHeartbeat(){},onFailure(){}});const base:any={task:{id:'blocked-optional',title:'Blocked',description:'task',configSnapshot:{autoFixEnabled:true,maxFixCycles:2,testerRequired:false}},workspaceContext:{id:'w',type:'local',location:process.cwd()},projectRules:[],previousArtifacts:[],constraints:{timeoutSeconds:1,tokenBudget:0,budgetUsd:0}};await runner.run(base,['developer','tester','reviewer']);assert.deepEqual(roles,['developer','tester','reviewer']);});
test('task snapshot freezes tester requirement and allowed script names',()=>{const snapshot=createTaskConfigSnapshot(['tester'],{testerProvider:'command-tester',testerRequired:false,testerAllowedScripts:'test:orchestrator'},{},{});assert.equal(snapshot.testerRequired,false);assert.deepEqual(snapshot.testerAllowedScripts,['test:orchestrator']);assert.equal(snapshot.agentConfigs[0].provider,'command-tester');});
test('provider registry exposes the complete model catalog and safe auth billing semantics',()=>{const models=(id:string)=>PROVIDER_REGISTRY.find(p=>p.id===id)?.models.map(m=>m.modelId);assert.deepEqual(models('mock'),['mock-fast','mock-reasoning']);assert.deepEqual(models('claude-code'),['sonnet','haiku']);assert.deepEqual(models('command-tester'),['local-command-runner']);assert.deepEqual(models('codex-cli'),['gpt-5.6-luna']);assert.equal(PROVIDER_REGISTRY.find(p=>p.id==='command-tester')?.authMode,'not_applicable');assert.equal(PROVIDER_REGISTRY.find(p=>p.id==='mock')?.authMode,'not_applicable');assert.equal(PROVIDER_REGISTRY.find(p=>p.id==='command-tester')?.billingMode,'local');assert.equal(PROVIDER_REGISTRY.find(p=>p.id==='mock')?.billingMode,'no_external_cost');assert.equal(PROVIDER_REGISTRY.find(p=>p.id==='claude-code')?.authMode,'account_session_or_cli_managed');assert.equal(PROVIDER_REGISTRY.find(p=>p.id==='codex-cli')?.authMode,'account_session_or_cli_managed');assert.equal(PROVIDER_REGISTRY.some(p=>p.models.some(m=>m.contextWindow!==null&&p.id!=='mock')),false);});
test('role router does not silently replace configured real providers with Mock',()=>{const task:any={configSnapshot:{agentConfigs:[{role:'developer',provider:'claude-code',model:'sonnet'}]}};const router=new RoleProviderRouter({});assert.throws(()=>router.execute({stage:'developer',task} as any),error=>{assert.equal((error as any).kind,'configuration_error');assert.match(String(error),/no silent Mock fallback/);return true;});});
test('global provider defaults have a valid model for every role',()=>{assert.deepEqual(DEFAULT_PROVIDER_CONFIG,{planner:{provider:'mock',model:'mock-fast'},developer:{provider:'claude-code',model:'sonnet'},tester:{provider:'command-tester',model:'local-command-runner'},reviewer:{provider:'codex-cli',model:'gpt-5.6-luna'}});for(const [role,config] of Object.entries(DEFAULT_PROVIDER_CONFIG)){assert.ok(PROVIDER_REGISTRY.find(provider=>provider.id===config.provider)?.roles.includes(role as any));assert.ok(PROVIDER_REGISTRY.find(provider=>provider.id===config.provider)?.models.some(model=>model.modelId===config.model));}});
test('provider configuration validation blocks empty or incompatible models',()=>{assert.equal(validateAgentConfig('developer','claude-code','').valid,false);assert.equal(validateAgentConfig('tester','command-tester','mock-fast').valid,false);assert.equal(validateAgentConfig('tester','command-tester','local-command-runner').valid,true);});
test('workspace provider reset returns global effective config to the frontend',()=>{const server=readFileSync(new URL('./server.ts',import.meta.url),'utf8');const agents=readFileSync(new URL('../../web/src/WorkspaceAgentConfig.tsx',import.meta.url),'utf8');assert.match(server,/function workspaceProviderConfigResponse\(workspaceId:string\)/);assert.match(server,/app\.delete\('\/api\/workspaces\/:id\/provider-config'.*res\.json\(workspaceProviderConfigResponse\(req\.params\.id\)\)/);const global={...DEFAULT_PROVIDER_CONFIG};const workspaceOverride={developer:{provider:'mock',model:'mock-fast'}};const afterSave={global,workspace:workspaceOverride,effective:{...global,...workspaceOverride},origins:{planner:'global',developer:'workspace',tester:'global',reviewer:'global'}};const reset={global,workspace:{},effective:global,origins:Object.fromEntries(Object.keys(global).map(role=>[role,'global']))};assert.deepEqual(afterSave.workspace,workspaceOverride);assert.deepEqual(reset.workspace,{});assert.deepEqual(reset.effective,global);assert.deepEqual(reset.origins,{planner:'global',developer:'global',tester:'global',reviewer:'global'});assert.match(agents,/setSavedConfig\(persisted\.effective\)/);assert.match(agents,/setDraftConfig\(persisted\.effective\)/);assert.match(agents,/if\(!persisted\?\.effective\)\{await load\(\)\;/);});
test('task config UI clarifies tester blocked policy without renaming snapshot field',()=>{const source=readFileSync(new URL('../../web/src/main.tsx',import.meta.url),'utf8');assert.match(source,/Bloquear se testes não puderem ser executados/);assert.match(source,/Quando ativo, resultado BLOCKED do Tester exige intervenção\./);assert.match(source,/task\.configSnapshot\?\.testerRequired\?'Sim':'Não'/);assert.doesNotMatch(source,/Tester obrigatório/);});
test('providers UI keeps save feedback and dirty-state guards',()=>{const source=readFileSync(new URL('../../web/src/ProvidersPage.tsx',import.meta.url),'utf8');assert.match(source,/!dirty\|\|Boolean\(invalid\)\|\|saving/);assert.match(source,/Configuração salva com sucesso\./);assert.match(source,/Não foi possível salvar a configuração\./);assert.match(source,/const dirty=!equal\(savedConfig,draftConfig\)/);assert.match(source,/response\?\.global\|\|draftConfig/);});
test('workspace detail keeps provider settings responsive and semantically isolated',()=>{const main=readFileSync(new URL('../../web/src/main.tsx',import.meta.url),'utf8');const agents=readFileSync(new URL('../../web/src/WorkspaceAgentConfig.tsx',import.meta.url),'utf8');const providers=readFileSync(new URL('../../web/src/ProvidersPage.tsx',import.meta.url),'utf8');const css=readFileSync(new URL('../../web/src/composition-final.css',import.meta.url),'utf8');assert.match(main,/WorkspaceAgentConfig workspace=\{workspace\} notify=\{notify\}/);assert.match(agents,/Usando configuração global/);assert.match(agents,/Configuração personalizada/);assert.match(agents,/const dirty=Boolean\(draftConfig\)&&!equal\(savedConfig,draftConfig\)/);assert.match(agents,/Configuração do workspace salva\./);assert.match(agents,/Não foi possível salvar a configuração do workspace\./);assert.match(agents,/Usar configuração global/);assert.match(agents,/workspace-provider-role/);assert.match(css,/grid-template-columns:minmax\(0,1fr\) minmax\(0,380px\)/);assert.match(css,/@media\(max-width:1279px\)/);assert.match(css,/workspace-rail select/);assert.doesNotMatch(css,/body[^}]*overflow-x:hidden/);assert.match(providers,/Atualizando\.\.\./);assert.match(providers,/Status dos providers atualizado\./);assert.match(providers,/Não foi possível atualizar o status dos providers\./);});
test('provider auth semantics normalize stale health values at the source',()=>{assert.deepEqual(providerAuthSemantics('claude-code'),{authMode:'cli_managed',authenticationStatus:'cli_managed'});assert.deepEqual(providerAuthSemantics('codex-cli'),{authMode:'cli_managed',authenticationStatus:'cli_managed'});assert.deepEqual(providerAuthSemantics('command-tester'),{authMode:'not_applicable',authenticationStatus:'not_applicable'});assert.deepEqual(providerAuthSemantics('mock'),{authMode:'not_applicable',authenticationStatus:'not_applicable'});const stale={claude:{authenticationStatus:'not_configured'},codex:{authenticationStatus:'not_configured'},tester:{authenticationStatus:'authenticated'},mock:{authenticationStatus:'authenticated'}};const normalized={claude:{...stale.claude,...providerAuthSemantics('claude-code')},codex:{...stale.codex,...providerAuthSemantics('codex-cli')},tester:{...stale.tester,...providerAuthSemantics('command-tester')},mock:{...stale.mock,...providerAuthSemantics('mock')}};assert.deepEqual(normalized,{claude:{authenticationStatus:'cli_managed',authMode:'cli_managed'},codex:{authenticationStatus:'cli_managed',authMode:'cli_managed'},tester:{authenticationStatus:'not_applicable',authMode:'not_applicable'},mock:{authenticationStatus:'not_applicable',authMode:'not_applicable'}});});
test('workspace layout has one CSS source of truth without global overflow hiding',()=>{const approved=readFileSync(new URL('../../web/src/approved-ui.css',import.meta.url),'utf8');const composition=readFileSync(new URL('../../web/src/composition-final.css',import.meta.url),'utf8');assert.equal((composition.match(/\.workspace-detail-grid\{/g)||[]).length,2);assert.equal((composition.match(/\.workspace-primary\{/g)||[]).length,1);assert.equal((composition.match(/\.workspace-rail\{/g)||[]).length,2);assert.doesNotMatch(approved,/\.workspace-detail-grid\{|\.workspace-primary\{|\.workspace-rail\{/);assert.match(composition,/minmax\(0,380px\)/);assert.match(composition,/@media\(max-width:1279px\)/);assert.doesNotMatch(composition,/body[^}]*overflow-x:hidden/);});
