import {existsSync} from 'node:fs';
import type {AgentConfig,AgentRole,Workspace,WorkspaceType} from '@orchestrator/shared';

export interface ProviderEnvironment {reviewerProvider?:string;codexModel?:string;developerProvider?:string;claudeModel?:string;testerProvider?:string;testerAllowedScripts?:string;testerRequired?:boolean;}
export interface TaskConfigSnapshot {pipeline:AgentRole[];agentConfigs:AgentConfig[];securityPolicy:unknown;gates:unknown;providerSelection:string;autoFixEnabled:boolean;maxFixCycles:number;testerRequired:boolean;testerAllowedScripts:string[];}

export function buildAgentConfigs(pipeline:AgentRole[],env:ProviderEnvironment=process.env):AgentConfig[]{return pipeline.map(role=>{const isCodexReviewer=role==='reviewer'&&env.reviewerProvider==='codex-cli';const isClaudeDeveloper=role==='developer'&&env.developerProvider==='claude-code';const isCommandTester=role==='tester'&&env.testerProvider==='command-tester';return{role,provider:isCodexReviewer?'codex-cli':isClaudeDeveloper?'claude-code':isCommandTester?'command-tester':'mock',model:isCodexReviewer?(env.codexModel||'configured'):isClaudeDeveloper?(env.claudeModel||'configured'):isCommandTester?'local-command-runner':'mock-fast',timeoutSeconds:isClaudeDeveloper?180:120,maxRetries:2,maxIterations:3,budgetUsd:0,tokenBudget:0,fallbackProviders:[],enabled:true};});}
export function buildProviderSelection(configs:AgentConfig[]):string{return configs.map(config=>`${config.role}:${config.provider}/${config.model}`).join(',');}
export function createTaskConfigSnapshot(pipeline:AgentRole[],env:ProviderEnvironment,securityPolicy:unknown,gates:unknown):TaskConfigSnapshot{const runtimeEnv={...env,testerProvider:env.testerProvider??process.env.TESTER_PROVIDER};const agentConfigs=buildAgentConfigs(pipeline,runtimeEnv);const autoFixEnabled=String(process.env.AUTO_FIX_ENABLED??'true').toLowerCase()!=='false';const parsed=Number(process.env.MAX_FIX_CYCLES??2);const maxFixCycles=Number.isFinite(parsed)&&parsed>=0?Math.floor(parsed):2;const testerRequired=env.testerRequired??(String(process.env.TESTER_REQUIRED??'false').toLowerCase()==='true');const testerAllowedScripts=[...(env.testerAllowedScripts??process.env.TESTER_ALLOWED_SCRIPTS??'').split(',')].map(item=>item.trim()).filter(Boolean);return{pipeline,agentConfigs,securityPolicy,gates,providerSelection:buildProviderSelection(agentConfigs),autoFixEnabled,maxFixCycles,testerRequired,testerAllowedScripts};}
export function configForRole(snapshot:TaskConfigSnapshot,role:AgentRole):AgentConfig{return snapshot.agentConfigs.find(config=>config.role===role)||{role,provider:'mock',model:'mock-fast',timeoutSeconds:120,maxRetries:2,maxIterations:3,budgetUsd:0,tokenBudget:0,fallbackProviders:[],enabled:true};}
export function toWorkspaceContext(workspace:Workspace){return{id:workspace.id,type:workspace.type as WorkspaceType,location:workspace.location,branch:workspace.branch};}
export function validateWorkspaceLocation(workspace:Pick<Workspace,'type'|'location'>,pathExists:(path:string)=>boolean=existsSync){return workspace.type!=='local'||pathExists(workspace.location);}
