import {mkdirSync,mkdtempSync,readFileSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
import assert from 'node:assert/strict';
import test from 'node:test';
import {TaskIsolationError,TaskIsolationManager,buildTaskBranchName,inspectRepository} from '@orchestrator/workspace';

function git(cwd:string,args:string[]){return execFileSync('git',args,{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();}
function fixture(){const root=mkdtempSync(join(tmpdir(),'orquestradoria-isolation-test-'));git(root,['init','-b','main']);git(root,['config','user.email','test@example.invalid']);git(root,['config','user.name','Orquestradoria Test']);writeFileSync(join(root,'README.md'),'base\n');git(root,['add','.']);git(root,['commit','-m','base']);return root;}
function cleanup(root:string){try{rmSync(root,{recursive:true,force:true});}catch{}}

test('task isolation creates local branch/worktree and keeps dirty main untouched',()=>{const root=fixture();const manager=new TaskIsolationManager({root:mkdtempSync(join(tmpdir(),'orquestradoria-managed-'))});try{writeFileSync(join(root,'local-only.txt'),'keep on main\n');const environment=manager.prepare({workspaceId:'workspace-a',taskId:'task-a',title:'Implement feature',workspacePath:root,baseBranch:'main'});assert.equal(environment.isolationMode,'worktree');assert.equal(environment.mainDirty,true);assert.ok(environment.taskBranch?.startsWith('task/task-a-'));assert.ok(environment.worktreePath);assert.equal(git(root,['branch','--show-current']),'main');assert.equal(readFileSync(join(root,'local-only.txt'),'utf8'),'keep on main\n');assert.equal(readFileSync(join(environment.worktreePath!,'README.md'),'utf8').replace(/\r\n/g,'\n'),'base\n');}finally{cleanup(root);}});

test('two tasks receive distinct branches/worktrees and diff includes uncommitted task files',()=>{const root=fixture();const manager=new TaskIsolationManager({root:mkdtempSync(join(tmpdir(),'orquestradoria-managed-'))});try{const first=manager.prepare({workspaceId:'workspace-a',taskId:'task-one',title:'Same title',workspacePath:root});const second=manager.prepare({workspaceId:'workspace-a',taskId:'task-two',title:'Same title',workspacePath:root});assert.notEqual(first.taskBranch,second.taskBranch);assert.notEqual(first.worktreePath,second.worktreePath);writeFileSync(join(first.worktreePath!,'new-file.txt'),'uncommitted\n');writeFileSync(join(first.worktreePath!,'README.md'),'changed\n');const diff=manager.diff(first,root);assert.deepEqual(diff.added,['new-file.txt']);assert.ok(diff.modified.includes('README.md'));assert.ok(diff.files.some(file=>file.path==='new-file.txt'));manager.discard(first,root);manager.discard(second,root);}finally{cleanup(root);}});

test('approved task apply commits worktree changes, merges only on clean unchanged main, then can be discarded',()=>{const root=fixture();const manager=new TaskIsolationManager({root:mkdtempSync(join(tmpdir(),'orquestradoria-managed-'))});try{const environment=manager.prepare({workspaceId:'workspace-a',taskId:'task-apply',title:'Apply feature',workspacePath:root});writeFileSync(join(environment.worktreePath!,'feature.txt'),'implemented\n');assert.equal(manager.commitForApply(environment,'orchestrator: prepare apply'),true);manager.apply(environment,root);assert.equal(readFileSync(join(root,'feature.txt'),'utf8').replace(/\r\n/g,'\n'),'implemented\n');manager.discard(environment,root);assert.equal(git(root,['branch','--list',environment.taskBranch!]),'');}finally{cleanup(root);}});

test('apply blocks dirty main and advanced base without changing main',()=>{const root=fixture();const manager=new TaskIsolationManager({root:mkdtempSync(join(tmpdir(),'orquestradoria-managed-'))});try{const dirty=manager.prepare({workspaceId:'workspace-a',taskId:'task-dirty',title:'Dirty main',workspacePath:root});writeFileSync(join(dirty.worktreePath!,'x.txt'),'x\n');manager.commitForApply(dirty,'change');writeFileSync(join(root,'unrelated.txt'),'do not touch\n');assert.throws(()=>manager.apply(dirty,root),(error:any)=>error.code==='apply_blocked_dirty_workspace');rmSync(join(root,'unrelated.txt'));manager.discard(dirty,root);const advanced=manager.prepare({workspaceId:'workspace-a',taskId:'task-advanced',title:'Advanced base',workspacePath:root});writeFileSync(join(root,'main-change.txt'),'main\n');git(root,['add','.']);git(root,['commit','-m','advance main']);assert.throws(()=>manager.apply(advanced,root),(error:any)=>error.code==='base_branch_advanced');manager.discard(advanced,root);}finally{cleanup(root);}});

test('apply conflict aborts merge and preserves task worktree for review or discard',()=>{const root=fixture();const manager=new TaskIsolationManager({root:mkdtempSync(join(tmpdir(),'orquestradoria-managed-'))});try{const environment=manager.prepare({workspaceId:'workspace-a',taskId:'task-conflict',title:'Conflict',workspacePath:root});writeFileSync(join(environment.worktreePath!,'README.md'),'task version\n');manager.commitForApply(environment,'task change');writeFileSync(join(root,'README.md'),'main version\n');git(root,['add','README.md']);git(root,['commit','-m','main change']);environment.baseCommitSha=git(root,['rev-parse','main']);assert.throws(()=>manager.apply(environment,root),(error:any)=>error.code==='apply_conflict');assert.equal(git(root,['status','--porcelain']),'');assert.equal(readFileSync(join(environment.worktreePath!,'README.md'),'utf8').replace(/\r\n/g,'\n'),'task version\n');manager.discard(environment,root);}finally{cleanup(root);}});

test('non-Git workspace uses explicit current-workspace fallback and never fabricates isolation',()=>{const root=mkdtempSync(join(tmpdir(),'orquestradoria-no-git-'));const manager=new TaskIsolationManager({root:join(root,'managed')});try{const environment=manager.prepare({workspaceId:'workspace-a',taskId:'task-no-git',title:'No git',workspacePath:root});assert.equal(environment.isolationMode,'current-workspace');assert.equal(environment.worktreePath,undefined);assert.match(environment.warning||'',/Git isolation unavailable/);}finally{cleanup(root);}});

test('branch names are deterministic, readable, unique and task scoped',()=>{const first=buildTaskBranchName('abc123','Corrigir autenticação');const second=buildTaskBranchName('abc123','Corrigir autenticação',[first]);assert.match(first,/^task\/abc123-corrigir-autenticacao$/);assert.notEqual(first,second);assert.ok(second.startsWith('task/abc123-corrigir-autenticacao-'));});

test('unborn Git repository is distinguished from non-Git and preserves symbolic master',()=>{const root=mkdtempSync(join(tmpdir(),'orquestradoria-unborn-'));try{git(root,['init','-b','master']);writeFileSync(join(root,'untracked.txt'),'user data\n');const status=inspectRepository(root,'main');assert.equal(status.isGitRepository,true);assert.equal(status.hasCommits,false);assert.equal(status.currentBranch,'master');assert.equal(status.headSha,null);assert.equal(status.resolvedBaseBranch,'master');assert.equal(status.branchMismatch,true);assert.equal(status.dirty,true);assert.equal(status.untrackedCount,1);const manager=new TaskIsolationManager({root:mkdtempSync(join(tmpdir(),'orquestradoria-managed-'))});assert.throws(()=>manager.prepare({workspaceId:'workspace-a',taskId:'unborn',title:'Unborn',workspacePath:root,baseBranch:'main'}),(error:any)=>error instanceof TaskIsolationError&&error.code==='repository_has_no_commits');assert.equal(readFileSync(join(root,'untracked.txt'),'utf8'),'user data\n');}finally{cleanup(root);}});

test('master and main repositories resolve their actual committed base branch',()=>{for(const branch of ['master','main']){const root=fixture();if(branch==='master')git(root,['branch','-m','master']);const status=inspectRepository(root);assert.equal(status.resolvedBaseBranch,branch);const manager=new TaskIsolationManager({root:mkdtempSync(join(tmpdir(),'orquestradoria-managed-'))});const environment=manager.prepare({workspaceId:'workspace-a',taskId:`task-${branch}`,title:'Committed',workspacePath:root});assert.equal(environment.baseBranch,branch);assert.ok(environment.baseCommitSha);manager.discard(environment,root);cleanup(root);}});

test('configured valid branch wins over the currently checked out branch',()=>{const root=fixture();try{git(root,['branch','release']);git(root,['checkout','release']);const status=inspectRepository(root,'main');assert.equal(status.resolvedBaseBranch,'main');assert.equal(status.branchMismatch,false);const manager=new TaskIsolationManager({root:mkdtempSync(join(tmpdir(),'orquestradoria-managed-'))});const environment=manager.prepare({workspaceId:'workspace-a',taskId:'configured',title:'Configured base',workspacePath:root,baseBranch:'main'});assert.equal(environment.baseBranch,'main');manager.discard(environment,root);}finally{cleanup(root);}});

test('retrying the same task after an initial commit creates the worktree without auto bootstrap',()=>{const root=mkdtempSync(join(tmpdir(),'orquestradoria-retry-'));const managed=mkdtempSync(join(tmpdir(),'orquestradoria-managed-'));try{git(root,['init','-b','master']);writeFileSync(join(root,'README.md'),'baseline\n');const manager=new TaskIsolationManager({root:managed});assert.throws(()=>manager.prepare({workspaceId:'workspace-a',taskId:'retry',title:'Retry',workspacePath:root}),(error:any)=>error.code==='repository_has_no_commits');assert.equal(git(root,['status','--porcelain']).includes('README.md'),true);git(root,['add','README.md']);git(root,['commit','-m','initial baseline']);const environment=manager.prepare({workspaceId:'workspace-a',taskId:'retry',title:'Retry',workspacePath:root});assert.equal(environment.baseBranch,'master');assert.ok(environment.worktreePath);manager.discard(environment,root);}finally{cleanup(root);cleanup(managed);}});

test('existing worktree path is rejected with a typed conflict and no branch is created',()=>{const root=fixture();const managed=mkdtempSync(join(tmpdir(),'orquestradoria-managed-'));const taskPath=join(managed,'workspace-a','conflict');mkdirSync(taskPath,{recursive:true});try{const manager=new TaskIsolationManager({root:managed});assert.throws(()=>manager.prepare({workspaceId:'workspace-a',taskId:'conflict',title:'Conflict path',workspacePath:root}),(error:any)=>error.code==='worktree_path_conflict');assert.equal(git(root,['for-each-ref','refs/heads/task/','--format=%(refname:short)']),'');}finally{cleanup(root);cleanup(managed);}});
