import {mkdtempSync,readFileSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
import assert from 'node:assert/strict';
import test from 'node:test';
import {TaskIsolationManager,buildTaskBranchName} from '@orchestrator/workspace';

function git(cwd:string,args:string[]){return execFileSync('git',args,{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();}
function fixture(){const root=mkdtempSync(join(tmpdir(),'orquestradoria-isolation-test-'));git(root,['init','-b','main']);git(root,['config','user.email','test@example.invalid']);git(root,['config','user.name','Orquestradoria Test']);writeFileSync(join(root,'README.md'),'base\n');git(root,['add','.']);git(root,['commit','-m','base']);return root;}
function cleanup(root:string){try{rmSync(root,{recursive:true,force:true});}catch{}}

test('task isolation creates local branch/worktree and keeps dirty main untouched',()=>{const root=fixture();const manager=new TaskIsolationManager({root:mkdtempSync(join(tmpdir(),'orquestradoria-managed-'))});try{writeFileSync(join(root,'local-only.txt'),'keep on main\n');const environment=manager.prepare({workspaceId:'workspace-a',taskId:'task-a',title:'Implement feature',workspacePath:root,baseBranch:'main'});assert.equal(environment.isolationMode,'worktree');assert.equal(environment.mainDirty,true);assert.ok(environment.taskBranch?.startsWith('task/task-a-'));assert.ok(environment.worktreePath);assert.equal(git(root,['branch','--show-current']),'main');assert.equal(readFileSync(join(root,'local-only.txt'),'utf8'),'keep on main\n');assert.equal(readFileSync(join(environment.worktreePath!,'README.md'),'utf8').replace(/\r\n/g,'\n'),'base\n');}finally{cleanup(root);}});

test('two tasks receive distinct branches/worktrees and diff includes uncommitted task files',()=>{const root=fixture();const manager=new TaskIsolationManager({root:mkdtempSync(join(tmpdir(),'orquestradoria-managed-'))});try{const first=manager.prepare({workspaceId:'workspace-a',taskId:'task-one',title:'Same title',workspacePath:root});const second=manager.prepare({workspaceId:'workspace-a',taskId:'task-two',title:'Same title',workspacePath:root});assert.notEqual(first.taskBranch,second.taskBranch);assert.notEqual(first.worktreePath,second.worktreePath);writeFileSync(join(first.worktreePath!,'new-file.txt'),'uncommitted\n');writeFileSync(join(first.worktreePath!,'README.md'),'changed\n');const diff=manager.diff(first,root);assert.deepEqual(diff.added,['new-file.txt']);assert.ok(diff.modified.includes('README.md'));assert.ok(diff.files.some(file=>file.path==='new-file.txt'));manager.discard(first,root);manager.discard(second,root);}finally{cleanup(root);}});

test('approved task apply commits worktree changes, merges only on clean unchanged main, then can be discarded',()=>{const root=fixture();const manager=new TaskIsolationManager({root:mkdtempSync(join(tmpdir(),'orquestradoria-managed-'))});try{const environment=manager.prepare({workspaceId:'workspace-a',taskId:'task-apply',title:'Apply feature',workspacePath:root});writeFileSync(join(environment.worktreePath!,'feature.txt'),'implemented\n');assert.equal(manager.commitForApply(environment,'orchestrator: prepare apply'),true);manager.apply(environment,root);assert.equal(readFileSync(join(root,'feature.txt'),'utf8').replace(/\r\n/g,'\n'),'implemented\n');manager.discard(environment,root);assert.equal(git(root,['branch','--list',environment.taskBranch!]),'');}finally{cleanup(root);}});

test('apply blocks dirty main and advanced base without changing main',()=>{const root=fixture();const manager=new TaskIsolationManager({root:mkdtempSync(join(tmpdir(),'orquestradoria-managed-'))});try{const dirty=manager.prepare({workspaceId:'workspace-a',taskId:'task-dirty',title:'Dirty main',workspacePath:root});writeFileSync(join(dirty.worktreePath!,'x.txt'),'x\n');manager.commitForApply(dirty,'change');writeFileSync(join(root,'unrelated.txt'),'do not touch\n');assert.throws(()=>manager.apply(dirty,root),(error:any)=>error.code==='apply_blocked_dirty_workspace');rmSync(join(root,'unrelated.txt'));manager.discard(dirty,root);const advanced=manager.prepare({workspaceId:'workspace-a',taskId:'task-advanced',title:'Advanced base',workspacePath:root});writeFileSync(join(root,'main-change.txt'),'main\n');git(root,['add','.']);git(root,['commit','-m','advance main']);assert.throws(()=>manager.apply(advanced,root),(error:any)=>error.code==='base_branch_advanced');manager.discard(advanced,root);}finally{cleanup(root);}});

test('apply conflict aborts merge and preserves task worktree for review or discard',()=>{const root=fixture();const manager=new TaskIsolationManager({root:mkdtempSync(join(tmpdir(),'orquestradoria-managed-'))});try{const environment=manager.prepare({workspaceId:'workspace-a',taskId:'task-conflict',title:'Conflict',workspacePath:root});writeFileSync(join(environment.worktreePath!,'README.md'),'task version\n');manager.commitForApply(environment,'task change');writeFileSync(join(root,'README.md'),'main version\n');git(root,['add','README.md']);git(root,['commit','-m','main change']);environment.baseCommitSha=git(root,['rev-parse','main']);assert.throws(()=>manager.apply(environment,root),(error:any)=>error.code==='apply_conflict');assert.equal(git(root,['status','--porcelain']),'');assert.equal(readFileSync(join(environment.worktreePath!,'README.md'),'utf8').replace(/\r\n/g,'\n'),'task version\n');manager.discard(environment,root);}finally{cleanup(root);}});

test('non-Git workspace uses explicit current-workspace fallback and never fabricates isolation',()=>{const root=mkdtempSync(join(tmpdir(),'orquestradoria-no-git-'));const manager=new TaskIsolationManager({root:join(root,'managed')});try{const environment=manager.prepare({workspaceId:'workspace-a',taskId:'task-no-git',title:'No git',workspacePath:root});assert.equal(environment.isolationMode,'current-workspace');assert.equal(environment.worktreePath,undefined);assert.match(environment.warning||'',/Git isolation unavailable/);}finally{cleanup(root);}});

test('branch names are deterministic, readable, unique and task scoped',()=>{const first=buildTaskBranchName('abc123','Corrigir autenticação');const second=buildTaskBranchName('abc123','Corrigir autenticação',[first]);assert.match(first,/^task\/abc123-corrigir-autenticacao$/);assert.notEqual(first,second);assert.ok(second.startsWith('task/abc123-corrigir-autenticacao-'));});
