import {existsSync} from 'node:fs';
import {DEFAULT_GATES,DEFAULT_POLICY,modelForProvider,providerForRole,type AgentConfig, type AgentRole, type Workspace, type WorkspaceType} from '@orchestrator/shared';

export interface ProviderEnvironment {reviewerProvider?:string;codexModel?:string;developerProvider?:string;claudeModel?:string;testerProvider?:string;testerAllowedScripts?:string;testerRequired?:boolean;acceptanceCoverageRequired?:boolean;browserQaEnabled?:boolean;browserQaRequired?:boolean;browserQaInteractiveEnabled?:boolean;executionPolicy?:Partial<ExecutionPolicy>;persistedAgentConfigs?:Partial<Record<AgentRole,{provider:string;model:string}>>;}
export interface ExecutionPolicy {autoFixEnabled:boolean;maxFixCycles:number;testerRequired:boolean;acceptanceCoverageRequired:boolean;browserQaEnabled:boolean;browserQaRequired:boolean;browserQaInteractiveEnabled:boolean;}
export const DEFAULT_EXECUTION_POLICY:ExecutionPolicy={autoFixEnabled:true,maxFixCycles:2,testerRequired:false,acceptanceCoverageRequired:false,browserQaEnabled:false,browserQaRequired:false,browserQaInteractiveEnabled:false};
export interface TaskConfigSnapshot {pipeline:AgentRole[];agentConfigs:AgentConfig[];securityPolicy:unknown;gates:unknown;providerSelection:string;autoFixEnabled:boolean;maxFixCycles:number;testerRequired:boolean;acceptanceCoverageRequired:boolean;testerAllowedScripts:string[];browserQaEnabled:boolean;browserQaRequired:boolean;browserQaInteractiveEnabled:boolean;executionPolicyOrigins?:Record<keyof ExecutionPolicy,string>;}
export interface RuntimeConfig {stages:Record<AgentRole,{provider:string;model:string}>;autoFixEnabled:boolean;maxFixCycles:number;testerRequired:boolean;promptRefiner:{provider:string;model:string;mode:'mock'|'api'|'cli'|'fallback'};}

export function buildAgentConfigs(pipeline:AgentRole[],env:ProviderEnvironment=process.env):AgentConfig[]{return pipeline.map(role=>{const persisted=env.persistedAgentConfigs?.[role];const configuredProvider=persisted?.provider||(role==='reviewer'?env.reviewerProvider:role==='developer'?env.developerProvider:role==='tester'?env.testerProvider:undefined);const provider=configuredProvider||'mock';const model=persisted?.model||(provider==='codex-cli'?(env.codexModel||'gpt-5.6-luna'):provider==='claude-code'?(env.claudeModel||'sonnet'):provider==='command-tester'?'local-command-runner':provider==='mock'?'mock-fast':'configured');return{role,provider,model,timeoutSeconds:provider==='claude-code'?180:120,maxRetries:2,maxIterations:3,budgetUsd:0,tokenBudget:0,fallbackProviders:[],enabled:true};});}
export function buildProviderSelection(configs:AgentConfig[]):string{return configs.map(config=>`${config.role}:${config.provider}/${config.model}`).join(',');}
export function createTaskConfigSnapshot(pipeline:AgentRole[],env:ProviderEnvironment,securityPolicy:unknown,gates:unknown):TaskConfigSnapshot{const runtimeEnv={...env,testerProvider:env.testerProvider??process.env.TESTER_PROVIDER};const agentConfigs=buildAgentConfigs(pipeline,runtimeEnv);const policy=env.executionPolicy||{};const autoFixEnabled=policy.autoFixEnabled??(String(process.env.AUTO_FIX_ENABLED??'true').toLowerCase()!=='false');const parsed=Number(policy.maxFixCycles??process.env.MAX_FIX_CYCLES??DEFAULT_EXECUTION_POLICY.maxFixCycles);const maxFixCycles=Number.isFinite(parsed)&&parsed>=0?Math.floor(parsed):DEFAULT_EXECUTION_POLICY.maxFixCycles;const testerRequired=policy.testerRequired??env.testerRequired??(String(process.env.TESTER_REQUIRED??'false').toLowerCase()==='true');const acceptanceCoverageRequired=policy.acceptanceCoverageRequired??env.acceptanceCoverageRequired??(String(process.env.ACCEPTANCE_COVERAGE_REQUIRED??'false').toLowerCase()==='true');const browserQaEnabled=policy.browserQaEnabled??(env.browserQaEnabled??(String(process.env.BROWSER_QA_ENABLED??'false').toLowerCase()==='true'));const browserQaRequired=policy.browserQaRequired??(env.browserQaRequired??(String(process.env.BROWSER_QA_REQUIRED??'false').toLowerCase()==='true'));const browserQaInteractiveEnabled=policy.browserQaInteractiveEnabled??(String(process.env.BROWSER_QA_INTERACTIVE_ENABLED??'false').toLowerCase()==='true');const testerAllowedScripts=[...(env.testerAllowedScripts??process.env.TESTER_ALLOWED_SCRIPTS??'').split(',')].map(item=>item.trim()).filter(Boolean);return{pipeline,agentConfigs,securityPolicy,gates,providerSelection:buildProviderSelection(agentConfigs),autoFixEnabled,maxFixCycles,testerRequired,acceptanceCoverageRequired,testerAllowedScripts,browserQaEnabled,browserQaRequired,browserQaInteractiveEnabled};}
export function createRuntimeConfig(env:ProviderEnvironment=process.env):RuntimeConfig {const source=env as ProviderEnvironment&NodeJS.ProcessEnv;const normalized:ProviderEnvironment={...env,reviewerProvider:env.reviewerProvider??source.REVIEWER_PROVIDER,codexModel:env.codexModel??source.CODEX_MODEL,developerProvider:env.developerProvider??source.DEVELOPER_PROVIDER,claudeModel:env.claudeModel??source.CLAUDE_MODEL,testerProvider:env.testerProvider??source.TESTER_PROVIDER,testerRequired:env.testerRequired??(String(source.TESTER_REQUIRED||'false').toLowerCase()==='true'),testerAllowedScripts:env.testerAllowedScripts??source.TESTER_ALLOWED_SCRIPTS};const pipeline=['planner','developer','tester','reviewer'] as AgentRole[];const snapshot=createTaskConfigSnapshot(pipeline,normalized,DEFAULT_POLICY,DEFAULT_GATES);const stages=Object.fromEntries(snapshot.agentConfigs.map(config=>[config.role,{provider:config.provider,model:config.model}])) as RuntimeConfig['stages'];const provider=source.PROMPT_REFINER_PROVIDER||'mock';return{stages,autoFixEnabled:snapshot.autoFixEnabled,maxFixCycles:snapshot.maxFixCycles,testerRequired:snapshot.testerRequired,promptRefiner:{provider,model:source.PROMPT_REFINER_MODEL||(provider==='anthropic'?'claude-haiku-4-5-20251001':provider==='claude-code'?'haiku':'mock-fast'),mode:provider==='mock'?'mock':provider==='claude-code'?'cli':'api'}};}
export function configForRole(snapshot:TaskConfigSnapshot,role:AgentRole):AgentConfig{return snapshot.agentConfigs.find(config=>config.role===role)||{role,provider:'mock',model:'mock-fast',timeoutSeconds:120,maxRetries:2,maxIterations:3,budgetUsd:0,tokenBudget:0,fallbackProviders:[],enabled:true};}
export function validateAgentConfig(role:AgentRole,provider:string,model:string){if(!providerForRole(provider,role))return{valid:false,error:`Provider ${provider} is incompatible with role ${role}`};if(!modelForProvider(provider,model))return{valid:false,error:`Model ${model} is not enabled for provider ${provider}`};return{valid:true as const};}
export function toWorkspaceContext(workspace:Workspace){return{id:workspace.id,type:workspace.type as WorkspaceType,location:workspace.location,branch:workspace.branch};}
export function validateWorkspaceLocation(workspace:Pick<Workspace,'type'|'location'>,pathExists:(path:string)=>boolean=existsSync){return workspace.type!=='local'||pathExists(workspace.location);}
