import {spawn as nodeSpawn, type ChildProcessWithoutNullStreams} from 'node:child_process';
import {readFileSync,existsSync} from 'node:fs';
import {win32} from 'node:path';

export interface CommandInvocation {executable:string;args:string[];cwd?:string;env?:NodeJS.ProcessEnv;platform?:NodeJS.Platform;}
export type CliSpawnOptions={cwd?:string;env?:NodeJS.ProcessEnv;stdio:['pipe','pipe','pipe'];shell?:boolean};
export type CliSpawn=(command:string,args:string[],options:CliSpawnOptions)=>ChildProcessWithoutNullStreams;
export function resolveWindowsCmdTarget(executable:string,pathExists:(path:string)=>boolean=existsSync,readFile:(path:string)=>string=(path)=>readFileSync(path,'utf8')){try{const wrapper=readFile(executable);const match=wrapper.match(/%dp0%[^"'\r\n]+\.(?:exe|js|cjs)/i);if(!match)return undefined;const target=match[0].replace(/%dp0%/gi,`${win32.dirname(executable)}\\`).replace(/\\+/g,'\\');return pathExists(target)?target:undefined;}catch{return undefined;}}

function quoteWindowsArg(value:string){const escaped=value.replace(/(\\*)"/g,'$1$1\\"').replace(/(\\+)$/g,'$1$1');return `"${escaped}"`;}
function quoteWindowsExecutable(value:string){const escaped=value.replace(/"/g,'""');return /[\s()]/.test(value)?`"${escaped}"`:escaped;}
export function buildWindowsCmdInvocation(invocation:CommandInvocation){const executable=quoteWindowsExecutable(invocation.executable);const argumentsLine=invocation.args.map(quoteWindowsArg).join(' ');const cmdLine=['call',executable,argumentsLine].filter(Boolean).join(' ');return{command:'cmd.exe',args:['/d','/c',cmdLine],shell:false as const};}
export function prepareCliInvocation(command:string,args:string[],options:CliSpawnOptions,platform:NodeJS.Platform=process.platform){if(platform==='win32'&&command.toLowerCase().endsWith('.cmd')){const target=resolveWindowsCmdTarget(command);if(target)return{command:target,args,options:{...options,shell:false as const}};const wrapped=buildWindowsCmdInvocation({executable:command,args,platform});return{command:wrapped.command,args:wrapped.args,options:{...options,shell:false as const}};}return{command,args,options:{...options,shell:false as const}};}
export function createCliSpawn(platform:NodeJS.Platform=process.platform):CliSpawn{return(command,args,options)=>{const prepared=prepareCliInvocation(command,args,options,platform);return nodeSpawn(prepared.command,prepared.args,prepared.options);};}
export interface CliProcessResult{code:number|null;stdout:string;stderr:string;}
export function runCliProcess(invocation:CommandInvocation,spawn:CliSpawn=createCliSpawn(invocation.platform),signal?:AbortSignal):Promise<CliProcessResult>{return new Promise((resolve,reject)=>{const options={cwd:invocation.cwd,env:invocation.env,stdio:['pipe','pipe','pipe'] as ['pipe','pipe','pipe'],shell:false};const prepared=prepareCliInvocation(invocation.executable,invocation.args,options,invocation.platform||process.platform);let stdout='',stderr='',settled=false;let child:ChildProcessWithoutNullStreams;try{child=spawn(prepared.command,prepared.args,prepared.options);}catch(error){reject(error);return;}const finish=(callback:()=>void)=>{if(settled)return;settled=true;callback();};child.stdout.on('data',(chunk:Buffer)=>stdout+=chunk.toString());child.stderr.on('data',(chunk:Buffer)=>stderr+=chunk.toString());child.on('error',error=>finish(()=>reject(error)));child.on('close',code=>finish(()=>resolve({code,stdout,stderr})));signal?.addEventListener('abort',()=>{child.kill('SIGTERM');finish(()=>reject(Object.assign(new Error('CLI process cancelled'),{kind:'cancelled'})));},{once:true});child.stdin.end();});}
