import type {AgentRole,ProviderAdapter,ProviderCapabilities} from '@orchestrator/shared';
import {join} from 'node:path';
import {CommandTesterAdapter} from './tester.js';
const outputs:Record<AgentRole,string>={analyst:'Escopo analisado: dependências, riscos e critérios de aceite identificados.',planner:'Plano simulado criado com etapas incrementais e pontos de validação.',developer:'Implementação simulada concluída em um workspace isolado.',tester:'Testes simulados executados: nenhum bloqueio encontrado.',reviewer:'APPROVED — revisão simulada concluída com todos os critérios atendidos.'};
export class MockAdapter implements ProviderAdapter{id='mock';name='Mock Provider';capabilities:ProviderCapabilities={streaming:true,cancel:true,usageReporting:true,modelSelection:true,toolUse:false,filesystemAccess:false,sessionResume:true,structuredOutput:true};async checkAvailability(){return true;}async getModels(){return['mock-fast','mock-reasoning'];}async execute({stage,signal,onProgress,onHeartbeat,resumeToken}:{stage:AgentRole;signal?:AbortSignal;onProgress?:(message:string,percent?:number)=>void;onHeartbeat?:()=>void;resumeToken?:string}){const progressEvents=[] as {message:string;percent?:number;timestamp:string}[];for(let i=1;i<=3;i++){if(signal?.aborted)throw Object.assign(new Error('Execution cancelled'),{kind:'cancelled'});await new Promise(r=>setTimeout(r,250));onHeartbeat?.();const message=`Processando etapa ${i}/3`;const percent=Math.round(i/3*100);progressEvents.push({message,percent,timestamp:new Date().toISOString()});onProgress?.(message,percent);}const output=outputs[stage];const structuredResult=stage==='reviewer'?{stage,status:'APPROVED',summary:output,issues:[],resumedFrom:resumeToken||null}:{stage,status:'ok',resumedFrom:resumeToken||null};return{output,stdout:output,stderr:'',progressEvents,structuredResult,rawProviderResponse:{mock:true,stage},providerSessionId:resumeToken?'mock-session-resumed':'mock-session',conversationId:'mock-conversation',resumeToken:'mock-resume-token',tokenUsage:120+stage.length*7,estimatedCost:0};}async cancel(){return;}async getUsage(){return{tokenUsage:0,estimatedCost:0};}}
export class RoleProviderRouter implements ProviderAdapter{id='role-provider-router';name='Role provider router';capabilities:ProviderCapabilities;constructor(private readonly providers:Partial<Record<AgentRole,ProviderAdapter>>,private readonly fallback:ProviderAdapter=new MockAdapter()){this.capabilities={...fallback.capabilities};}checkAvailability(){return Promise.resolve(true);}getModels(){return this.fallback.getModels();}execute(input:Parameters<ProviderAdapter['execute']>[0]){const snapshot:any=input.task.configSnapshot;const configured=snapshot?.agentConfigs?.find((item:any)=>item.role===input.stage);const configuredProvider=configured?.provider||'mock';const provider=this.providers[input.stage]||(input.stage==='tester'&&configuredProvider==='command-tester'?new CommandTesterAdapter({env:{...process.env,TESTER_ALLOWED_SCRIPTS:(snapshot.testerAllowedScripts||[]).join(',')},browserQaEnabled:Boolean(snapshot.browserQaEnabled),browserQaRequired:Boolean(snapshot.browserQaRequired),screenshotDir:join(process.env.BROWSER_QA_SCREENSHOT_DIR||join(process.cwd(),'storage','local','browser-qa'),input.task.id)}):configuredProvider==='mock'?this.fallback:undefined);if(!provider)throw Object.assign(new Error(`Configured provider ${configuredProvider} is unavailable for role ${input.stage}; no silent Mock fallback was applied`),{kind:'configuration_error'});return provider.execute(input);}cancel(executionId:string){return Promise.all(Object.values(this.providers).map(provider=>provider?.cancel(executionId))).then(()=>undefined);}getUsage(){return this.fallback.getUsage();}}
export class ReviewerProviderRouter extends RoleProviderRouter {constructor(mock:MockAdapter,reviewer:ProviderAdapter){super({reviewer},mock);}}
export {CodexCliAdapter,resolveExecutable,classifyCodexCliError} from './codex.js';
export type {AuthenticationStatus,CodexCliConfig,CodexReview,CodexProviderHealth,ResolvedExecutable,ResolveExecutableOptions} from './codex.js';
export {ClaudeCodeAdapter,resolveClaudeExecutable,validateClaudeDeveloperResult} from './claude.js';
export {buildClaudeArgs,classifyClaudeCliError,parseClaudeCapabilities,validateClaudeHelpOutput,validateClaudeVersionOutput} from './claude.js';
export type {ClaudeArgsInput,ClaudeCapabilities,ClaudeCodeConfig,ClaudeDeveloperResult,ClaudeProviderHealth,ClaudeResolvedExecutable,ClaudeResolveOptions} from './claude.js';
export {buildWindowsCmdInvocation,createCliSpawn,prepareCliInvocation,resolveWindowsCmdTarget,runCliProcess} from './cli-process.js';
export type {CliSpawn,CommandInvocation,CliProcessResult} from './cli-process.js';
export {CommandTesterAdapter,detectProjectProfile,normalizeAssignedFiles} from './tester.js';
export {ClaudeCodeMissionPlanner,normalizeMissionPlannerOutput} from './mission-planner.js';
export {parseClaudeStructuredText} from './claude.js';
export type {ClaudeMissionPlannerConfig} from './mission-planner.js';
export type {CommandTesterConfig,TesterResult,TesterCommandResult,ProjectTestProfile,TestCommand} from './tester.js';
export {BrowserQaRunner,smokeRoutes} from './browser-qa.js';
export type {BrowserQaResult,BrowserQaRouteResult,BrowserQaLauncher} from './browser-qa.js';
