import {resolveClaudeExecutable,buildClaudeArgs,parseClaudeCapabilities,parseClaudeStructuredText} from './claude.js';
import {createCliSpawn} from './cli-process.js';

export interface ClaudeMissionPlannerConfig{model:string;env?:NodeJS.ProcessEnv;spawn?:any;timeoutMs?:number;executable?:string;}
function validationError(message:string){return Object.assign(new Error(message),{kind:'validation_error'});}
function validateMissionPlannerOutput(value:unknown){if(!value||typeof value!=='object')throw validationError('Claude Mission Planner result must be an object');const v=value as Record<string,unknown>;if(typeof v.summary!=='string')throw validationError('Claude Mission Planner summary must be a string');for(const field of ['assumptions','risks'])if(!Array.isArray(v[field])||!(v[field] as unknown[]).every(item=>typeof item==='string'))throw validationError(`Claude Mission Planner ${field} must be an array of strings`);if(!Array.isArray(v.tasks)||v.tasks.length<1||v.tasks.length>20)throw validationError('Claude Mission Planner tasks must contain between 1 and 20 items');const tasks=v.tasks.map((item,index)=>{if(!item||typeof item!=='object')throw validationError(`Claude Mission Planner task ${index+1} is invalid`);const task=item as Record<string,unknown>;if(typeof task.title!=='string'||!task.title.trim())throw validationError(`Claude Mission Planner task ${index+1} title is required`);if(typeof task.description!=='string'||!task.description.trim())throw validationError(`Claude Mission Planner task ${index+1} description is required`);if(!Array.isArray(task.acceptanceCriteria)||!task.acceptanceCriteria.every(criteria=>typeof criteria==='string'))throw validationError(`Claude Mission Planner task ${index+1} acceptanceCriteria is invalid`);if(!Array.isArray(task.dependsOn)||!task.dependsOn.every(dependency=>Number.isInteger(dependency)))throw validationError(`Claude Mission Planner task ${index+1} dependsOn is invalid`);return{title:task.title,description:task.description,acceptanceCriteria:task.acceptanceCriteria,dependsOn:task.dependsOn};});return{summary:v.summary,assumptions:v.assumptions,risks:v.risks,tasks};}
export class ClaudeCodeMissionPlanner{
  readonly model:string;private readonly env:NodeJS.ProcessEnv;private readonly executable:any;private readonly spawnProcess:any;private readonly timeoutMs:number;
  constructor(config:ClaudeMissionPlannerConfig){this.model=config.model;this.env=config.env||process.env;this.executable=resolveClaudeExecutable({explicit:config.executable,platform:process.platform,env:this.env});this.spawnProcess=config.spawn||createCliSpawn(process.platform);this.timeoutMs=config.timeoutMs||Number(this.env.CLAUDE_TIMEOUT_MS||180000);}
  async plan(input:any){if(!this.executable)throw Object.assign(new Error('Claude Code CLI not found'),{kind:'configuration_error'});const help=await this.run(['--help']);const capabilities=parseClaudeCapabilities(help.stdout+'\n'+help.stderr);if(!capabilities.supportedFlags.includes('-p')&&!capabilities.supportedFlags.includes('--print'))throw Object.assign(new Error('Claude CLI has no confirmed non-interactive print flag'),{kind:'configuration_error'});const args=buildClaudeArgs({model:this.model,supportedFlags:capabilities.supportedFlags,allowedTools:[],disallowedTools:['Read','Write','Edit','Bash'],permissionMode:'dontAsk',maxTurns:1,safeArgs:[],outputFormat:'json'});const prompt=['You are a task specification planner. Return ONLY valid JSON with summary, assumptions, risks and tasks. Do not modify files, commit, push or deploy.',`Mission: ${input.title}`,`Demand: ${input.request}`,`Project Context: ${JSON.stringify(input.projectContext||null)}`,`Workspace: ${JSON.stringify(input.workspace||{})}`].join('\n\n');const result=await this.run(args,prompt);try{return validateMissionPlannerOutput(parseClaudeStructuredText(result.stdout));}catch(error){if((error as any)?.kind==='validation_error'&&String((error as any)?.message).includes('structured output'))throw validationError('Não foi possível interpretar a resposta estruturada do Claude Mission Planner.');if((error as any)?.kind==='validation_error')throw error;throw validationError('Não foi possível interpretar a resposta estruturada do Claude Mission Planner.');}}
  private run(args:string[],stdin?:string){return new Promise<{stdout:string;stderr:string}>((resolve,reject)=>{let stdout='',stderr='';let child:any;try{child=this.spawnProcess(this.executable.path,args,{stdio:['pipe','pipe','pipe'],env:this.env,shell:false});}catch(error){reject(error);return;}const timer=setTimeout(()=>{child.kill?.('SIGTERM');reject(Object.assign(new Error('Claude Code Mission Planner timed out'),{kind:'timeout'}));},this.timeoutMs);child.stdout.on('data',(chunk:Buffer)=>stdout+=chunk.toString());child.stderr.on('data',(chunk:Buffer)=>stderr+=chunk.toString());child.on('error',(error:any)=>{clearTimeout(timer);reject(Object.assign(error,{kind:'cli_invocation_error'}));});child.on('close',(code:number)=>{clearTimeout(timer);if(code!==0)reject(Object.assign(new Error(stderr||`Claude Code exited with code ${code}`),{kind:'provider_error'}));else resolve({stdout,stderr});});child.stdin.end(stdin||'');});}
}
