import {resolveClaudeExecutable,buildClaudeArgs,parseClaudeCapabilities} from './claude.js';
import {createCliSpawn} from './cli-process.js';

export interface ClaudeMissionPlannerConfig{model:string;env?:NodeJS.ProcessEnv;spawn?:any;timeoutMs?:number;executable?:string;}
export class ClaudeCodeMissionPlanner{
  readonly model:string;private readonly env:NodeJS.ProcessEnv;private readonly executable:any;private readonly spawnProcess:any;private readonly timeoutMs:number;
  constructor(config:ClaudeMissionPlannerConfig){this.model=config.model;this.env=config.env||process.env;this.executable=resolveClaudeExecutable({explicit:config.executable,platform:process.platform,env:this.env});this.spawnProcess=config.spawn||createCliSpawn(process.platform);this.timeoutMs=config.timeoutMs||Number(this.env.CLAUDE_TIMEOUT_MS||180000);}
  async plan(input:any){if(!this.executable)throw Object.assign(new Error('Claude Code CLI not found'),{kind:'configuration_error'});const help=await this.run(['--help']);const capabilities=parseClaudeCapabilities(help.stdout+'\n'+help.stderr);if(!capabilities.supportedFlags.includes('-p')&&!capabilities.supportedFlags.includes('--print'))throw Object.assign(new Error('Claude CLI has no confirmed non-interactive print flag'),{kind:'configuration_error'});const args=buildClaudeArgs({model:this.model,supportedFlags:capabilities.supportedFlags,allowedTools:[],disallowedTools:['Read','Write','Edit','Bash'],permissionMode:'dontAsk',maxTurns:1,safeArgs:[],outputFormat:'json'});const prompt=['You are a task specification planner. Return ONLY valid JSON with summary, assumptions, risks and tasks. Do not modify files, commit, push or deploy.',`Mission: ${input.title}`,`Demand: ${input.request}`,`Project Context: ${JSON.stringify(input.projectContext||null)}`,`Workspace: ${JSON.stringify(input.workspace||{})}`].join('\n\n');const result=await this.run(args,prompt);let value:any;try{value=JSON.parse(result.stdout.trim());}catch{throw Object.assign(new Error('Claude Code Mission Planner retornou JSON inválido.'),{kind:'validation_error'});}return value;}
  private run(args:string[],stdin?:string){return new Promise<{stdout:string;stderr:string}>((resolve,reject)=>{let stdout='',stderr='';let child:any;try{child=this.spawnProcess(this.executable.path,args,{stdio:['pipe','pipe','pipe'],env:this.env,shell:false});}catch(error){reject(error);return;}const timer=setTimeout(()=>{child.kill?.('SIGTERM');reject(Object.assign(new Error('Claude Code Mission Planner timed out'),{kind:'timeout'}));},this.timeoutMs);child.stdout.on('data',(chunk:Buffer)=>stdout+=chunk.toString());child.stderr.on('data',(chunk:Buffer)=>stderr+=chunk.toString());child.on('error',(error:any)=>{clearTimeout(timer);reject(Object.assign(error,{kind:'cli_invocation_error'}));});child.on('close',(code:number)=>{clearTimeout(timer);if(code!==0)reject(Object.assign(new Error(stderr||`Claude Code exited with code ${code}`),{kind:'provider_error'}));else resolve({stdout,stderr});});child.stdin.end(stdin||'');});}
}
