import {existsSync,readFileSync,realpathSync} from 'node:fs';
import {basename,extname,isAbsolute,join,relative,resolve,sep} from 'node:path';

export type ProjectType='node'|'javascript'|'php'|'python'|'unknown';
export type PackageManager='pnpm'|'npm'|'yarn';
export type TestCommandKind='process'|'json';
export interface TestCommand{id:string;label:string;executable:string;args:string[];cwd:string;timeoutMs:number;kind?:TestCommandKind;file?:string;}
export interface ProjectTestProfile{projectType:ProjectType;packageManager?:PackageManager;commands:TestCommand[];notes:string[];fileAwareFallbacks?:string[];assignedFiles?:string[];unvalidatedFiles?:string[];}
export interface ProjectDetectorOptions{location:string;assignedFiles?:string[];allowedScripts?:string[];env?:NodeJS.ProcessEnv;timeoutMs?:number;}

const exists=(path:string)=>existsSync(path);
const readJson=(path:string):Record<string,unknown>|undefined=>{try{return JSON.parse(readFileSync(path,'utf8')) as Record<string,unknown>;}catch{return undefined;}};
const script=(pkg:Record<string,unknown>,name:string)=>typeof (pkg.scripts as Record<string,unknown>|undefined)?.[name]==='string';
const commandFor=(manager:PackageManager,name:string,cwd:string,timeoutMs:number):TestCommand=>({id:`${manager}:${name}`,label:name,executable:manager,args:name==='test'?[name]:['run',name],cwd,timeoutMs});
const fallbackCapabilities=['javascript: node --check','php: php -l','json: JSON parse'];
function safeAssignedFiles(root:string,files:string[]){const workspace=resolve(root);const accepted:string[]=[];for(const input of files){const value=input.trim();if(!value||isAbsolute(value))continue;const candidate=resolve(workspace,value);const rel=relative(workspace,candidate);if(!rel||rel.startsWith('..'+sep)||isAbsolute(rel)||!exists(candidate))continue;try{const realRoot=realpathSync(workspace),realCandidate=realpathSync(candidate),realRel=relative(realRoot,realCandidate);if(realRel.startsWith('..'+sep)||isAbsolute(realRel))continue;}catch{continue;}accepted.push(rel.replaceAll('\\','/'));}return[...new Set(accepted)];}
export function normalizeAssignedFiles(location:string,files:string[]){return safeAssignedFiles(location,files);}
export function detectProjectProfile(options:ProjectDetectorOptions):ProjectTestProfile{const cwd=options.location;const timeoutMs=options.timeoutMs||Number(options.env?.TEST_COMMAND_TIMEOUT_MS||120000);const assigned=safeAssignedFiles(cwd,options.assignedFiles||[]);const notes:string[]=[];const packageJson=readJson(join(cwd,'package.json'));if(packageJson){const manager=exists(join(cwd,'pnpm-lock.yaml'))?'pnpm':exists(join(cwd,'yarn.lock'))?'yarn':exists(join(cwd,'package-lock.json'))?'npm':'npm';const allowed=[...(options.allowedScripts||[])].map(item=>item.trim()).filter(Boolean);const names=[...new Set(['typecheck','test','build',...allowed])];const commands=names.filter(name=>script(packageJson,name)).map(name=>commandFor(manager,name,cwd,timeoutMs));if(!commands.length)notes.push('package.json has no safe detected or allowlisted scripts');const missing=allowed.filter(name=>!script(packageJson,name));if(missing.length)notes.push(`Allowlisted scripts not found: ${missing.join(', ')}`);return{projectType:'node',packageManager:manager,commands,notes,fileAwareFallbacks:fallbackCapabilities,assignedFiles:assigned,unvalidatedFiles:[]};}const commands:TestCommand[]=[];const unvalidated:string[]=[];const javascript=assigned.filter(file=>/\.(?:js|mjs|cjs)$/i.test(file));const php=assigned.filter(file=>/\.php$/i.test(file));const json=assigned.filter(file=>/\.json$/i.test(file));const typescript=assigned.filter(file=>/\.(?:ts|tsx)$/i.test(file));const python=assigned.filter(file=>/\.py$/i.test(file));const markup=assigned.filter(file=>/\.(?:html?|css)$/i.test(file));for(const file of javascript)commands.push({id:`node:check:${file}`,label:`node --check ${file}`,executable:'node',args:['--check',file],cwd,timeoutMs,file});for(const file of php)commands.push({id:`php:lint:${file}`,label:`php -l ${file}`,executable:'php',args:['-l',file],cwd,timeoutMs,file});for(const file of json)commands.push({id:`json:parse:${file}`,label:`JSON parse ${file}`,executable:'internal',args:['json-parse',file],cwd,timeoutMs,kind:'json',file});unvalidated.push(...markup);if(typescript.length)notes.push('TypeScript files detected but no safe typecheck command is configured.');if(python.length)notes.push('Python files detected; no safe command was inferred.');if(markup.length)notes.push(`${markup.join(', ')} detected without a safe validator.`);if(!assigned.length)notes.push('No task-assigned files were available for file-aware validation.');if(!commands.length&&unvalidated.length)notes.push('No safe validator configured for these file types.');const projectType=javascript.length?'javascript':php.length?'php':python.length?'python':typescript.length?'unknown':json.length?'unknown':'unknown';return{projectType,commands,notes,fileAwareFallbacks:fallbackCapabilities,assignedFiles:assigned,unvalidatedFiles:unvalidated};}
