import {createCliSpawn,type CliSpawn} from './cli-process.js';
import {readFileSync} from 'node:fs';
import {resolve as resolvePath} from 'node:path';
import {detectProjectProfile,normalizeAssignedFiles,type ProjectTestProfile, type TestCommand} from './project-detector.js';
import type {ExecutionContext,ProviderAdapter,ProviderCapabilities,ProviderExecutionResult} from '@orchestrator/shared';
import {RuntimeSessionManager} from '@orchestrator/workspace';
import {BrowserQaRunner,smokeRoutes,type BrowserQaResult} from './browser-qa.js';

export type TesterStatus='PASSED'|'FAILED'|'BLOCKED';
export interface TesterCommandResult{commandId:string;label:string;status:'passed'|'failed'|'blocked'|'cancelled'|'timed_out';exitCode:number|null;stdout:string;stderr:string;durationMs:number;}
export interface TesterResult{status:TesterStatus;projectProfile:ProjectTestProfile;assignedFiles:string[];validatedFiles:string[];unvalidatedFiles:string[];commands:TesterCommandResult[];detectedCommands:string[];executedCommands:string[];notes:string[];blockReason?:string;progress:number;summary:string;commandQa?:{status:TesterStatus;commands:TesterCommandResult[]};browserQa?:BrowserQaResult;runtime?:{type:string;baseUrl?:string;status:string;};}
export interface CommandTesterConfig{profile?:ProjectTestProfile;timeoutMs?:number;maxOutputChars?:number;failFast?:boolean;spawn?:CliSpawn;platform?:NodeJS.Platform;env?:NodeJS.ProcessEnv;browserQaEnabled?:boolean;browserQaRequired?:boolean;screenshotDir?:string;runtimeManager?:RuntimeSessionManager;browserQaRunner?:BrowserQaRunner;}
type TesterInput=ExecutionContext&{signal?:AbortSignal;onProgress?:(message:string,percent?:number)=>void;onHeartbeat?:()=>void};
const capabilities:ProviderCapabilities={streaming:false,cancel:true,usageReporting:false,modelSelection:false,toolUse:false,filesystemAccess:true,sessionResume:false,structuredOutput:true};
const executable=(name:string,platform:NodeJS.Platform)=>platform==='win32'&&['pnpm','npm','yarn'].includes(name)?`${name}.cmd`:name;
const bounded=(value:string,max:number)=>value.length<=max?value:`${value.slice(0,Math.max(0,max-32))}\n...[truncated]`;
const safeRelativeFile=(file:string)=>!file.startsWith('/')&&!/^[A-Za-z]:[\\/]/.test(file)&&!file.split(/[\\/]/).includes('..');
const safeCommand=(command:TestCommand)=>{if(command.kind==='json')return command.executable==='internal'&&command.args[0]==='json-parse'&&command.args.length===2&&safeRelativeFile(command.args[1]);if(command.executable==='node')return command.args.length===2&&command.args[0]==='--check'&&safeRelativeFile(command.args[1]);if(command.executable==='php')return command.args.length===2&&command.args[0]==='-l'&&/\.php$/i.test(command.args[1])&&safeRelativeFile(command.args[1]);if(!['pnpm','npm','yarn'].includes(command.executable))return false;return command.args.length<=2&&command.args.every(arg=>/^[A-Za-z0-9:_-]+$/.test(arg));};
const assignedFilesFromInput=(input:TesterInput)=>{const files=[...(input.stageContext?.contextFilesIncluded||[])];for(const artifact of input.previousArtifacts){if(artifact.type!=='diff')continue;try{const parsed=JSON.parse(artifact.content);files.push(...(parsed.changes?.filesChanged||parsed.actualFilesChanged||[]));}catch{}}return normalizeAssignedFiles(input.workspaceContext.location,files);};
const resolveFile=(location:string,file:string)=>resolvePath(location,file);

export class CommandTesterAdapter implements ProviderAdapter{
  id='command-tester';name='Command Tester';capabilities=capabilities;private readonly active=new Map<string,{kill:(signal?:NodeJS.Signals)=>void}>();
  constructor(private readonly config:CommandTesterConfig={}){}
  async checkAvailability(){return true;}
  async getModels(){return['local-command-runner'];}
  async getUsage(){return{tokenUsage:0,estimatedCost:undefined as unknown as number};}
  async cancel(executionId:string){this.active.get(executionId)?.kill('SIGTERM');}
  async execute(input:TesterInput):Promise<ProviderExecutionResult>{
    if(input.stage!=='tester')throw Object.assign(new Error('Command Tester is restricted to tester stage'),{kind:'validation_error'});
    const assignedFiles=assignedFilesFromInput(input);const profile=this.config.profile||detectProjectProfile({location:input.workspaceContext.location,assignedFiles,allowedScripts:(this.config.env||process.env).TESTER_ALLOWED_SCRIPTS?.split(',')||[],env:this.config.env||process.env});
    const maxOutput=this.config.maxOutputChars||Number(this.config.env?.TEST_MAX_OUTPUT_CHARS||12000);const commands=profile.commands;
    if(!commands.length){const result:TesterResult={status:'BLOCKED',projectProfile:profile,assignedFiles,validatedFiles:[],unvalidatedFiles:profile.unvalidatedFiles||assignedFiles,commands:[],detectedCommands:[],executedCommands:[],notes:profile.notes,blockReason:'No safe test command was detected',progress:0,summary:'No safe test command was detected'};return this.result(result);}
    const results:TesterCommandResult[]=[];
    for(const command of commands){if(!safeCommand(command)){results.push({commandId:command.id,label:command.label,status:'blocked',exitCode:null,stdout:'',stderr:'Unsafe generated command rejected',durationMs:0});if(this.config.failFast!==false)break;continue;}
      const item=command.kind==='json'?await this.runJson(command,input.workspaceContext.location,maxOutput):await this.runCommand(input,command,maxOutput);results.push(item);input.onProgress?.(`${command.label}: ${item.status}`,Math.round(results.length/commands.length*100));if(item.status!=='passed'&&this.config.failFast!==false)break;}
    let status:TesterStatus=results.some(r=>r.status==='failed'||r.status==='timed_out')?'FAILED':results.some(r=>r.status==='blocked'||r.status==='cancelled')?'BLOCKED':profile.unvalidatedFiles?.length&&results.length===0?'BLOCKED':'PASSED';const validatedFiles=results.filter(item=>item.status==='passed').map(item=>commands.find(command=>command.id===item.commandId)?.file).filter((file):file is string=>Boolean(file));const result:TesterResult={status,projectProfile:profile,assignedFiles,validatedFiles,unvalidatedFiles:[...(profile.unvalidatedFiles||[]),...assignedFiles.filter(file=>!validatedFiles.includes(file)&&!commands.some(command=>command.file===file))],commands:results,detectedCommands:commands.map(item=>item.label),executedCommands:results.map(item=>item.label),notes:profile.notes,blockReason:status==='BLOCKED'?'No safe validator configured for these files':undefined,progress:Math.round(results.length/commands.length*100),summary:status==='PASSED'?'All detected commands passed':status==='FAILED'?'One or more test commands failed':'No safe validator configured for these files',commandQa:{status,commands:results}};
    if(status!=='FAILED'&&this.config.browserQaEnabled){input.onProgress?.('Iniciando runtime');const manager=this.config.runtimeManager||new RuntimeSessionManager();const session=await manager.start(input.workspaceContext.location,{id:`runtime-${input.task.id}`,signal:input.signal,onProgress:input.onProgress});result.runtime={type:session.profile.type,baseUrl:session.baseUrl,status:session.status};if(session.status!=='ready'){result.browserQa={status:'BLOCKED',baseUrl:session.baseUrl,routes:[],consoleErrors:[],pageErrors:[],failedRequests:[],screenshots:[],durationMs:0,summary:session.stderr||session.profile.reason||'Runtime unavailable'};if(this.config.browserQaRequired)status='BLOCKED';else result.notes.push(`Browser QA indisponível: ${result.browserQa.summary}`);}else{try{const runner=this.config.browserQaRunner||new BrowserQaRunner();result.browserQa=await runner.run({baseUrl:session.baseUrl,routes:smokeRoutes(session.baseUrl,assignedFiles),screenshotDir:this.config.screenshotDir||resolvePath('.browser-qa',input.task.id),signal:input.signal,onProgress:input.onProgress});if(result.browserQa.status==='FAILED')status='FAILED';if(result.browserQa.status==='BLOCKED'&&this.config.browserQaRequired)status='BLOCKED';}finally{input.onProgress?.('Encerrando runtime');await manager.stop(session);}}result.status=status;result.summary=status==='PASSED'&&result.browserQa?'Command tests and browser smoke QA passed':result.summary;}
    return this.result(result);
  }
  private async runJson(command:TestCommand,location:string,maxOutput:number):Promise<TesterCommandResult>{const started=Date.now();try{const file=command.file||command.args[1];JSON.parse(readFileSync(resolveFile(location,file),'utf8'));return{commandId:command.id,label:command.label,status:'passed',exitCode:0,stdout:'JSON parse passed',stderr:'',durationMs:Date.now()-started};}catch(error){return{commandId:command.id,label:command.label,status:'failed',exitCode:1,stdout:'',stderr:bounded(String(error),maxOutput),durationMs:Date.now()-started};}}
  private result(result:TesterResult):ProviderExecutionResult{return{output:JSON.stringify(result),stdout:JSON.stringify(result),stderr:'',progressEvents:[],structuredResult:result as unknown as Record<string,unknown>,rawProviderResponse:{kind:'local-command-tester',status:result.status},tokenUsage:0,estimatedCost:undefined};}
  private runCommand(input:TesterInput,command:TestCommand,maxOutput:number):Promise<TesterCommandResult>{const platform=this.config.platform||process.platform;const spawn=this.config.spawn||createCliSpawn(platform);const started=Date.now();return new Promise((resolve,reject)=>{let stdout='',stderr='',settled=false,timedOut=false;const timeout=this.config.timeoutMs||command.timeoutMs;let timer:ReturnType<typeof setTimeout>|undefined;let heartbeat:ReturnType<typeof setInterval>|undefined;let child:any;const finish=(result:TesterCommandResult)=>{if(settled)return;settled=true;if(timer)clearTimeout(timer);if(heartbeat)clearInterval(heartbeat);this.active.delete(input.task.id);resolve({...result,stdout:bounded(stdout,maxOutput),stderr:bounded(stderr,maxOutput),durationMs:Date.now()-started});};try{child=spawn(executable(command.executable,platform),command.args,{cwd:command.cwd,env:this.config.env||process.env,stdio:['pipe','pipe','pipe'],shell:false});this.active.set(input.task.id,child);heartbeat=setInterval(()=>{if(!settled)input.onHeartbeat?.();},Math.max(25,Math.min(1000,Math.floor(timeout/3))));child.stdout.on('data',(chunk:Buffer)=>{stdout+=chunk.toString();});child.stderr.on('data',(chunk:Buffer)=>{stderr+=chunk.toString();});child.on('error',(error:Error)=>{if((error as NodeJS.ErrnoException).code==='ENOENT')finish({commandId:command.id,label:command.label,status:'blocked',exitCode:null,stdout:'',stderr:'executable not found',durationMs:0});else reject(Object.assign(new Error(String(error)),{kind:'cli_invocation_error'}));});child.on('close',(code:number|null)=>{if(timedOut)finish({commandId:command.id,label:command.label,status:'timed_out',exitCode:code,stdout,stderr,durationMs:0});else finish({commandId:command.id,label:command.label,status:code===0?'passed':'failed',exitCode:code,stdout,stderr,durationMs:0});});timer=setTimeout(()=>{if(settled)return;timedOut=true;child.kill('SIGTERM');},timeout);input.signal?.addEventListener('abort',()=>{if(settled)return;child.kill('SIGTERM');finish({commandId:command.id,label:command.label,status:'cancelled',exitCode:null,stdout,stderr,durationMs:0});reject(Object.assign(new Error('Command tester cancelled'),{kind:'cancelled'}));},{once:true});child.stdin.end();}catch(error){reject(Object.assign(new Error(String(error)),{kind:'cli_invocation_error'}));}});}
}
export type {ProjectTestProfile,TestCommand} from './project-detector.js';
export {detectProjectProfile,normalizeAssignedFiles} from './project-detector.js';
